
<!DOCTYPE html>
<!--[if IEMobile 7 ]><html class="no-js iem7"><![endif]-->
<!--[if lt IE 9]><html class="no-js lte-ie8"><![endif]-->
<!--[if (gt IE 8)|(gt IEMobile 7)|!(IEMobile)|!(IE)]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <title>A Statistics Blog</title>
  <meta name="author" content="Homer White">

  
  <meta name="description" content="Preliminaries Basic Scatterplot Including a Regression Line Playing With Points Preliminaries The function xyplot() makes scatterplots to indicate &hellip;">
  

  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  
  <link rel="canonical" href="http://homerhanumat.github.io">
  <link href="/favicon.png" rel="icon">
  <link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">
  <link href="/atom.xml" rel="alternate" title="A Statistics Blog" type="application/atom+xml">
  <script src="/javascripts/modernizr-2.0.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script>!window.jQuery && document.write(unescape('%3Cscript src="./javascripts/libs/jquery.min.js"%3E%3C/script%3E'))</script>
  <script src="/javascripts/octopress.js" type="text/javascript"></script>
  <!--Fonts from Google"s Web font directory at http://google.com/webfonts -->
<link href="http://fonts.googleapis.com/css?family=PT+Serif:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
<!-- MathJax -->
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true
    }
  });
</script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
      }
    });
</script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Queue(function() {
        var all = MathJax.Hub.getAllJax(), i;
        for(i=0; i < all.length; i += 1) {
            all[i].SourceElement().parentNode.className += ' has-jax';
        }
    });
</script>

<script type="text/javascript"
   src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>


  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-47254229-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>


</head>

<body   >
  <header role="banner"><hgroup>
  <h1><a href="/">A Statistics Blog</a></h1>
  <img src="/favicon.png" style="float:  right; align:  right; width: 20%;">
  
    <h2>R for Statistics Education, and information for the courses I teach.</h2>
  
 
</hgroup>

</header>
  <nav role="navigation"><ul class="subscription" data-subscription="rss">
  <li><a href="/atom.xml" rel="subscribe-rss" title="subscribe via RSS">RSS</a></li>
  
</ul>
  
<form action="http://google.com/search" method="get">
  <fieldset role="search">
    <input type="hidden" name="q" value="site:homerhanumat.github.io" />
    <input class="search" type="text" name="q" results="0" placeholder="Search"/>
  </fieldset>
</form>
  
<ul class="main-navigation">
  <li><a href="/">Blog</a></li>
  <li><a href="/blog/archives">Archives</a></li>
  <li><a href="/about/index.html">About</a></li>
</ul>

</nav>
  <div id="main">
    <div id="content">
      <div class="blog-index">
  
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/28/xyplottutorial/">Tutorial on Lattice&#8217;s Xyplot()</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-28T17:30:00-05:00" pubdate data-updated="true">Feb 28<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/02/28/xyplottutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/28/xyplottutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#basic-scatterplot">Basic Scatterplot</a></li>
  <li><a href="#including-a-regression-line">Including a Regression Line</a></li>
  <li><a href="#playing-with-points">Playing With Points</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p>The function <code>xyplot()</code> makes scatterplots to indicate the relationship between two numerical variables.  It comes from the <code>lattice</code> package for statistical graphics, which is pre-installed with every distribution of R.  Also, package <code>tigerstats</code> depends on lattice, so if you load <code>tigerstats</code>:</p>

<pre><code>require(tigerstats)
</code></pre>

<p>then <code>lattice</code> will be loaded as well.  If you don’t plan to use <code>tigerstats</code> but you want to use the function <code>xyplot()</code>, then make sure you load lattice:</p>

<pre><code>require(lattice)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need to install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<h2 id="basic-scatterplot">Basic Scatterplot</h2>

<p>Suppose you want to know:</p>

<blockquote>
  <p><em>Do students with higher GPA’s tend to drive more slowly than students with lower GPA’s?</em></p>
</blockquote>

<p>If so, then you might check to see if numerical variable <strong>fastest</strong> (in the <code>m111survey</code> data frame from the <code>tigerstats</code> package) is realted to the numerical variable <code>GPA</code>.  Then you can make a scatterplot as follows:</p>

<pre><code>xyplot(fastest~GPA,data=m111survey,
       xlab="grade point average",
       ylab="speed (mph)",
       main="Fastest Speed Ever Driven,\nby Grade Point Average")
</code></pre>

<p><img src="/images/figure/xytutfastestgpa.png" alt="plot of chunk xytutfastestgpa" /> </p>

<p>Note the use of:</p>

<ul>
  <li>the <code>xlab</code> argument to label the horizontal axis;</li>
  <li>the <code>ylab</code> argument to label the vertical axis, complete with units (miles per hour);</li>
  <li>the <code>main</code> argument to provide a brief but descriptive title for the graph;</li>
  <li>the “\n” to make two lines in the title (useful if you have a long title).</li>
</ul>

<p>When we think of one variable as explanatory and the other as the response, it is common to put the explanatory on the horizontal axis and the response on the vertical axis.  This is accomplished by the formula</p>

<script type="math/tex; mode=display">response \sim explanatory</script>

<h2 id="including-a-regression-line">Including a Regression Line</h2>

<p>If you want desire a regression line along with your scatterplot, use the argument <code>type</code>, as follows:</p>

<pre><code>xyplot(fastest~GPA,data=m111survey,
       xlab="grade point average",
       ylab="speed (mph)",
       main="Fastest Speed Ever Driven,\nby Grade Point Average",
       type=c("p","r"))
</code></pre>

<p><img src="/images/figure/xytutfastestgpareg.png" alt="plot of chunk xytutfastestgpareg" /> </p>

<p>The list given by <code>c("p","r")</code> tells <code>xyplot()</code> that we want both the points (“p”) and a regression line (“r”).</p>

<h2 id="playing-with-points">Playing With Points</h2>

<p>You can vary the type of point using the <code>pch</code> argument, and the color of the points with the <code>col</code> argument.  For example:</p>

<pre><code>xyplot(fastest~GPA,data=m111survey,
       xlab="grade point average",
       ylab="speed (mph)",
       main="Fastest Speed Ever Driven,\nby Grade Point Average",
       pch=19,col="blue")
</code></pre>

<p><img src="/images/figure/xytutfastestgpapoints.png" alt="plot of chunk xytutfastestgpapoints" /> </p>

<p>There are 25 different values for <code>pch</code>:  the integers 1 through 25.</p>

<p>There are many, many values for <code>col</code>.  You can explore 657 of them with the command:</p>

<pre><code>colors()
</code></pre>

</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/28/bwplottutorial/">Tutorial on Lattice&#8217;s Bwplot()</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-28T17:00:00-05:00" pubdate data-updated="true">Feb 28<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/02/28/bwplottutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/28/bwplottutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#one-numerical-variable">One Numerical Variable</a></li>
  <li><a href="#numerical-and-factor-variable">Numerical and Factor Variable</a></li>
  <li><a href="#warning">Warning</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p>The function <code>bwplot()</code> makes box-and-whisker plots for numerical variables.  It comes from the <code>lattice</code> package for statistical graphics, which is pre-installed with every distribution of R.  Also, package <code>tigerstats</code> depends on lattice, so if you load <code>tigerstats</code>:</p>

<pre><code>require(tigerstats)
</code></pre>

<p>then <code>lattice</code> will be loaded as well.  If you don’t plan to use <code>tigerstats</code> but you want to use the function <code>bwplot()</code>, then make sure you load lattice:</p>

<pre><code>require(lattice)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need to install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<h2 id="one-numerical-variable">One Numerical Variable</h2>

<p>For a box-and-whisker plot of the fastest speeds ever driven by students in the <code>m111survey</code> data frame, use the command:</p>

<pre><code>bwplot(~fastest,data=m111survey,
       xlab="speed (mph)",
       main="Fastest Speed Ever Driven")
</code></pre>

<p><img src="/images/figure/bwtutfastest.png" alt="plot of chunk bwtutfastest" /> </p>

<p>Note the use of:</p>

<ul>
  <li>the <code>xlab</code> argument to label the horizontal axis, complete with units (miles per hour);</li>
  <li>the <code>main</code> argument to provide a brief but descriptive title for the graph.</li>
</ul>

<h2 id="numerical-and-factor-variable">Numerical and Factor Variable</h2>

<p>Say you want to know:</p>

<blockquote>
  <p><em>Who tends to drive faster:  the guys or the gals?</em></p>
</blockquote>

<p>Then you are studying the relationship between the numerical variable <strong>fastest</strong> and the factor variable <strong>sex</strong>.  <code>bwplot()</code> will break the fastest speeds up by sex and parallel box-and-whisker plots, if you run the following command:</p>

<pre><code>bwplot(fastest~sex,data=m111survey,
       ylab="speed (mph)",
       main="Fastest Speed Ever Driven,\nby Sex of Subject")
</code></pre>

<p><img src="/images/figure/bwtutfastestsex.png" alt="plot of chunk bwtutfastestsex" /> </p>

<p>Note the use of the “\n” to create a two-line title.  This trick can come in handy if your title is long!</p>

<p>If you prefer your box-and-whisker plots to be horizontal, then you can reverse the order of the variables in the formula:</p>

<pre><code>bwplot(sex~fastest,data=m111survey,
       xlab="speed (mph)",
       main="Fastest Speed Ever Driven,\nby Sex of Subject")
</code></pre>

<p><img src="/images/figure/bwtutfastestsexhoriz.png" alt="plot of chunk bwtutfastestsexhoriz" /> </p>

<h2 id="warning">Warning</h2>

<p>Box-and-Whisker plots are great for studying:</p>

<ul>
  <li>one numerical variable</li>
  <li>the relationship between a numerical variable and a factor variable.</li>
</ul>

<p>However, if you try to study the relationship between two numerical variables with <code>bwplot()</code>, you will get bizarre results.</p>

<p>For example, suppose you want to study the relationship between fastest speed ever driven (<strong>fastest</strong>) and the grade point average (<strong>GPA</strong>) of the subjects in <code>m111survey</code>:</p>

<pre><code>bwplot(fastest~GPA,data=m111survey,
       ylab="speed (mph)",
       xbal="grade-point average",
       main="Fastes Speed Ever Driven,\nby Grade-Point Average")
</code></pre>

<p><img src="/images/figure/bwtutbad.png" alt="plot of chunk bwtutbad" /> </p>

<p><code>bwplot()</code> expects at least one of the two variable in the formula to be numerical.  When it is presented with two numerical variables it politely makes do—apparently converting <strong>fastest</strong> into a new factor variable—but the resulting graph doesn’t make any sense at all.</p>

<p>Use <code>xyplot()</code> (scatterplots) to study the relationship between two numerical variables.</p>
</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/28/proptestGCtutorial/">proptestGC() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-28T16:00:00-05:00" pubdate data-updated="true">Feb 28<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/02/28/proptestGCtutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/28/proptestGCtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#one-proportion-from-data-frame-read-this">One Proportion, From Data Frame (Read This!!)</a>    <ul>
      <li><a href="#confidence-interval-only">Confidence Interval Only</a></li>
      <li><a href="#interval-and-test">Interval and Test</a></li>
      <li><a href="#graph-of-the-p-value">Graph of the P-Value</a></li>
      <li><a href="#limiting-output">Limiting Output</a></li>
    </ul>
  </li>
  <li><a href="#one-proportion-from-summary-data">One Proportion, From Summary Data</a>    <ul>
      <li><a href="#confidence-interval-only-1">Confidence Interval Only</a></li>
      <li><a href="#interval-and-test-1">Interval and Test</a></li>
    </ul>
  </li>
  <li><a href="#difference-of-two-proportions-data-frame">Difference of Two Proportions, Data Frame</a>    <ul>
      <li><a href="#confidence-interval-only-2">Confidence Interval Only</a></li>
      <li><a href="#interval-and-test-2">Interval and Test</a></li>
      <li><a href="#order-of-the-groups">Order of the Groups</a></li>
    </ul>
  </li>
  <li><a href="#difference-of-two-proportions-summary-data">Difference of Two Proportions, Summary Data</a>    <ul>
      <li><a href="#confidence-interval-only-3">Confidence Interval Only</a></li>
      <li><a href="#interval-and-test-3">Interval and Test</a></li>
    </ul>
  </li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p>You use <code>proptestGC()</code> for inferential procedures regarding:</p>

<ul>
  <li>one population proportion $p$;</li>
  <li>the difference of two population proportions, $p_1 - p_2$.</li>
</ul>

<p>The function comes from the <code>tigerstats</code> package, so make sure that <code>tigerstats</code> is loaded:</p>

<pre><code>require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need to install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<h2 id="one-proportion-from-data-frame-read-this">One Proportion, From Data Frame (Read This!!)</h2>

<p>In inference procedures regarding one proportion, <code>binomtestGC()</code> is preferred over <code>proptestGC()</code>, especially at smaller sample sizes.  Nevertheless, read this section carefully.  It talks about:</p>

<ul>
  <li>what to count as a “success”,</li>
  <li>levels of confidence,</li>
  <li>types of Alternative Hypothesis,</li>
  <li>graphs of the P-value, and</li>
  <li>an option to limit output to the console</li>
</ul>

<p>in ways that apply to all uses of <code>proptestGC()</code>.</p>

<h3 id="confidence-interval-only">Confidence Interval Only</h3>

<p>In the <code>m111survey</code> data from the <code>tigerstats</code> package, suppose you want a 95%-confidence interval for:</p>

<blockquote>
  <p>$p =$ the proportion of all Georgetown College students who are female.</p>
</blockquote>

<p>Use the function:</p>

<pre><code>proptestGC(~sex,data=m111survey,
           success="female")

## 
## 
## Inferential Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 	Continuity Correction Applied to Test Statistic
## 
## 
## Descriptive Results:
## 
##  female  n estimated.prop
##      40 71         0.5634
## 
## 
## Inferential Results:
## 
## Estimate of p:	 0.5634 
## SE(p.hat):	 0.05886 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.448016            0.678745
</code></pre>

<p>Note that the <code>success</code> argument is set to “female” in order to make the function recognize $p$ as the population proportion of <em>females</em>, rather than the proportion of males (or of some other value of the variable in question).</p>

<p>To get any other level of confidence, you need to use the <code>conf.level</code> argument, indicating your desired level of confidence in decimal (not percentage) form.</p>

<p>For example, for a 90%-confidence interval for $\mu$, use</p>

<pre><code>proptestGC(~sex,data=m111survey,
           success="female",conf.level=0.90)

## 
## 
## Inferential Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 	Continuity Correction Applied to Test Statistic
## 
## 
## Descriptive Results:
## 
##  female  n estimated.prop
##      40 71         0.5634
## 
## 
## Inferential Results:
## 
## Estimate of p:	 0.5634 
## SE(p.hat):	 0.05886 
## 
## 90% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.466564            0.660197
</code></pre>

<h3 id="interval-and-test">Interval and Test</h3>

<p>If you want a test of significance as well as the confidence interval, then</p>

<ul>
  <li>use the <code>p</code> argument to set what the Null Hypothesis thinks that the value of $p$ is;</li>
  <li>use the <code>alternative</code> argument to specify the Alternative Hypothesis.</li>
</ul>

<p>For example, if the hypotheses are:</p>

<blockquote>
  <p>$H_0:  p = 0.50$</p>
</blockquote>

<blockquote>
  <p>$H_a: p &gt; 0.50$</p>
</blockquote>

<p>Then use:</p>

<pre><code>proptestGC(~sex,data=m111survey,p=0.50,
           success="female",alternative="greater")

## 
## 
## Inferential Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 	Continuity Correction Applied to Test Statistic
## 
## 
## Descriptive Results:
## 
##  female  n estimated.prop
##      40 71         0.5634
## 
## 
## Inferential Results:
## 
## Estimate of p:	 0.5634 
## SE(p.hat):	 0.05886 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.466564            1.000000             
## 
## Test of Significance:
## 
## 	H_0:  p = 0.5 
## 	H_a:  p &gt; 0.5 
## 
## 	Test Statistic:		z = 0.9571 
## 	P-value:		P = 0.1692
</code></pre>

<p>If the hypotheses are:</p>

<blockquote>
  <p>$H_0:  p = 0.50$</p>
</blockquote>

<blockquote>
  <p>$H_a: p &lt; 0.50$</p>
</blockquote>

<p>Then use:</p>

<pre><code>proptestGC(~sex,data=m111survey,p=0.50,
           success="female",alternative="less")

## 
## 
## Inferential Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 	Continuity Correction Applied to Test Statistic
## 
## 
## Descriptive Results:
## 
##  female  n estimated.prop
##      40 71         0.5634
## 
## 
## Inferential Results:
## 
## Estimate of p:	 0.5634 
## SE(p.hat):	 0.05886 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.000000            0.660197             
## 
## Test of Significance:
## 
## 	H_0:  p = 0.5 
## 	H_a:  p &lt; 0.5 
## 
## 	Test Statistic:		z = 1.196 
## 	P-value:		P = 0.8842
</code></pre>

<p>If the hypotheses are:</p>

<blockquote>
  <p>$H_0:  p = 0.50$</p>
</blockquote>

<blockquote>
  <p>$H_a: p \neq 0.50$</p>
</blockquote>

<p>Then use:</p>

<pre><code>proptestGC(~sex,data=m111survey,p=0.50,
        success="female",alternative="two.sided")

## 
## 
## Inferential Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 	Continuity Correction Applied to Test Statistic
## 
## 
## Descriptive Results:
## 
##  female  n estimated.prop
##      40 71         0.5634
## 
## 
## Inferential Results:
## 
## Estimate of p:	 0.5634 
## SE(p.hat):	 0.05886 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.448016            0.678745             
## 
## Test of Significance:
## 
## 	H_0:  p = 0.5 
## 	H_a:  p != 0.5 
## 
## 	Test Statistic:		z = 0.9571 
## 	P-value:		P = 0.3385
</code></pre>

<p>But note that the default value of <code>alternative</code> is “two.sided”, so if you want you could just leave it out and still get a two-sided test:</p>

<pre><code>proptestGC(~sex,data=m111survey,p=0.50,
           success="female")
</code></pre>

<h3 id="graph-of-the-p-value">Graph of the P-Value</h3>

<p>Anytime you want, you can get a graph of the $P$-value for your test, simply by setting the argument <code>graph</code> to <code>TRUE</code>:</p>

<pre><code>proptestGC(~sex,data=m111survey,p=0.50,
        success="female",graph=TRUE)

## 
## 
## Inferential Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 	Continuity Correction Applied to Test Statistic
## 
## 
## Descriptive Results:
## 
##  female  n estimated.prop
##      40 71         0.5634
## 
## 
## Inferential Results:
## 
## Estimate of p:	 0.5634 
## SE(p.hat):	 0.05886 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.448016            0.678745             
## 
## Test of Significance:
## 
## 	H_0:  p = 0.5 
## 	H_a:  p != 0.5 
## 
## 	Test Statistic:		z = 0.9571 
## 	P-value:		P = 0.3385
</code></pre>

<p><img src="/images/figure/proptesttutoneprop2sided.png" alt="plot of chunk proptesttutoneprop2sided" /> </p>

<h3 id="limiting-output">Limiting Output</h3>

<p>Sometimes you don’t need R to print so much information to the console.  If you want only the basics (such as a confidence interval, the test statistic and $P$-value), then set the <code>verbose</code> argument to <code>FALSE</code>:</p>

<pre><code>proptestGC(~sex,data=m111survey,p=0.50,
        success="female",verbose=FALSE)

## 
## 
## Inferential Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 	Continuity Correction Applied to Test Statistic
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.448016            0.678745             
## 
## 	Test Statistic:		z = 0.9571 
## 	P-value:		P = 0.3385
</code></pre>

<h2 id="one-proportion-from-summary-data">One Proportion, From Summary Data</h2>

<p>Again note that <code>binomtestGC()</code> is preferred in this situation, especially at smaller sample sizes.</p>

<h3 id="confidence-interval-only-1">Confidence Interval Only</h3>

<p>Say that you have taken a simple random sample of size $n=2500$ from the population of all registered voters in the U.S., and you find that 1325 of them favor the Affordable Care Act.  Suppose that you would like to make a confidence interval for</p>

<blockquote>
  <p>$p =$ the proportion of all registered voters in the U.S. who support the Act.</p>
</blockquote>

<p>You don’t have the raw data present in a data frame, but you have enough summary data to use <code>proptestGC()</code>.  You just have to set some new arguments:</p>

<ul>
  <li>set <code>x</code> to 1325, the number of “successes” you are counting up;</li>
  <li>set <code>n</code> to 2500, the sample size.</li>
</ul>

<p>So if you only want a 95%-confidence interval for $p$. use:</p>

<pre><code>proptestGC(x=1325,n=2500)

## 
## 
## Inferential Procedures for a Single Proportion p:
## 	Results based on Summary Data
## 	Continuity Correction Applied to Test Statistic
## 
## 
## Descriptive Results:
## 
##  successes    n estimated.prop
##       1325 2500           0.53
## 
## 
## Inferential Results:
## 
## Estimate of p:	 0.53 
## SE(p.hat):	 0.009982 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.510436            0.549564
</code></pre>

<h3 id="interval-and-test-1">Interval and Test</h3>

<p>If you also want to do a test of significance, again specify <code>p</code> and <code>alternative</code>.  For example, to test the hypotheses</p>

<blockquote>
  <p>$H_0:  p = 0.50$</p>
</blockquote>

<blockquote>
  <p>$H_a: p &lt; 0.50$</p>
</blockquote>

<p>use:</p>

<pre><code>proptestGC(x=1325,n=2500,
        p=0.50,,alternative="less")

## 
## 
## Inferential Procedures for a Single Proportion p:
## 	Results based on Summary Data
## 	Continuity Correction Applied to Test Statistic
## 
## 
## Descriptive Results:
## 
##  successes    n estimated.prop
##       1325 2500           0.53
## 
## 
## Inferential Results:
## 
## Estimate of p:	 0.53 
## SE(p.hat):	 0.009982 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.000000            0.546419             
## 
## Test of Significance:
## 
## 	H_0:  p = 0.5 
## 	H_a:  p &lt; 0.5 
## 
## 	Test Statistic:		z = 3.025 
## 	P-value:		P = 0.9988
</code></pre>

<h2 id="difference-of-two-proportions-data-frame">Difference of Two Proportions, Data Frame</h2>

<h3 id="confidence-interval-only-2">Confidence Interval Only</h3>

<p>Suppose</p>

<blockquote>
  <p>$p_1 =$ proportion of all GC females who believe they get enough sleep</p>
</blockquote>

<blockquote>
  <p>$p_2 =$ proportion of all GC males who believe they get enough sleep</p>
</blockquote>

<p>If you desire, say, an 85%-confidence interval for $p_1 - p_2$, then use:</p>

<pre><code>proptestGC(~sex+enough_Sleep,data=m111survey,
        success="yes",conf.level=0.85)

## 
## 
## Inferential Procedures for the Difference of Two Proportions p1-p2:
## 	 enough_Sleep grouped by sex 
## 
## 
## Descriptive Results:
## 
##        yes  n estimated.prop
## female  14 40         0.3500
## male    11 31         0.3548
## 
## 
## Inferential Results:
## 
## Estimate of p1-p2:	 -0.004839 
## SE(p1.hat - p2.hat):	 0.1143 
## 
## 85% Confidence Interval for p1-p2:
## 
##           lower.bound         upper.bound          
##           -0.169426           0.159749
</code></pre>

<h3 id="interval-and-test-2">Interval and Test</h3>

<p>If you want a 95%-confidence interval for $p_1 - p_2$ and you would like to test the hypotheses:</p>

<blockquote>
  <p>$H_0:  p_1 - p_2 = 0$</p>
</blockquote>

<blockquote>
  <p>$H_a: p_1 - p_2 \neq 0$</p>
</blockquote>

<p>then use:</p>

<pre><code>proptestGC(~sex+enough_Sleep,data=m111survey,
      success="yes",p=0)

## 
## 
## Inferential Procedures for the Difference of Two Proportions p1-p2:
## 	 enough_Sleep grouped by sex 
## 
## 
## Descriptive Results:
## 
##        yes  n estimated.prop
## female  14 40         0.3500
## male    11 31         0.3548
## 
## 
## Inferential Results:
## 
## Estimate of p1-p2:	 -0.004839 
## SE(p1.hat - p2.hat):	 0.1143 
## 
## 95% Confidence Interval for p1-p2:
## 
##           lower.bound         upper.bound          
##           -0.228929           0.219252             
## 
## Test of Significance:
## 
## 	H_0:  p1-p2 = 0
## 	H_a:  p1-p2 != 0
## 
## 	Test Statistic:		z = -0.04232 
## 	P-value:		P = 0.9662
</code></pre>

<p>Notice that this time:</p>

<ul>
  <li>you specified the Null’s belief about the value of $p_1-p_2$ using the <code>p</code> argument;</li>
  <li>you did not have to set <code>conf.level</code> to 0.95 (the default value of the argument is 0.95 already);</li>
  <li>you did not have to specify the two-sided alternative (the default value of <code>alternative</code> is already “two.sided”).</li>
</ul>

<h3 id="order-of-the-groups">Order of the Groups</h3>

<p>Suppose that in the previous situation you had defined:</p>

<blockquote>
  <p>$p_1 =$ proportion of all GC males who believe they get enough sleep</p>
</blockquote>

<blockquote>
  <p>$p_2 =$ proportion of all GC females who believe they get enough sleep</p>
</blockquote>

<p>Then for you, the first population is all GC males and the second population is all GC females.  In order to guarantee that R abides by your choice, use the argument <code>first</code>:</p>

<pre><code>proptestGC(~sex+enough_Sleep,data=m111survey,
      success="yes",p=0,first="male")

## 
## 
## Inferential Procedures for the Difference of Two Proportions p1-p2:
## 	 enough_Sleep grouped by sex 
## 
## 
## Descriptive Results:
## 
##        yes  n estimated.prop
## male    11 31         0.3548
## female  14 40         0.3500
## 
## 
## Inferential Results:
## 
## Estimate of p1-p2:	 0.004839 
## SE(p1.hat - p2.hat):	 0.1143 
## 
## 95% Confidence Interval for p1-p2:
## 
##           lower.bound         upper.bound          
##           -0.219252           0.228929             
## 
## Test of Significance:
## 
## 	H_0:  p1-p2 = 0
## 	H_a:  p1-p2 != 0
## 
## 	Test Statistic:		z = 0.04232 
## 	P-value:		P = 0.9662
</code></pre>

<h2 id="difference-of-two-proportions-summary-data">Difference of Two Proportions, Summary Data</h2>

<h3 id="confidence-interval-only-3">Confidence Interval Only</h3>

<p>Suppose that you have taken two independent samples from two populations (or performed a completely randomized experiment with two treatment groups), and you have the following summary data:</p>

<table>
  <thead>
    <tr>
      <th style="text-align: center">Group</th>
      <th style="text-align: center">Success Count</th>
      <th style="text-align: center">Sample Size</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align: center">group one</td>
      <td style="text-align: center">1325</td>
      <td style="text-align: center">2500</td>
    </tr>
    <tr>
      <td style="text-align: center">group two</td>
      <td style="text-align: center">905</td>
      <td style="text-align: center">1800</td>
    </tr>
  </tbody>
</table>

<p>You need to provide the summary data to the arguments <code>x</code> and <code>n</code> as lists using the <code>c()</code> function.  In each list, data from the first group should come first.</p>

<p>For a 95%-confidence interval for $p_1 - p_2$, use:</p>

<pre><code>proptestGC(x=c(1325,905),n=c(2500,1800))

## 
## 
## Inferential Procedures for the Difference of Two Proportions p1-p2:
## 	Results taken from summary data.
## 
## 
## Descriptive Results:
## 
##         successes    n estimated.prop
## Group 1      1325 2500         0.5300
## Group 2       905 1800         0.5028
## 
## 
## Inferential Results:
## 
## Estimate of p1-p2:	 0.02722 
## SE(p1.hat - p2.hat):	 0.01544 
## 
## 95% Confidence Interval for p1-p2:
## 
##           lower.bound         upper.bound          
##           -0.003048           0.057492
</code></pre>

<h3 id="interval-and-test-3">Interval and Test</h3>

<p>Suppose that you want a 90%-confidence interval for $p_1 - p_2$ and that you would like to test the hypotheses:</p>

<blockquote>
  <p>$H_0:  p_1 - p_2 = 0$</p>
</blockquote>

<blockquote>
  <p>$H_a: p_1 - p_2 &gt; 0$</p>
</blockquote>

<p>Suppose also that you want a graph of the $P$-value.  Then use:</p>

<pre><code>proptestGC(x=c(1325,905),n=c(2500,1800),
           p=0,conf.level=0.90,graph=TRUE)

## 
## 
## Inferential Procedures for the Difference of Two Proportions p1-p2:
## 	Results taken from summary data.
## 
## 
## Descriptive Results:
## 
##         successes    n estimated.prop
## Group 1      1325 2500         0.5300
## Group 2       905 1800         0.5028
## 
## 
## Inferential Results:
## 
## Estimate of p1-p2:	 0.02722 
## SE(p1.hat - p2.hat):	 0.01544 
## 
## 90% Confidence Interval for p1-p2:
## 
##           lower.bound         upper.bound          
##           0.001819            0.052626             
## 
## Test of Significance:
## 
## 	H_0:  p1-p2 = 0
## 	H_a:  p1-p2 != 0
## 
## 	Test Statistic:		z = 1.763 
## 	P-value:		P = 0.07797
</code></pre>

<p><img src="/images/figure/proptesttut2propssummary.png" alt="plot of chunk proptesttut2propssummary" /> </p>

</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/28/binomtestGCtutorial/">binomtestGC() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-28T15:00:00-05:00" pubdate data-updated="true">Feb 28<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/02/28/binomtestGCtutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/28/binomtestGCtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#working-from-a-data-frame">Working from a Data Frame</a></li>
  <li><a href="#setting-the-confidence-level">Setting the Confidence Level</a></li>
  <li><a href="#significance-tests">Significance Tests</a></li>
  <li><a href="#a-graph-of-the-p-value">A Graph of the $P$-Value</a></li>
  <li><a href="#working-with-summary-data">Working with Summary Data</a></li>
  <li><a href="#want-less-output">Want Less Output?</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p>You use <code>binomtestGC()</code> for inferential procedures regarding one population proportion $p$.  The function <code>proptestGC()</code> can also handle this analysis, but <code>binomtestGC()</code> computes exact $P$-values rather than employing the (sometimes crude) normal approximation, and it also uses a somewhat more sophisticated method to compute confidence intervals.</p>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need to install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<h2 id="working-from-a-data-frame">Working from a Data Frame</h2>

<p>Let</p>

<blockquote>
  <p>$p =$ the proportion of all Georgetown College students who are female</p>
</blockquote>

<p>Suppose that you would like a 95%-confidence interval for $p$.  Since <strong>sex</strong> is present as a variable in the <code>m111survey</code> data frame, so you can use formula-data input in the usual way to direct the attention of <code>binomtestGC()</code> to <strong>sex</strong> as the data.</p>

<p>However, when the function looks at <strong>sex</strong>, it sees the values “female” and “male”.  It needs to be told which of them to count as a “success” when it computes the sample proportion $\hat{p}$.  You do this with the <code>success</code> argument.</p>

<p>So you use:</p>

<pre><code>binomtestGC(~sex,data=m111survey,
            success="female")

## 
## Exact Binomial Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 
## 
## Descriptive Results:  40 successes in 71 trials
## 
## Inferential Results:
## 
## Estimate of p:	 0.5634 
## SE(p.hat):	 0.0589 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.440455            0.680850
</code></pre>

<p>Note that you did not have to specify a confidence level:  by default, the function returns a 95%-confidence interval.</p>

<h2 id="setting-the-confidence-level">Setting the Confidence Level</h2>

<p>You can get intervals with other levels of confidence besides 95%, simply by setting the argument <code>conf.level</code> to the desired level (expressed as a proportion, rather than as a percentage).</p>

<p>For example, if you want a 90%-confidence interval for $p$, then you use:</p>

<pre><code>binomtestGC(~sex,data=m111survey,
            success="female",conf.level=0.90)

## 
## Exact Binomial Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 
## 
## Descriptive Results:  40 successes in 71 trials
## 
## Inferential Results:
## 
## Estimate of p:	 0.5634 
## SE(p.hat):	 0.0589 
## 
## 90% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.458929            0.663741
</code></pre>

<h2 id="significance-tests">Significance Tests</h2>

<p>Let’s now let</p>

<blockquote>
  <p>$p =$ the proportion of all Georgetown College students who are male</p>
</blockquote>

<p>(Notice that, for variety’s sake, we have switched to counting up males.)</p>

<p>Suppose that we want to perform a test of significance.  Then we would use:</p>

<ul>
  <li>the argument <code>p</code> to indicate the belief of the Null Hypothesis as to the value of $p$;</li>
  <li>the argument <code>alternative</code> to specify the direction of the Alternative Hypothesis.  The possible values of this argument are:
    <ul>
      <li>“less”</li>
      <li>“greater”</li>
      <li>“two.sided” (the default value)</li>
    </ul>
  </li>
</ul>

<p>For example, if we want to test the hypotheses:</p>

<blockquote>
  <p>$H_0 : p = 0.50$</p>
</blockquote>

<blockquote>
  <p>$H_a : p &lt; 0.50$</p>
</blockquote>

<p>then we use</p>

<pre><code>binomtestGC(~sex,data=m111survey,
            success="male",p=0.50,
            alternative="less")

## 
## Exact Binomial Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 
## 
## Descriptive Results:  31 successes in 71 trials
## 
## Inferential Results:
## 
## Estimate of p:	 0.4366 
## SE(p.hat):	 0.0589 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.000000            0.541071             
## 
## Test of Significance:
## 
## 	H_0:  p = 0.5 
## 	H_a:  p &lt; 0.5 
## 
## 	P-value:		P = 0.1712
</code></pre>

<p>To test the hypotheses</p>

<blockquote>
  <p>$H_0 : p = 0.50$</p>
</blockquote>

<blockquote>
  <p>$H_a : p &gt; 0.50$</p>
</blockquote>

<p>then we use</p>

<pre><code>binomtestGC(~sex,data=m111survey,
            success="male",p=0.50,
            alternative="greater")

## 
## Exact Binomial Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 
## 
## Descriptive Results:  31 successes in 71 trials
## 
## Inferential Results:
## 
## Estimate of p:	 0.4366 
## SE(p.hat):	 0.0589 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.336259            1.000000             
## 
## Test of Significance:
## 
## 	H_0:  p = 0.5 
## 	H_a:  p &gt; 0.5 
## 
## 	P-value:		P = 0.8825
</code></pre>

<p>If we want a two-side test</p>

<blockquote>
  <p>$H_0 : p = 0.50$</p>
</blockquote>

<blockquote>
  <p>$H_a : p \neq 0.50$</p>
</blockquote>

<p>then we use</p>

<pre><code>binomtestGC(~sex,data=m111survey,
            success="male",p=0.50)

## 
## Exact Binomial Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 
## 
## Descriptive Results:  31 successes in 71 trials
## 
## Inferential Results:
## 
## Estimate of p:	 0.4366 
## SE(p.hat):	 0.0589 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.319150            0.559545             
## 
## Test of Significance:
## 
## 	H_0:  p = 0.5 
## 	H_a:  p != 0.5 
## 
## 	P-value:		P = 0.3425
</code></pre>

<p>Note that there is no need to specify an alternative, since the default value of <code>alternative</code> is “two.sided”.</p>

<h2 id="a-graph-of-the-p-value">A Graph of the $P$-Value</h2>

<p>Fro a one-sided test, we can get a graph of the $P$-value simply by setting the argument <code>graph</code> to <code>TRUE</code>:</p>

<pre><code>binomtestGC(~sex,data=m111survey,
            success="male",p=0.50,
            alternative="less",
            graph=TRUE)

## 
## Exact Binomial Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 
## 
## Descriptive Results:  31 successes in 71 trials
## 
## Inferential Results:
## 
## Estimate of p:	 0.4366 
## SE(p.hat):	 0.0589 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.000000            0.541071             
## 
## Test of Significance:
## 
## 	H_0:  p = 0.5 
## 	H_a:  p &lt; 0.5 
## 
## 	P-value:		P = 0.1712
</code></pre>

<p><img src="/images/figure/binomtesttutsexless.png" alt="plot of chunk binomtesttutsexless" /> </p>

<p>For a two-sided test, the function gets the $P$-value by doubling an appropriate one-sided $P$-value, so no graph represents the $P$-value very well.  Hence the function will refuse to provide a graph in that case.</p>

<h2 id="working-with-summary-data">Working with Summary Data</h2>

<p>Suppose that in a poll of 2500 randomly selected registered voters, 1325 of them indicated support for the Affordable Care Act.  Suppose that we want a confidence interval for $p$, the proportion of all registered voters who favor the Act, and a two-sided test of significance with the hypotheses:</p>

<blockquote>
  <p>$H_0 : p = 0.50$</p>
</blockquote>

<blockquote>
  <p>$H_a : p \neq 0.50$</p>
</blockquote>

<p>We do not have raw data from a data frame, but the summary information we are given will suffice for <code>binomtestGC()</code>.  We need only:</p>

<ul>
  <li>set the argument <code>x</code> to the number of successes (the count of people who said they support the Act), and</li>
  <li>set the argument <code>n</code> to the sample size.</li>
</ul>

<p>Hence we use:</p>

<pre><code>binomtestGC(x=1325,n=2500,p=0.50)

## 
## Exact Binomial Procedures for a Single Proportion p:
## 	Results based on Summary Data
## 
## 
## Descriptive Results:  1325 successes in 2500 trials
## 
## Inferential Results:
## 
## Estimate of p:	 0.53 
## SE(p.hat):	 0.01 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.510210            0.549719             
## 
## Test of Significance:
## 
## 	H_0:  p = 0.5 
## 	H_a:  p != 0.5 
## 
## 	P-value:		P = 0.0029
</code></pre>

<h2 id="want-less-output">Want Less Output?</h2>

<p>Sometimes you don’t need to see quite so much output to the console. If you only wantf the basics (confidence interval for $p$ and $P$-value for your test), then set the argument <code>verbose</code> to <code>FALSE</code>.</p>

<p>For example, if you want a 90%-confidence interval and a two-sided test then try:</p>

<pre><code>binomtestGC(~sex,data=m111survey,
            success="male",p=0.50,
            verbose=FALSE)

## 
## Exact Binomial Procedures for a Single Proportion p:
## 	Variable under study is sex 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.319150            0.559545             
## 
## 	P-value:		P = 0.3425
</code></pre>

</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/27/ttestGCtutorial/">ttestGC() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-27T15:00:00-05:00" pubdate data-updated="true">Feb 27<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/02/27/ttestGCtutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/27/ttestGCtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#one-mean-from-data-frame-read-this">One Mean, From Data Frame (Read This!!)</a>    <ul>
      <li><a href="#confidence-interval-only">Confidence Interval Only</a></li>
      <li><a href="#interval-and-test">Interval and Test</a></li>
      <li><a href="#graph-of-the-p-value">Graph of the P-Value</a></li>
      <li><a href="#limiting-output">Limiting Output</a></li>
    </ul>
  </li>
  <li><a href="#one-mean-from-summary-data">One Mean, From Summary Data</a>    <ul>
      <li><a href="#confidence-interval-only-1">Confidence Interval Only</a></li>
      <li><a href="#interval-and-test-1">Interval and Test</a></li>
    </ul>
  </li>
  <li><a href="#difference-of-two-means-data-frame">Difference of Two Means, Data Frame</a>    <ul>
      <li><a href="#confidence-interval-only-2">Confidence Interval Only</a></li>
      <li><a href="#interval-and-test-2">Interval and Test</a></li>
      <li><a href="#order-of-the-groups">Order of the Groups</a></li>
    </ul>
  </li>
  <li><a href="#difference-of-two-means-summary-data">Difference of Two Means, Summary Data</a>    <ul>
      <li><a href="#confidence-interval-only-3">Confidence Interval Only</a></li>
      <li><a href="#interval-and-test-3">Interval and Test</a></li>
    </ul>
  </li>
  <li><a href="#mean-of-differences">Mean of Differences</a>    <ul>
      <li><a href="#both-variables-in-the-data-frame">Both Variables in the Data Frame</a>        <ul>
          <li><a href="#confidence-interval-only-4">Confidence Interval Only</a></li>
          <li><a href="#interval-and-test-4">Interval and Test</a></li>
        </ul>
      </li>
      <li><a href="#the-difference-is-in-the-data-frame">The Difference is in the Data Frame</a>        <ul>
          <li><a href="#confidence-interval-only-5">Confidence Interval Only</a></li>
          <li><a href="#interval-and-test-5">Interval and Test</a></li>
        </ul>
      </li>
    </ul>
  </li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p>You use <code>ttestGC()</code> for inferential procedures regarding:</p>

<ul>
  <li>one population mean $\mu$;</li>
  <li>the difference of two population means, $\mu_1 - \mu_2$;</li>
  <li>the mean $\mu_d$ of paired differences in a population.</li>
</ul>

<p>The function comes from the <code>tigerstats</code> package, so make sure that <code>tigerstats</code> is loaded:</p>

<pre><code>require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need to install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<h2 id="one-mean-from-data-frame-read-this">One Mean, From Data Frame (Read This!!)</h2>

<p>Read this section carefully.  It talks about:</p>

<ul>
  <li>levels of confidence,</li>
  <li>types of Alternative Hypothesis,</li>
  <li>graphs of the P-value, and</li>
  <li>an option to limit output to the console</li>
</ul>

<p>in ways that apply to all uses of <code>ttestGC()</code>.</p>

<h3 id="confidence-interval-only">Confidence Interval Only</h3>

<p>In the <code>m111survey</code> data from the <code>tigerstats</code> package, suppose you want a 95%-confidence interval for:</p>

<blockquote>
  <p>$\mu =$ the mean fastest speed ever driven, for all GC students.</p>
</blockquote>

<p>Use the function:</p>

<pre><code>ttestGC(~fastest,data=m111survey)

## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##  variable  mean    sd  n
##   fastest 105.9 20.88 71
## 
## 
## Inferential Results:
## 
## Estimate of mu:	 105.9 
## SE(x.bar):	 2.478 
## 
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           100.959833          110.842984
</code></pre>

<p>To get any other level of confidence, you need to use the <code>conf.level</code> argument, indicating your desired level of confidence in decimal (not percentage) form.</p>

<p>For example, for a 90%-confidence interval for $\mu$, use</p>

<pre><code>ttestGC(~fastest,data=m111survey,conf.level=0.90)

## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##  variable  mean    sd  n
##   fastest 105.9 20.88 71
## 
## 
## Inferential Results:
## 
## Estimate of mu:	 105.9 
## SE(x.bar):	 2.478 
## 
## 90% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           101.771329          110.031488
</code></pre>

<h3 id="interval-and-test">Interval and Test</h3>

<p>If you want a test of significance as well as the confidence interval, then</p>

<ul>
  <li>use the <code>mu</code> argument to set what the Null Hypothesis thinks that the value of $\mu$ is;</li>
  <li>use the <code>alternative</code> argument to specify the Alternative Hypothesis.</li>
</ul>

<p>For example, if the hypotheses are:</p>

<blockquote>
  <p>$H_0:  \mu = 100$</p>
</blockquote>

<blockquote>
  <p>$H_a: \mu &gt; 100$</p>
</blockquote>

<p>Then use:</p>

<pre><code>ttestGC(~fastest,data=m111survey,mu=100,alternative="greater")

## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##  variable  mean    sd  n
##   fastest 105.9 20.88 71
## 
## 
## Inferential Results:
## 
## Estimate of mu:	 105.9 
## SE(x.bar):	 2.478 
## 
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           101.771329          Inf                  
## 
## Test of Significance:
## 
## 	H_0:  mu = 100 
## 	H_a:  mu &gt; 100 
## 
## 	Test Statistic:		t = 2.382 
## 	Degrees of Freedom:	  70 
## 	P-value:		P = 0.009974
</code></pre>

<p>If the hypotheses are:</p>

<blockquote>
  <p>$H_0:  \mu = 100$</p>
</blockquote>

<blockquote>
  <p>$H_a: \mu &lt; 100$</p>
</blockquote>

<p>Then use:</p>

<pre><code>ttestGC(~fastest,data=m111survey,mu=100,alternative="less")

## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##  variable  mean    sd  n
##   fastest 105.9 20.88 71
## 
## 
## Inferential Results:
## 
## Estimate of mu:	 105.9 
## SE(x.bar):	 2.478 
## 
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           -Inf                110.031488           
## 
## Test of Significance:
## 
## 	H_0:  mu = 100 
## 	H_a:  mu &lt; 100 
## 
## 	Test Statistic:		t = 2.382 
## 	Degrees of Freedom:	  70 
## 	P-value:		P = 0.99
</code></pre>

<p>If the hypotheses are:</p>

<blockquote>
  <p>$H_0:  \mu = 100$</p>
</blockquote>

<blockquote>
  <p>$H_a: \mu \neq 100$</p>
</blockquote>

<p>Then use:</p>

<pre><code>ttestGC(~fastest,data=m111survey,mu=100,
        alternative="two.sided")

## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##  variable  mean    sd  n
##   fastest 105.9 20.88 71
## 
## 
## Inferential Results:
## 
## Estimate of mu:	 105.9 
## SE(x.bar):	 2.478 
## 
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           100.959833          110.842984           
## 
## Test of Significance:
## 
## 	H_0:  mu = 100 
## 	H_a:  mu != 100 
## 
## 	Test Statistic:		t = 2.382 
## 	Degrees of Freedom:	  70 
## 	P-value:		P = 0.01995
</code></pre>

<p>But note that the default value of <code>alternative</code> is “two.sided”, so if you want you could just leave it out and still get a two-sided test:</p>

<pre><code>ttestGC(~fastest,data=m111survey,mu=100)
</code></pre>

<h3 id="graph-of-the-p-value">Graph of the P-Value</h3>

<p>Anytime you want, you can get a graph of the $P$-value for your test, simply by setting the argument <code>graph</code> to <code>TRUE</code>:</p>

<pre><code>ttestGC(~fastest,data=m111survey,mu=100,
        alternative="two.sided",graph=TRUE)

## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##  variable  mean    sd  n
##   fastest 105.9 20.88 71
## 
## 
## Inferential Results:
## 
## Estimate of mu:	 105.9 
## SE(x.bar):	 2.478 
## 
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           100.959833          110.842984           
## 
## Test of Significance:
## 
## 	H_0:  mu = 100 
## 	H_a:  mu != 100 
## 
## 	Test Statistic:		t = 2.382 
## 	Degrees of Freedom:	  70 
## 	P-value:		P = 0.01995
</code></pre>

<p><img src="/images/figure/ttesttutonemean2sided.png" alt="plot of chunk ttesttutonemean2sided" /> </p>

<h3 id="limiting-output">Limiting Output</h3>

<p>Sometimes you don’t need R to print so much information to the console.  If you want only the basics (such as a confidence interval, the test statistic and $P$-value), then set the <code>verbose</code> argument to <code>FALSE</code>:</p>

<pre><code>ttestGC(~fastest,data=m111survey,mu=100,
        alternative="two.sided",verbose=FALSE)

## 
## 
## Inferential Procedures for One Mean mu:
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           100.959833          110.842984           
## 
## 	Test Statistic:		t = 2.382 
## 	Degrees of Freedom:	  70 
## 	P-value:		P = 0.01995
</code></pre>

<h2 id="one-mean-from-summary-data">One Mean, From Summary Data</h2>

<h3 id="confidence-interval-only-1">Confidence Interval Only</h3>

<p>Say that you have taken a simple random sample from some large population, and:</p>

<ul>
  <li>the sample mean is $\bar{x}=30$,</li>
  <li>the sample standard deviation is $s=4$,</li>
  <li>the sample size was $n=40$.</li>
</ul>

<p>You don’t have the raw data present in a data frame, but you have enough summary data to use <code>ttestGC()</code>.  You just have to set some new arguments:</p>

<ul>
  <li>set <code>mean</code> to the sample mean;</li>
  <li>set <code>sd</code> to the sample standard deviation;</li>
  <li>set <code>n</code> to the sample size.</li>
</ul>

<p>So if you only want a 95%-confidence interval for $\mu$. use:</p>

<pre><code>ttestGC(mean=30,sd=4,n=40)

## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##  mean sd  n
##    30  4 40
## 
## 
## Inferential Results:
## 
## Estimate of mu:	 30 
## SE(x.bar):	 0.6325 
## 
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           28.720738           31.279262
</code></pre>

<h3 id="interval-and-test-1">Interval and Test</h3>

<p>If you also want to do a test of significance, again specify <code>mu</code> and <code>alternative</code>.  For example, to test the hypotheses</p>

<blockquote>
  <p>$H_0:  \mu = 32$</p>
</blockquote>

<blockquote>
  <p>$H_a: \mu &lt; 32$</p>
</blockquote>

<p>use:</p>

<pre><code>ttestGC(mean=30,sd=4,n=40,
        mu=32,alternative="less")

## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##  mean sd  n
##    30  4 40
## 
## 
## Inferential Results:
## 
## Estimate of mu:	 30 
## SE(x.bar):	 0.6325 
## 
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           -Inf                31.065609            
## 
## Test of Significance:
## 
## 	H_0:  mu = 32 
## 	H_a:  mu &lt; 32 
## 
## 	Test Statistic:		t = -3.162 
## 	Degrees of Freedom:	  39 
## 	P-value:		P = 0.001514
</code></pre>

<h2 id="difference-of-two-means-data-frame">Difference of Two Means, Data Frame</h2>

<h3 id="confidence-interval-only-2">Confidence Interval Only</h3>

<p>Suppose</p>

<blockquote>
  <p>$\mu_1 =$ mean fastest speed ever driven, by all GC females</p>
</blockquote>

<blockquote>
  <p>$\mu_2 =$ mean fastest speed ever driven, by all GC males</p>
</blockquote>

<p>If you desire, say, an 85%-confidence interval for $\mu_1 - \mu_2$, then use:</p>

<pre><code>ttestGC(fastest~sex,data=m111survey,
        conf.level=0.85)

## 
## 
## Inferential Procedures for the Difference of Two Means mu1-mu2:
## 	(Welch's Approximation Used for Degrees of Freedom)
## 	 fastest grouped by sex 
## 
## 
## Descriptive Results:
## 
##   group  mean    sd  n
##  female 100.0 17.61 40
##    male 113.5 22.57 31
## 
## 
## Inferential Results:
## 
## Estimate of mu1-mu2:	 -13.4 
## SE(mu1.hat - mu2.hat):	 4.918 
## 
## 85% Confidence Interval for mu1-mu2:
## 
##           lower.bound         upper.bound          
##           -20.579953          -6.223273
</code></pre>

<h3 id="interval-and-test-2">Interval and Test</h3>

<p>If you want a 95%-confidence interval for $\mu_1 - \mu_2$ and you would like to test the hypotheses:</p>

<blockquote>
  <p>$H_0:  \mu_1 - \mu_2 = 0$</p>
</blockquote>

<blockquote>
  <p>$H_a: \mu_1 - \mu_2 \neq 0$</p>
</blockquote>

<p>then use:</p>

<pre><code>ttestGC(fastest~sex,data=m111survey,
      mu=0)

## 
## 
## Inferential Procedures for the Difference of Two Means mu1-mu2:
## 	(Welch's Approximation Used for Degrees of Freedom)
## 	 fastest grouped by sex 
## 
## 
## Descriptive Results:
## 
##   group  mean    sd  n
##  female 100.0 17.61 40
##    male 113.5 22.57 31
## 
## 
## Inferential Results:
## 
## Estimate of mu1-mu2:	 -13.4 
## SE(mu1.hat - mu2.hat):	 4.918 
## 
## 95% Confidence Interval for mu1-mu2:
## 
##           lower.bound         upper.bound          
##           -23.254640          -3.548586            
## 
## Test of Significance:
## 
## 	H_0:  mu1-mu2 = 0 
## 	H_a:  mu1-mu2 != 0 
## 
## 	Test Statistic:		t = -2.725 
## 	Degrees of Freedom:	  55.49 
## 	P-value:		P = 0.008579
</code></pre>

<p>Notice that this time:</p>

<ul>
  <li>you specified the Null’s belief about the value of $\mu<em>1-\mu</em>2$ using the <code>mu</code> argument;</li>
  <li>you did not have to set <code>conf.level</code> to 0.95 (the default value of the argument is 0.95 already);</li>
  <li>you did not have to specify the two-sided alternative (the default value of <code>alternative</code> is already “two.sided”).</li>
</ul>

<h3 id="order-of-the-groups">Order of the Groups</h3>

<p>Suppose that in the previous situation you had defined:</p>

<blockquote>
  <p>$\mu_1 =$ mean fastest speed ever driven, by all GC males</p>
</blockquote>

<blockquote>
  <p>$\mu_2 =$ mean fastest speed ever driven, by all GC females</p>
</blockquote>

<p>Then for you, the first population is all GC males and the second population is all GC females.  In order to guarantee that R abides by your choice, use the argument <code>first</code>:</p>

<pre><code>ttestGC(fastest~sex,data=m111survey,
      mu=0,first="male")

## 
## 
## Inferential Procedures for the Difference of Two Means mu1-mu2:
## 	(Welch's Approximation Used for Degrees of Freedom)
## 	 fastest grouped by sex 
## 
## 
## Descriptive Results:
## 
##   group  mean    sd  n
##    male 113.5 22.57 31
##  female 100.0 17.61 40
## 
## 
## Inferential Results:
## 
## Estimate of mu1-mu2:	 13.4 
## SE(mu1.hat - mu2.hat):	 4.918 
## 
## 95% Confidence Interval for mu1-mu2:
## 
##           lower.bound         upper.bound          
##           3.548586            23.254640            
## 
## Test of Significance:
## 
## 	H_0:  mu1-mu2 = 0 
## 	H_a:  mu1-mu2 != 0 
## 
## 	Test Statistic:		t = 2.725 
## 	Degrees of Freedom:	  55.49 
## 	P-value:		P = 0.008579
</code></pre>

<h2 id="difference-of-two-means-summary-data">Difference of Two Means, Summary Data</h2>

<h3 id="confidence-interval-only-3">Confidence Interval Only</h3>

<p>Suppose that you have taken two independent samples from two populations (or performed a completely randomized experiment with two treatment groups), and you have the following summary data:</p>

<table>
  <thead>
    <tr>
      <th style="text-align: center">Group</th>
      <th style="text-align: center">$\bar{x}$</th>
      <th style="text-align: center">$s$</th>
      <th style="text-align: center">$n$</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align: center">group one</td>
      <td style="text-align: center">32</td>
      <td style="text-align: center">4.2</td>
      <td style="text-align: center">33</td>
    </tr>
    <tr>
      <td style="text-align: center">group two</td>
      <td style="text-align: center">30</td>
      <td style="text-align: center">5.1</td>
      <td style="text-align: center">42</td>
    </tr>
  </tbody>
</table>

<p>You need to provide the summary data to the arguments <code>mean</code>, <code>sd</code> and <code>n</code>, as lists using the <code>c()</code> function.  In each list, data from the first group should come first.</p>

<p>For a 95%-confidence interval for $\mu_1 - \mu_2$, use:</p>

<pre><code>ttestGC(mean=c(32,30),sd=c(4.2,5.1),n=c(33,42))

## 
## 
## Inferential Procedures for the Difference of Two Means mu1-mu2:
## 	(Welch's Approximation Used for Degrees of Freedom)
## 	Results from summary data.
## 
## 
## Descriptive Results:
## 
##    group mean  sd  n
##  Group 1   32 4.2 33
##  Group 2   30 5.1 42
## 
## 
## Inferential Results:
## 
## Estimate of mu1-mu2:	 2 
## SE(mu1.hat - mu2.hat):	 1.074 
## 
## 95% Confidence Interval for mu1-mu2:
## 
##           lower.bound         upper.bound          
##           -0.140898           4.140898
</code></pre>

<h3 id="interval-and-test-3">Interval and Test</h3>

<p>Suppose that you want a 90%-confidence interval for $\mu_1 - \mu_2$ and that you would like to test the hypotheses:</p>

<blockquote>
  <p>$H_0:  \mu_1 - \mu_2 = 0$</p>
</blockquote>

<blockquote>
  <p>$H_a: \mu_1 - \mu_2 &gt; 0$</p>
</blockquote>

<p>Suppose also that want a graph of the $P$-value.  Then use:</p>

<pre><code>ttestGC(mean=c(32,30),sd=c(4.2,5.1),n=c(33,42),
        mu=0,alternative="greater",
        conf.level=0.90,graph=TRUE)

## 
## 
## Inferential Procedures for the Difference of Two Means mu1-mu2:
## 	(Welch's Approximation Used for Degrees of Freedom)
## 	Results from summary data.
## 
## 
## Descriptive Results:
## 
##    group mean  sd  n
##  Group 1   32 4.2 33
##  Group 2   30 5.1 42
## 
## 
## Inferential Results:
## 
## Estimate of mu1-mu2:	 2 
## SE(mu1.hat - mu2.hat):	 1.074 
## 
## 90% Confidence Interval for mu1-mu2:
## 
##           lower.bound         upper.bound          
##           0.610797            Inf                  
## 
## Test of Significance:
## 
## 	H_0:  mu1-mu2 = 0 
## 	H_a:  mu1-mu2 &gt; 0 
## 
## 	Test Statistic:		t = 1.862 
## 	Degrees of Freedom:	  72.82 
## 	P-value:		P = 0.03333
</code></pre>

<p><img src="/images/figure/ttesttut2meanssummary.png" alt="plot of chunk ttesttut2meanssummary" /> </p>

<h2 id="mean-of-differences">Mean of Differences</h2>

<h3 id="both-variables-in-the-data-frame">Both Variables in the Data Frame</h3>

<h4 id="confidence-interval-only-4">Confidence Interval Only</h4>

<p>Suppose that</p>

<blockquote>
  <p>$\mu_d =$ mean difference (ideal height minus actual height) for all Georgetown College student.</p>
</blockquote>

<p>Both of the relevant variables—<strong>ideal_ht</strong> and <strong>height</strong>—are present in the <code>m111survey</code> data frame.</p>

<p>If you want a 95%-confidence interval for $\mu_d$, then use:</p>

<pre><code>ttestGC(~ideal_ht - height,data=m111survey)

## 
## 
## Inferential Procedures for the Difference of Means mu-d:
## 	 height minus ideal_ht 
## 
## 
## Descriptive Results:
## 
##         Difference mean.difference sd.difference  n
##  ideal_ht - height           1.946         3.206 69
## 
## 
## Inferential Results:
## 
## Estimate of mu-d:	 1.946 
## SE(d.bar):	 0.3859 
## 
## 95% Confidence Interval for mu-d:
## 
##           lower.bound         upper.bound          
##           1.175528            2.715776
</code></pre>

<p>Note how the “~” character signals the presence of a formula.</p>

<h4 id="interval-and-test-4">Interval and Test</h4>

<p>In order to test:</p>

<blockquote>
  <p>$H_0:  \mu_d = 0$</p>
</blockquote>

<blockquote>
  <p>$H_a: \mu_d &gt; 0$</p>
</blockquote>

<p>use:</p>

<pre><code>ttestGC(~ideal_ht - height,data=m111survey,
        mu=0,alternative="greater")

## 
## 
## Inferential Procedures for the Difference of Means mu-d:
## 	 height minus ideal_ht 
## 
## 
## Descriptive Results:
## 
##         Difference mean.difference sd.difference  n
##  ideal_ht - height           1.946         3.206 69
## 
## 
## Inferential Results:
## 
## Estimate of mu-d:	 1.946 
## SE(d.bar):	 0.3859 
## 
## 95% Confidence Interval for mu-d:
## 
##           lower.bound         upper.bound          
##           1.302075            Inf                  
## 
## Test of Significance:
## 
## 	H_0:  mu-d = 0 
## 	H_a:  mu-d &gt; 0 
## 
## 	Test Statistic:		t = 5.041 
## 	Degrees of Freedom:	  68 
## 	P-value:		P = 1.826e-06
</code></pre>

<h3 id="the-difference-is-in-the-data-frame">The Difference is in the Data Frame</h3>

<p>Sometimes the difference of the two relevant numerical variables is included in the data frame as another variable:  such is the case for <code>m111survey</code>, where the difference is recorded as the variable <strong>diff.ideal.act.</strong></p>

<p>If you would like to use this difference, then Work just as if you were studying one population mean $\mu$.</p>

<h4 id="confidence-interval-only-5">Confidence Interval Only</h4>

<p>Thus, for a 95%-confidence interval for $\mu_d$ we could also have done:</p>

<pre><code>ttestGC(~diff.ideal.act.,data=m111survey)

## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##         variable  mean    sd  n
##  diff.ideal.act. 1.946 3.206 69
## 
## 
## Inferential Results:
## 
## Estimate of mu:	 1.946 
## SE(x.bar):	 0.3859 
## 
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           1.175528            2.715776
</code></pre>

<h4 id="interval-and-test-5">Interval and Test</h4>

<p>For a test of</p>

<blockquote>
  <p>$H_0:  \mu_d = 0$</p>
</blockquote>

<blockquote>
  <p>$H_a: \mu_d &gt; 0$</p>
</blockquote>

<p>we could have done:</p>

<pre><code>ttestGC(~diff.ideal.act.,data=m111survey,
        mu=0,alternative="greater")

## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##         variable  mean    sd  n
##  diff.ideal.act. 1.946 3.206 69
## 
## 
## Inferential Results:
## 
## Estimate of mu:	 1.946 
## SE(x.bar):	 0.3859 
## 
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           1.302075            Inf                  
## 
## Test of Significance:
## 
## 	H_0:  mu = 0 
## 	H_a:  mu &gt; 0 
## 
## 	Test Statistic:		t = 5.041 
## 	Degrees of Freedom:	  68 
## 	P-value:		P = 1.826e-06
</code></pre>

<p>Note that in its statement of hypotheses, R identifies the parameter of interest as $\mu$ rather than as $\mu_d$.  It had no way of knowing that <strong>diff.ideal.act.</strong> recorded the difference of a pair of measurements.</p>
</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/26/pnormGCtutorial/">pnormGC() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-26T16:00:00-05:00" pubdate data-updated="true">Feb 26<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/02/26/pnormGCtutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/26/pnormGCtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#finding-px--x">Finding P(X &lt; x)</a></li>
  <li><a href="#find-px--x">Find P(X &gt; x)</a></li>
  <li><a href="#finding-pa--x--b">Finding P(a &lt; X &lt; b)</a></li>
  <li><a href="#outside-probabilities">“Outside” Probabilities</a></li>
  <li><a href="#non-strict-inequalities">Non-Strict Inequalities</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p><code>pnormGC()</code> provides a direct way to compute probabilities for normal random variables, along with graphs for the probabilities, if you want them.  The function comes from the <code>tigerstats</code> package, so make sure that <code>tigerstats</code> is loaded:</p>

<pre><code>require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need to install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<h2 id="finding-px--x">Finding P(X &lt; x)</h2>

<p>Suppose that you have a normal random variable $X$ with mean $\mu=70$ and standard deviation $\sigma=3$, and you would like to find the chance that $X$ will turn out to be less than 66.  In other words, you are looking for:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 66). %]]></script>

<p>Then run this command:</p>

<pre><code>pnormGC(bound=66,region="below",mean=70,sd=3)

## [1] 0.09121
</code></pre>

<p>Note carefully what the arguments mean, here:</p>

<ul>
  <li><code>bound=66</code> tells <code>pnormGC()</code> where to stop</li>
  <li><code>region="below"</code> takes care of the “less than” part of the requested probability</li>
  <li><code>mean=70</code> specifies the mean $\mu$ of $X$</li>
  <li><code>sd=3</code> specifies the standard deviation $\sigma$ of $X$</li>
</ul>

<p>If you would like to see a graph of the probability distribution of $X$ along with a shaded area that represents the requested probability, then you can set the argument <code>graph</code> to <code>TRUE</code>:</p>

<pre><code>pnormGC(bound=66,region="below",
        mean=70,sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/normtutless66.png" alt="plot of chunk normtutless66" /> </p>

<pre><code>## [1] 0.09121
</code></pre>

<p>You should ask for a graph until you are confident of being able to use <code>pnormGC()</code> to get exactly the probability that you want.</p>

<h2 id="find-px--x">Find P(X &gt; x)</h2>

<p>For the same random variable $X \sim norm(70,3)$, suppose we want the probability that $X$ is greater than 69, i.e.:</p>

<script type="math/tex; mode=display">P(X > 69).</script>

<p>Ask for:</p>

<pre><code>pnormGC(bound=69,region="above",
        mean=70,sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/normtutgreater69.png" alt="plot of chunk normtutgreater69" /> </p>

<pre><code>## [1] 0.6306
</code></pre>

<h2 id="finding-pa--x--b">Finding P(a &lt; X &lt; b)</h2>

<p>For the same random variable $X \sim norm(70,3)$, suppose we want the probability that $X$ is between 68 and 72, i.e.:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(68 < X < 72). %]]></script>

<p>Ask for:</p>

<pre><code>pnormGC(bound=c(68,72),region="between",
        mean=70,sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/normtutbetween.png" alt="plot of chunk normtutbetween" /> </p>

<pre><code>## [1] 0.495
</code></pre>

<p>Observe that since there are two numbers—68 and 72—that are boundaries, we have to specify both of them for <code>pnormGC()</code> in the form of a list <code>c(68,72)</code>.</p>

<h2 id="outside-probabilities">“Outside” Probabilities</h2>

<p>For the same random variable $X \sim norm(70,3)$, suppose we want the probability that either $X$ is less than 66 OR that $X$ is more than 73.  Then we are looking for:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 66 \textbf{ or } X > 73). %]]></script>

<p>We can find this with the command:</p>

<pre><code>pnormGC(bound=c(66,73),region="outside",
         mean=70,sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/mormtutout.png" alt="plot of chunk mormtutout" /> </p>

<pre><code>## [1] 0.2499
</code></pre>

<p>Again observe that there are two numbers—66 and 73—that make the boundaries, so supply both of them to the <code>bound</code> argument as a list:  <code>c(66,72)</code>.</p>

<h2 id="non-strict-inequalities">Non-Strict Inequalities</h2>

<p>Suppose that for the same random variable $X \sim norm(70,3)$, you want the probability that $X$ will turn out to be <em>no more than</em> 66, i.e., you want:</p>

<script type="math/tex; mode=display">P(X \leq 66).</script>

<p>You get this with exactly the same function call that gives you $P(X &lt; 66)$, namely:</p>

<pre><code>pnormGC(bound=66,region="below",
        mean=70,sd=3)
</code></pre>

<p>Remember why?  Normal random variables are <em>continuous</em> random variables, and for any continuous random variable the chance that it is <em>exactly</em> equal to any particular value is zero.  For example, the probability that $X$ is exactly equal to 66 is given by:</p>

<pre><code>pnormGC(bound=c(66,66),region="between",
        mean=70,sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/normtutequal.png" alt="plot of chunk normtutequal" /> </p>

<pre><code>## [1] 0
</code></pre>

<p>The probability of getting exactly 66 is given by the area of the line segment under the curve over 66.  But the area of a line segment—if you think of it as a “rectangle”” with zero width—is zero!</p>

<p>When you ask for</p>

<script type="math/tex; mode=display">P(X \leq 66)</script>

<p>as opposed to</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 66), %]]></script>

<p>you are adding on just the chance of $X$ being exactly 66.  Since this extra chance is zero, you get the same probability as you did with the strict inequality.</p>

</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/26/pbinomGCtutorial/">pbinomGC() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-26T15:00:00-05:00" pubdate data-updated="true">Feb 26<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/02/26/pbinomGCtutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/26/pbinomGCtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#finding-px--x">Finding P(X &lt;= x)</a></li>
  <li><a href="#find-px--x">Find P(X &gt;= x)</a></li>
  <li><a href="#strict-inequalities--finding-px--x">Strict Inequalities:  Finding P(X &lt; x)</a></li>
  <li><a href="#strict-inequalities--finding-px--x-1">Strict Inequalities:  Finding P(X &gt; x)</a></li>
  <li><a href="#finding-pa--x--b">Finding P(a &lt;= X &lt;= b)</a></li>
  <li><a href="#finding-px--x-1">Finding P(X = x)</a></li>
  <li><a href="#outside-probabilities">“Outside” Probabilities</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p><code>pbinomGC()</code> provides a direct way to compute probabilities for binomial random variables, along with graphs for the probabilities, if you want them.  The function comes from the <code>tigerstats</code> package, so make sure that <code>tigerstats</code> is loaded:</p>

<pre><code>require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<h2 id="finding-px--x">Finding P(X &lt;= x)</h2>

<p>Suppose that you have a binomial random variable with $n=20$ trials, and chance of success $p=0.3$ on each trial, and you would like to find the chance of getting 8 or fewer successes in your 20 trials.  In other words (letting $X$ stand for the binomial random variable), you are looking for:</p>

<script type="math/tex; mode=display">P(X \leq 8).</script>

<p>Then run this command:</p>

<pre><code>pbinomGC(bound=8,region="below",size=20,prob=0.3)

## [1] 0.8867
</code></pre>

<p>Note carefully what the arguments mean, here:</p>

<ul>
  <li><code>bound=8</code> tells where to stop</li>
  <li><code>region="below"</code> takes care of the “less than” part of the requested probability</li>
  <li><code>size=20</code> tells <code>pbinomGC()</code> the number of trials for $X$</li>
  <li><code>prob=0.3</code> tells <code>pbinomGC()</code> the chance of success on each trial</li>
</ul>

<p>If you would like to see a graph of the probability distribution of $X$ along with a shaded area that represents the requested probability, then you can set the argument <code>graph</code> to <code>TRUE</code>:</p>

<pre><code>pbinomGC(bound=8,region="below",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutleq8.png" alt="plot of chunk binomtutleq8" /> </p>

<pre><code>## [1] 0.8867
</code></pre>

<h2 id="find-px--x">Find P(X &gt;= x)</h2>

<p>For the same random variable $X \sim binom(20,0.3)$, suppose we want the probability of at least 10 successes, i.e.:</p>

<script type="math/tex; mode=display">P(X \geq 10).</script>

<p>When we want to go “above” a given number, <code>pbinomGC()</code> will <em>not</em> include that number in its computation of probabilities, so asking for</p>

<pre><code>pbinomGC(bound=10,region="above",
         size=20,prob=0.3)
</code></pre>

<p>would give us the chance of $X$ being at least 11, which is not what we want.</p>

<p>However, since $X$ can only take on whole number values, $X \geq 10$ means exactly the same thing as $X &gt; 9$, what we really should ask for is:</p>

<pre><code>pbinomGC(bound=9,region="above",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutgeq10.png" alt="plot of chunk binomtutgeq10" /> </p>

<pre><code>## [1] 0.04796
</code></pre>

<p>The shaded area starts at 10, as desired.</p>

<p>It’s a good idea to keep asking for a graph along with your output, so you can check that R is giving you exactly the probability that you need.</p>

<h2 id="strict-inequalities--finding-px--x">Strict Inequalities:  Finding P(X &lt; x)</h2>

<p>For this case we also have to be careful.</p>

<p>For the same random variable $X \sim binom(20,0.3)$, suppose we want the probability of less than 6 successes, i.e.:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 6). %]]></script>

<p>Since $X$ is a discrete random variable with whole number values, $X &lt; 6$ means exactly the same thing thing as $X \leq 5$.  <code>pbinomGC()</code> includes the bound in the probability that it computes, so we have stop at 5, rather than at 6.  We use the command:</p>

<pre><code>pbinomGC(bound=5,region="below",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutless6.png" alt="plot of chunk binomtutless6" /> </p>

<pre><code>## [1] 0.4164
</code></pre>

<h2 id="strict-inequalities--finding-px--x-1">Strict Inequalities:  Finding P(X &gt; x)</h2>

<p>For the same random variable $X \sim binom(20,0.3)$, suppose we want the probability that the number of successes will be more than 7.  Then we are looking for:</p>

<script type="math/tex; mode=display">P(X > 7).</script>

<p>This is easy again.  Since <code>pbinomGC()</code> does not include the bound when <code>region</code> is “above”, we only need to ask for:</p>

<pre><code>pbinomGC(bound=7,region="above",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutgreater7.png" alt="plot of chunk binomtutgreater7" /> </p>

<pre><code>## [1] 0.2277
</code></pre>

<h2 id="finding-pa--x--b">Finding P(a &lt;= X &lt;= b)</h2>

<p>For the same random variable $X \sim binom(20,0.3)$, suppose we want the probability that the number of successes will be at least 6 but no more than 10.  Then we are looking for:</p>

<script type="math/tex; mode=display">P(6 \leq X \leq 10).</script>

<p>We can find this with the command:</p>

<pre><code>pbinomGC(bound=c(6,10),region="between",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutbetwee.png" alt="plot of chunk binomtutbetwee" /> </p>

<pre><code>## [1] 0.5665
</code></pre>

<p>Notice that there are no two numbers—6 and 10—that make the boundaries, so we must supply both of them to the <code>bound</code> argument as a list:  <code>c(6,10)</code>.  Also note that when <code>region="between"</code>, <code>pbinomGC()</code> includes <em>both</em> of the bounds in its computation of probabilities.</p>

<h2 id="finding-px--x-1">Finding P(X = x)</h2>

<p>To find the chance of $X$ being <em>exactly</em> a particular value, you can employ a little trick.</p>

<p>For example, for the same random variable $X \sim binom(20,0.3)$, suppose we want the chance of exactly 6 successes.  This is very same thing as</p>

<script type="math/tex; mode=display">P(6 \leq X \leq 6),</script>

<p>so you can ask for:</p>

<pre><code>pbinomGC(bound=c(6,6),region="between",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutequal.png" alt="plot of chunk binomtutequal" /> </p>

<pre><code>## [1] 0.1916
</code></pre>

<h2 id="outside-probabilities">“Outside” Probabilities</h2>

<p>This case does not occur very often.</p>

<p>For the same random variable $X \sim binom(20,0.3)$, suppose we want the probability that you either get less than 7 successes OR you get more than 9 successes.  Then we are looking for:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 7 \textbf{ or } X > 9). %]]></script>

<p>You can find this with the command:</p>

<pre><code>pbinomGC(bound=c(7,9),region="outside",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutout.png" alt="plot of chunk binomtutout" /> </p>

<pre><code>## [1] 0.656
</code></pre>

<p>Notice that there are two numbers—7 and 9—that make the boundaries, so we must supply both of them to the <code>bound</code> argument as a list:  <code>c(6,10)</code>.  Notice also that when <code>region</code> is set to “outside”, <code>pbinomGC()</code> excludes both bounds.</p>
</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/21/barchartGCtutorial/">barchartGC() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-21T16:00:00-05:00" pubdate data-updated="true">Feb 21<span>st</span>, 2014</time>
        
           | <a href="/blog/2014/02/21/barchartGCtutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/21/barchartGCtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#one-factor-variable">One Factor Variable</a></li>
  <li><a href="#two-factor-variables">Two Factor Variables</a></li>
  <li><a href="#warning">Warning</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p><code>barchartGC()</code> provides quick-and-easy bar charts for the graphical exploration of factor variables.  The function comes from the <code>tigerstats</code> package and we will use some data from the <code>tigerstats</code> as well, so make sure that <code>tigerstats</code> is loaded:</p>

<pre><code>require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<p>In this tutorial we will work with the <code>m111survey</code> data frame from <code>tigerstats</code> package.  If you are not yet familiar with this data, then run:</p>

<pre><code>data(m111survey)
View(m111survey)
help(m111survey)
</code></pre>

<p>Remember that you can also learn about the types of each variable in the data frame with the <code>str()</code> function:</p>

<pre><code>str(m111survey)

## 'data.frame':	71 obs. of  12 variables:
##  $ height         : num  76 74 64 62 72 70.8 70 79 59 67 ...
##  $ ideal_ht       : num  78 76 NA 65 72 NA 72 76 61 67 ...
##  $ sleep          : num  9.5 7 9 7 8 10 4 6 7 7 ...
##  $ fastest        : int  119 110 85 100 95 100 85 160 90 90 ...
##  $ weight_feel    : Factor w/ 3 levels "1_underweight",..: 1 2 2 1 1 3 2 2 2 3 ...
##  $ love_first     : Factor w/ 2 levels "no","yes": 1 1 1 1 1 1 1 1 1 1 ...
##  $ extra_life     : Factor w/ 2 levels "no","yes": 2 2 1 1 2 1 2 2 2 1 ...
##  $ seat           : Factor w/ 3 levels "1_front","2_middle",..: 1 2 2 1 3 1 1 3 3 2 ...
##  $ GPA            : num  3.56 2.5 3.8 3.5 3.2 3.1 3.68 2.7 2.8 NA ...
##  $ enough_Sleep   : Factor w/ 2 levels "no","yes": 1 1 1 1 1 2 1 2 1 2 ...
##  $ sex            : Factor w/ 2 levels "female","male": 2 2 1 1 2 2 2 2 1 1 ...
##  $ diff.ideal.act.: num  2 2 NA 3 0 NA 2 -3 2 0 ...
</code></pre>

<h2 id="one-factor-variable">One Factor Variable</h2>

<p>To look see a bar chart for the tallies of the factor variable <strong>seat</strong>:</p>

<pre><code>barchartGC(~seat,data=m111survey,type="frequency",
           main="Barchart of Seating Preference")
</code></pre>

<p><img src="/images/figure/barchartseatfreq.png" alt="plot of chunk barchartseatfreq" /> </p>

<p>In order to get the actual distribution of <strong>seat</strong>, you want percents rather than counts:</p>

<pre><code>barchartGC(~seat,data=m111survey,type="percent",
           main="Barchart of Seating Preference")
</code></pre>

<p><img src="/images/figure/barchartseatperc.png" alt="plot of chunk barchartseatperc" /> </p>

<p>If you have a table of the counts for a variable, then you can enter it directly.  For example, suppose you have already made:</p>

<pre><code>Seat &lt;- xtabs(~seat,data=m111survey)
Seat

## seat
##  1_front 2_middle   3_back 
##       27       32       12
</code></pre>

<p>Then you can just enter the table:</p>

<pre><code>barchartGC(Seat,type="percent",
           main="Barchart of Seating Preference")
</code></pre>

<p><img src="/images/figure/barchartseattab.png" alt="plot of chunk barchartseattab" /> </p>

<h2 id="two-factor-variables">Two Factor Variables</h2>

<p>You can also use <code>barchartGC()</code> to study the relationship between two factor variables.  For example, if you want to see whether males and females differ in their seating preferences, then you might try formula-data input as follows:</p>

<pre><code>barchartGC(~sex+seat,data=m111survey,
           type="percent",
           main="Sex and Seating Preference\nat Georgetown")
</code></pre>

<p><img src="/images/figure/barchartsexseat.png" alt="plot of chunk barchartsexseat" /> </p>

<p>Again, if you happen to have already made a two-way table, then you can just enter it:</p>

<pre><code>SexSeat &lt;- xtabs(~sex+seat,data=m111survey)
SexSeat

##         seat
## sex      1_front 2_middle 3_back
##   female      19       16      5
##   male         8       16      7
</code></pre>

<p>Here is the bar chart from the two-way table:</p>

<pre><code>barchartGC(SexSeat,type="percent",
           main="Sex and Seating Preference\nat Georgetown")
</code></pre>

<p><img src="/images/figure/barchartsexseattab.png" alt="plot of chunk barchartsexseattab" /> </p>

<h2 id="warning">Warning</h2>

<p>Bar charts are for factor variables, not for numerical variables.  Look what happens when you ask for a bar chart of <strong>fastest</strong>:</p>

<pre><code>barchartGC(~fastest,data=m111survey,
           main="Fastest Speed Ever Driven")
</code></pre>

<p><img src="/images/figure/barchartfastest.png" alt="plot of chunk barchartfastest" /> </p>

<p>R tries to accommodate your request, but it ends up making something that resembles a very amateurish histogram.  R draws a separate bar for each speed that appears in the data, making for a very “busy” graph.  Worse yet, consecutive speeds are equally spaced from each other, even though the differences between consecutive speeds vary.  For example, the spacing between the 90 ans 91 mph bars is the same as the spacing between the 160 and 190 mph bars.  This is very misleading!</p>
</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/21/favstatstutorial/">Tutorial on Mosaic&#8217;s Favstats()</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-21T15:00:00-05:00" pubdate data-updated="true">Feb 21<span>st</span>, 2014</time>
        
           | <a href="/blog/2014/02/21/favstatstutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/21/favstatstutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#studying-one-numerical-variable">Studying One Numerical Variable</a></li>
  <li><a href="#studying-the-relationship-between-a-numerical-variable-and-a-factor-variable">Studying the Relationship Between a Numerical Variable and a Factor Variable</a></li>
  <li><a href="#limiting-the-output">Limiting the Output</a></li>
  <li><a href="#warning">Warning</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p><code>favstats()</code> comes from the <code>mosaic</code> package and we will use some data from the <code>tigerstats</code> package, so make sure that both are loaded:</p>

<pre><code>require(mosaic)
require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo = "homerhanumat/tigerstats")
</code></pre>

<p>In this tutorial we will work with the <code>m111survey</code> data frame from <code>tigerstats</code> package.  If you are not yet familiar with this data, then run:</p>

<pre><code>data(m111survey)
View(m111survey)
help(m111survey)
</code></pre>

<p>Remember that you can also learn about the types of each variable in the data frame with the <code>str()</code> function:</p>

<pre><code>str(m111survey)

## 'data.frame':	71 obs. of  12 variables:
##  $ height         : num  76 74 64 62 72 70.8 70 79 59 67 ...
##  $ ideal_ht       : num  78 76 NA 65 72 NA 72 76 61 67 ...
##  $ sleep          : num  9.5 7 9 7 8 10 4 6 7 7 ...
##  $ fastest        : int  119 110 85 100 95 100 85 160 90 90 ...
##  $ weight_feel    : Factor w/ 3 levels "1_underweight",..: 1 2 2 1 1 3 2 2 2 3 ...
##  $ love_first     : Factor w/ 2 levels "no","yes": 1 1 1 1 1 1 1 1 1 1 ...
##  $ extra_life     : Factor w/ 2 levels "no","yes": 2 2 1 1 2 1 2 2 2 1 ...
##  $ seat           : Factor w/ 3 levels "1_front","2_middle",..: 1 2 2 1 3 1 1 3 3 2 ...
##  $ GPA            : num  3.56 2.5 3.8 3.5 3.2 3.1 3.68 2.7 2.8 NA ...
##  $ enough_Sleep   : Factor w/ 2 levels "no","yes": 1 1 1 1 1 2 1 2 1 2 ...
##  $ sex            : Factor w/ 2 levels "female","male": 2 2 1 1 2 2 2 2 1 1 ...
##  $ diff.ideal.act.: num  2 2 NA 3 0 NA 2 -3 2 0 ...
</code></pre>

<h2 id="studying-one-numerical-variable">Studying One Numerical Variable</h2>

<p>“favstats” is short for “favorite statistics”:  it will give you the some of the most popular summary statistics for numerical variables.</p>

<p>Suppose, for example, that you want to know how fast people in the <code>m111survey</code> sample tend to drive, when they drive their fastest. The you want to study the numerical variable <strong>fastest</strong>:  the fastest speed each person claims to have ever driven, measured in miles per hour.  Just try <code>favstats()</code> with the usual formula-data input:</p>

<pre><code>favstats(~fastest, data = m111survey)

##  min   Q1 median    Q3 max  mean    sd  n missing
##   60 90.5    102 119.5 190 105.9 20.88 71       0
</code></pre>

<p>Remember what each of the statistics tells you:</p>

<ul>
  <li>The minimum fastest speed drive by anyone in the survery was 60 mph.</li>
  <li>The maximum fastest speed was 190 mph.</li>
  <li>About 25% of the survey participants drove less than 90.5 mph (the First Quartile)</li>
  <li>About 75% percent of the survey participants drove less than 119.5 mph (the Third Quartile)</li>
  <li>About 50% of the participants drove less than 102 mph (the median)</li>
  <li>The mean speed for this sample of students was about 105.9 mph …</li>
  <li>… give or take about 20.9 mph or so (the standard deviation).</li>
</ul>

<p>We also see that</p>

<ul>
  <li>71 people answered the question about fastest speed;</li>
  <li>Nobody did not answer (missing = 0).</li>
</ul>

<h2 id="studying-the-relationship-between-a-numerical-variable-and-a-factor-variable">Studying the Relationship Between a Numerical Variable and a Factor Variable</h2>

<p>Studying the relationship between a numerical variable and factor variable involves what is popularly known as “breaking the data into groups” based on the values of the factor variable.  More formally, we obtain the conditional distributions of the numerical variable given the various possible values of the factor variable, and look for difference between these distributions.  If we see large differences. then we know that the factor variable “makes a difference” in the likely values of the numerical variable, i.e., the two variable are related.</p>

<p>For example we might want to know if the fastest speed one drives might be related to one’s sex.  The relevant variables in <code>m111survey</code> are then the numerical <strong>fastest</strong> and the factor variable <strong>sex</strong>.</p>

<p>In formula-data input for <code>favstats()</code> the formula always follows the format:</p>

<script type="math/tex; mode=display">numerical \sim factor.</script>

<p>So we run the following command:</p>

<pre><code>favstats(fastest ~ sex, data = m111survey)

##        min Q1 median    Q3 max  mean    sd  n missing
## female  60 90     95 110.0 145 100.0 17.61 40       0
## male    85 99    110 122.5 190 113.5 22.57 31       0
</code></pre>

<p>The first row of the output gives a summary of the conditional distribution of <strong>fastest</strong>, given that <strong>sex</strong> is female.</p>

<p>The second row summarizes the conditional distribution of <strong>fastest</strong>, given that <strong>sex</strong> is male.</p>

<p>The two conditional distribution are not the same.  For example, we see that on average females drove about 100 mph, whereas the guys drove about 113.4 mph.  The guys appear to drive faster than the gals:  for this sample of students, fastest speed drive does indeed appear to be related to sex.</p>

<h2 id="limiting-the-output">Limiting the Output</h2>

<p>Sometimes you want just a few of the numbers from <code>favstats()</code>.  If you would like to display only those numbers you can do so using brackets “[” and “]”, along with a list of the names of the columns you want to see.  For example, to display only the means and the standard deviations for <strong>fastest</strong> broken down by <strong>sex</strong>, ask for:</p>

<pre><code>favstats(fastest ~ sex, data = m111survey)[c("mean", "sd")]

##         mean    sd
## female 100.0 17.61
## male   113.5 22.57
</code></pre>

<p>The brackets are R’s way of locating particular parts of an object.  If you want to display more than one column, make sure to combine their names (in quotes) in a list with the <code>c()</code> function, as shown above.</p>

<h2 id="warning">Warning</h2>

<p><code>favstats()</code> specializes in numerical variables:  it won’t help you to study a factor variable by itself.  Look what happens when you try to use it to study the factor variable <strong>sex</strong>:</p>

<pre><code>favstats(~sex, data = m111survey)

## Error: non-numeric argument to binary operator
</code></pre>

</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/15/lmGCtutorial/">lmGC() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-15T15:00:00-05:00" pubdate data-updated="true">Feb 15<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/02/15/lmGCtutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/15/lmGCtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#formula-data-input">Formula-Data Input</a></li>
  <li><a href="#prediction">Prediction</a></li>
  <li><a href="#plotting">Plotting</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p>The <code>lmGC()</code> is a starter-tool for simple linear regression, when you are studying the relationship between two numerical variables, one of which you consider to be an explanatory or predictor variable and the other of which you think of as the response.  It’s only a starter-tool:  by the end of the course, or in later statistics courses, you will move on to R’s function <code>lm()</code>, which allows you to work with more than one explanatory variable and which provides additional useful information in its output.  Also, in <code>lm()</code> the explanatory variable(s) can even be factors!</p>

<p>The function (and some of the data) that we will use comes from the <code>tigerstats</code> package, so make sure that it is loaded:</p>

<pre><code>require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo = "homerhanumat/tigerstats")
</code></pre>

<p>In this tutorial we will work with a couple of data sets:  <code>mtcars</code> from the <code>data</code> package that comes with the basic R installation, and <code>fuel</code> from the <code>tigerstats</code> package, so make sure you become familiar with them.  The following commands may be helpful in this regard:</p>

<pre><code>data(mtcars)
View(mtcars)
help(mtcars)
</code></pre>

<p>For <code>fuel</code>:</p>

<pre><code>data(fuel)
View(fuel)
help(fuel)
</code></pre>

<h2 id="formula-data-input">Formula-Data Input</h2>

<p>Like many R functions, <code>lmGC()</code> accepts formula-data input.  The general command looks like:</p>

<pre><code>lmGC(response ~ explanatory, data = DataFrame)
</code></pre>

<p>If you are interested in studying the relationship between the fuel efficiency of a car (<strong>mpg</strong> in the <code>mtcars</code> data frame, measured in miles per gallon) and its weight (<strong>wt</strong> in <code>mtcars</code>, measure din thousands of pounds), then you  can run:</p>

<pre><code>lmGC(mpg ~ wt, data = mtcars)

## 
## 			Simple Linear Regression
## 
## Correlation coefficient r =  -0.8677 
## 
## Equation of Regression Line:
## 
## 	 mpg = 37.29 + -5.345 * wt 
## 
## Residual Standard Error:	s   = 3.046 
## R^2 (unadjusted):		R^2 = 0.7528
</code></pre>

<p>The output to the console is rather minimal.  You get:</p>

<ul>
  <li>the correlation coefficient $r$.  We need to look at a scatter plot to be really sure about it (for plots, see below), but at this point the value $r = -0.87$ indicates a fairly strong negative linear relationship between fuel efficiency and weight.</li>
  <li>the equation of the regression line.  From the slope of -5.34, we see that for every thousand pound increase in the weight of a car, we predict a 5.34 mpg decrease in the fuel efficiency.</li>
  <li>the residual standard error $s$.  As a rough rule of thumb, we figure that when we use the regression equation to predict the fuel efficiency of a car from its weight, that prediction is liable to be off by about $s$ miles per gallon, or so.</li>
  <li>the unadjusted $R^2$.  We see here that about 75% of the variation in the fuel efficiency of the cars in the data set is accounted for by the variation in their weights.  since $R^2$ is fairly high, it seems that weight is a fairly decent predictor of fuel efficiency.</li>
</ul>

<h2 id="prediction">Prediction</h2>

<p>When the value of the explanatory variable for an individual is known and you wish to predict the value of the response variable for that individual, you can use the <code>predict()</code> function.  Its arguments are the linear model that is created by <code>lmGC()</code>, and the value <code>x</code> of the explanatory variable.</p>

<p>If you think that you might want to use <code>predict()</code>, you may first want to store the model in a variable, for example:</p>

<pre><code>WeightEff &lt;- lmGC(mpg ~ wt, data = mtcars)
</code></pre>

<p>Then if you want to predict the fuel efficiency of a car that weights 3000 pounds, run this command:</p>

<pre><code>predict(WeightEff, x = 3)

## [1] 21.25
</code></pre>

<p>We predict that a 3000 pound car (from the time of the Motor Trend study that produced this data) would have a fuel efficiency of 21.25 mpg, give or take about 3.046 mpg or so.  (Note how we used $s$ as a rough give-or-take figure.)</p>

<h2 id="plotting">Plotting</h2>

<p>But we are getting ahead of ourselves!  In order to use linear models at all, we need to make sure that our data really do show a linear relationship.  The single best way to check this is to look at a scatterplot, so <code>lmGC()</code> comes equipped with a option to produce one:  just set the argument <code>graph</code> to <code>TRUE</code>, as follows:</p>

<pre><code>lmGC(mpg ~ wt, data = mtcars, graph = TRUE)

## 
## 			Simple Linear Regression
## 
## Correlation coefficient r =  -0.8677 
## 
## Equation of Regression Line:
## 
## 	 mpg = 37.29 + -5.345 * wt 
## 
## Residual Standard Error:	s   = 3.046 
## R^2 (unadjusted):		R^2 = 0.7528
</code></pre>

<p><img src="/images/figure/mtcarsscatter.png" alt="Speed and fuel efficiency in the Motor Trends study" /> </p>

<p>The scatterplot includes the regression line. Indeed, the cloud of point seems to follow a line fairly well.  The relationship may be thought of as linear, so using <code>lmGC()</code> for tasks like prediction does make sense, for this data.</p>

<p>You can also perform some simple diagnostics, by setting the argument <code>diag</code> to <code>TRUE</code>:</p>

<pre><code>lmGC(mpg ~ wt, data = mtcars, diag = TRUE)

## 
## 			Simple Linear Regression
## 
## Correlation coefficient r =  -0.8677 
## 
## Equation of Regression Line:
## 
## 	 mpg = 37.29 + -5.345 * wt 
## 
## Residual Standard Error:	s   = 3.046 
## R^2 (unadjusted):		R^2 = 0.7528
</code></pre>

<p><img src="/images/figure/mtcarsdiag.png" alt="Diagnostic plots for the Motor Trends study" /> </p>

<p>You get two graphs:</p>

<ul>
  <li>a density plot of the residuals.  If the distribution of the residuals is roughly bell-shaped, then you can actually employ a &#8220;regression’’ version of the 68-95 Rule:  when you make a prediction using the regression line, there is a about a 68% chance that your predcition will be wtthin one $s$ of the actual $y$-value, and about a 95% chance that ti will be within $2s$ of the actual $y$-value.  <em>Neat!</em></li>
  <li>A plot of the residuals vs, the <code>fitted</code> $y$-values (the $y$-coordinates of the points on the original scatterplot).  If the points exhibit a linear relationship with about the same amount of scatter all the way along the regression line, then this plot should look like a random cloud of points.  In this case, it confirms that our linear model is appropriate to the data.</li>
</ul>

<p>On the other hand, consider <code>fuel</code> data frame, which shows the results of a study where a British Ford Escort was driven at various speed along a standard course, and the fuel efficiency (in kilometers traveled per liter of fuel consumed) was recorded at each speed.  Let’s try a linear model with <strong>speed</strong> as explanatory and <strong>efficiency</strong> as the response, with some diagnostic plots attached:</p>

<pre><code>lmGC(efficiency ~ speed, data = fuel, diag = TRUE)

## 
## 			Simple Linear Regression
## 
## Correlation coefficient r =  -0.1716 
## 
## Equation of Regression Line:
## 
## 	 efficiency = 11.06 + -0.0147 * speed 
## 
## Residual Standard Error:	s   = 3.905 
## R^2 (unadjusted):		R^2 = 0.0295
</code></pre>

<p><img src="/images/figure/fordescortsdiag.png" alt="Diagnostic Plots for British Ford Escort Study" /> </p>

<p>The residuals have a roughly-bell-shaped distribution, but the residual plot is clearly patterned.  Something is amiss!  Let’s look at a scatterplot of the data:</p>

<pre><code>xyplot(efficiency~speed,data=fuel,
       xlab="speed (kilometers/hour",
       ylab="fuel effiency (liters/100km",
       pch=19,col="blue",type=c("p","r"),
       main="Speed and Fuel Efficiency\nfor a British Ford Escort")
</code></pre>

<p><img src="/images/figure/fordescortscatter.png" alt="Speed and Fuel Efficiency for a British Ford Escort" /> </p>

<p>The relationship is strongly curvilinear:  it makes no sense to use the regression line (shown in the plot above) to study the relationship between these two variables!</p>
</div>
  
  


    </article>
  
  <div class="pagination">
    
      <a class="prev" href="/blog/page/2/">&larr; Older</a>
    
    <a href="/blog/archives">Blog Archives</a>
    
  </div>
</div>
<aside class="sidebar">
  
    <section>
  <h1>Recent Posts</h1>
  <ul id="recent_posts">
    
      <li class="post">
        <a href="/blog/2014/02/28/xyplottutorial/">Tutorial on Lattice&#8217;s Xyplot()</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/02/28/bwplottutorial/">Tutorial on Lattice&#8217;s Bwplot()</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/02/28/proptestGCtutorial/">proptestGC() Tutorial</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/02/28/binomtestGCtutorial/">binomtestGC() Tutorial</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/02/27/ttestGCtutorial/">ttestGC() Tutorial</a>
      </li>
    
  </ul>
</section>

<section>
  <h1>GitHub Repos</h1>
  <ul id="gh_repos">
    <li class="loading">Status updating&#8230;</li>
  </ul>
  
  <a href="https://github.com/homerhanumat">@homerhanumat</a> on GitHub
  
  <script type="text/javascript">
    $(document).ready(function(){
        if (!window.jXHR){
            var jxhr = document.createElement('script');
            jxhr.type = 'text/javascript';
            jxhr.src = '/javascripts/libs/jXHR.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(jxhr, s);
        }

        github.showRepos({
            user: 'homerhanumat',
            count: 2,
            skip_forks: true,
            target: '#gh_repos'
        });
    });
  </script>
  <script src="/javascripts/github.js" type="text/javascript"> </script>
</section>



<section class="googleplus">
  <h1>
    <a href="https://plus.google.com/101037539642604924807?rel=author">
      <img src="http://www.google.com/images/icons/ui/gprofile_button-32.png" width="32" height="32">
      Google+
    </a>
  </h1>
</section>


<section>
  <h1>Categories</h1>
  <ul id="categories">
    <li class='category'><a href='/blog/categories/r/'>R (1)</a></li>
<li class='category'><a href='/blog/categories/student-focused-tutorials/'>Student-Focused Tutorials (11)</a></li>
<li class='category'><a href='/blog/categories/tech-note/'>Tech Note (1)</a></li>

  </ul>
</section>
<section>
  <h1>Useful Links</h1>
  <ul id="links">
      <li class="post"><a href="http://www.r-bloggers.com" target="_blank">R-Bloggers</a></li>
      <li class="post"><a href="http://mosaic-web.org/" target="_blank">Project Mosaic</a></li>
      <li class="post"><a href="http://rainandrhino.org", target="_blank">My Elementary Course</a></li> 
  </ul>
</section>

  
</aside>

    </div>
  </div>
  <footer role="contentinfo"><p float>
  2014 - Homer White -
  <span class="credit">Powered by <a href="http://octopress.org">Octopress</a>
</p>
<p>      
  <span> <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /></span><span style="color:black">This work is licensed under a </span><a style="color:black" rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/deed.en_US">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
  </span>
</p>

</footer>
  

<script type="text/javascript">
      var disqus_shortname = 'homerhanumatgithubio';
      
        
        var disqus_script = 'count.js';
      
    (function () {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/' + disqus_script;
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    }());
</script>



<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id; js.async = true;
  js.src = "//connect.facebook.net/en_US/all.js#appId=212934732101925&xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>









</body>
</html>
