
<!DOCTYPE html>
<!--[if IEMobile 7 ]><html class="no-js iem7"><![endif]-->
<!--[if lt IE 9]><html class="no-js lte-ie8"><![endif]-->
<!--[if (gt IE 8)|(gt IEMobile 7)|!(IEMobile)|!(IE)]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <title>A Statistics Blog</title>
  <meta name="author" content="Homer White">

  
  <meta name="description" content="Introduction Installation Establishing a “Common Source” Folder Automated Assignment Collection/Return Student Usernames Encrypting Your Password &hellip;">
  

  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  
  <link rel="canonical" href="http://statistics.rainandrhino.org/blog/page/2">
  <link href="/favicon.png" rel="icon">
  <link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">
  <link href="/atom.xml" rel="alternate" title="A Statistics Blog" type="application/atom+xml">
  <script src="/javascripts/modernizr-2.0.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script>!window.jQuery && document.write(unescape('%3Cscript src="./javascripts/libs/jquery.min.js"%3E%3C/script%3E'))</script>
  <script src="/javascripts/octopress.js" type="text/javascript"></script>
  <!--Fonts from Google"s Web font directory at http://google.com/webfonts -->
<link href="http://fonts.googleapis.com/css?family=PT+Serif:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
<!-- MathJax -->
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true
    }
  });
</script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
      }
    });
</script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Queue(function() {
        var all = MathJax.Hub.getAllJax(), i;
        for(i=0; i < all.length; i += 1) {
            all[i].SourceElement().parentNode.className += ' has-jax';
        }
    });
</script>

<script type="text/javascript"
   src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>


  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-47254229-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>


</head>

<body   >
  <header role="banner"><hgroup>
  <h1><a href="/">A Statistics Blog</a></h1>
  <img src="/favicon.png" style="float:  right; align:  right; width: 20%;">
  
    <h2>R for Statistics Education, and information for the courses I teach.</h2>
  
 
</hgroup>

</header>
  <nav role="navigation"><ul class="subscription" data-subscription="rss">
  <li><a href="/atom.xml" rel="subscribe-rss" title="subscribe via RSS">RSS</a></li>
  
</ul>
  
<form action="http://google.com/search" method="get">
  <fieldset role="search">
    <input type="hidden" name="q" value="site:statistics.rainandrhino.org" />
    <input class="search" type="text" name="q" results="0" placeholder="Search"/>
  </fieldset>
</form>
  
<ul class="main-navigation">
  <li><a href="/">Blog</a></li>
  <li><a href="/blog/archives">Archives</a></li>
  <li><a href="/about/index.html">About</a></li>
</ul>

</nav>
  <div id="main">
    <div id="content">
      <div class="blog-index">
  
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/05/02/perl-scripts-r-studio/">Course Management With the RStudio Server</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-05-02T21:00:00-04:00" pubdate data-updated="true">May 2<span>nd</span>, 2014</time>
        
           | <a href="/blog/2014/05/02/perl-scripts-r-studio/#disqus_thread"
             data-disqus-identifier="http://statistics.rainandrhino.org/blog/2014/05/02/perl-scripts-r-studio/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#introduction">Introduction</a></li>
  <li><a href="#installation">Installation</a></li>
  <li><a href="#establishing-a-common-source-folder">Establishing a “Common Source” Folder</a></li>
  <li><a href="#automated-assignment-collectionreturn">Automated Assignment Collection/Return</a>    <ul>
      <li><a href="#student-usernames">Student Usernames</a></li>
      <li><a href="#encrypting-your-password">Encrypting Your Password</a></li>
      <li><a href="#create-subdirectories">Create Subdirectories</a></li>
      <li><a href="#collect-assignments">Collect Assignments</a></li>
      <li><a href="#return-assignments">Return Assignments</a></li>
    </ul>
  </li>
  <li><a href="#bumps-on-the-road">Bumps on the Road</a></li>
  <li><a href="#props-to-the-sysadmin">Props to the Sysadmin</a></li>
</ul>

<h2 id="introduction">Introduction</h2>

<p>At my institution we teach both elementary and upper-level undergraduate statistics using R, in the environment of the <a href="https://www.rstudio.com/ide/download/">RStudio Linux server</a> installed and configured on our campus network.  Although students are made aware of the existence of the desktop version of RStudio and eventually are encouraged to install it on their personal machines, the default course environment is that of the server.</p>

<p>One reason for this choice is that the server allows us—instructors working in consultation with our sysadmin—to standardize the R environment (R version, installed packages, etc.) for all class members, so that if we add a feature or fix a problem we have some reasonable confidence that it will work for everyone.</p>

<p>Another reason—which constitutes the theme of this post—is that the server environment facilitates course management, especially in technical respects specific to a statistics course, where standard online content management systems such as Moodle or Blackboard may fall short.  The aim of this post is to record, for colleagues at our institution and for folks at other institutions who are considering making the switch to R, the principal ways in which in we have tweaked the server for course-management purposes.  R and RStudio are wonderful free software, but like all free software, they come with a certain “cost of ownership”, and those costs can be considerable if (like me) you begin with little in the way of programming/hacking skills.  I hope that the following information will reduce the ownership costs for others who choose to teach with R in a similar vein.</p>

<h2 id="installation">Installation</h2>

<p>I assume that you have persuaded your sysadmin to install and configure some version of the <a href="https://www.rstudio.com/ide/download/">RStudio Linux server</a>.  My sysadmin chose to set up the Cent OS version, and configured it so that all members of the campus community can access it by means of their username and password.</p>

<p>If your personal machine runs Linux—either the Ubuntu or Cent OS distribution—it’s a good idea to brush up on (or acquire) some very basic command-line skills and to install the server on your own machine as well, so you can replicate some of the strategies described below.  Just a little bit of knowledge of the innards—file permissions, etc.—pays off handsomely in being able to work with your sysadmin to diagnose and resolve quickly any problems that arise.  I myself run Ubuntu, but have not found significant differences between how the server works for me and how it works on campus.</p>

<h2 id="establishing-a-common-source-folder">Establishing a “Common Source” Folder</h2>

<p>Ask your sysadmin to grant superuser privileges t oyou and other course instructors.  Then one of you should create a folder in your Home directory on the server that will serve as a common source for course material.  The sysadmin can create a symbolic link to the folder and can set permissions so that all users may read files in the folder but only you and fellow instructors can write to it.  This folder serves as the repository for assignments, solutions, syllabi, etc.</p>

<p>If you are not the owner of the folder, you can get to it using the ellipses button in the upper right-hand corner of the Files pane.  Simply enter the path-name as specified by your sysadmin.  For one of our courses it is simply: <code>/mat111</code>.</p>

<p>From there you can navigate the directory structure in the Files pane, in the usual way.  To reset the Files pane view back to your Home directory, push the Ellipses button again and enter: <code>~</code>.</p>

<p>All of the foregoing will make sense to you once your have studied Unix-like directory structures.</p>

<h2 id="automated-assignment-collectionreturn">Automated Assignment Collection/Return</h2>

<h3 id="student-usernames">Student Usernames</h3>

<p>Once our elementary  students have acquired some proficiency with R, we introduce them to R Markdown and require them to turn in certain homework  and project assignments as R Markdown documents.  We write comments into a copy of the assignment and return it to the student.  One of the best arguments for teaching in the server environment is that this collection and return process can be automated.  Here’s how we do it these days.</p>

<p>First of all, each instructor should create a text file consisting of the network usernames of student in his or her course (or section thereof), one username per line, and name it something like <code>students.txt</code>.</p>

<p>Save the file in your Home directory on the server.</p>

<h3 id="encrypting-your-password">Encrypting Your Password</h3>

<p>You are going to create some sub-directories in Home directories of your students, so for this you will need to act as a superuser.  This action will in turn require you to provide your password to the computer.  For security reasons, you don’t want to send out the password every time you perform a superuser action, so you need to encrypt your password and provide a key in its place.  For this purpose our sysadmin has written the following Perl script:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><figcaption><span></span></figcaption><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
<span class="line-number">10</span>
<span class="line-number">11</span>
<span class="line-number">12</span>
<span class="line-number">13</span>
<span class="line-number">14</span>
<span class="line-number">15</span>
<span class="line-number">16</span>
<span class="line-number">17</span>
<span class="line-number">18</span>
<span class="line-number">19</span>
<span class="line-number">20</span>
<span class="line-number">21</span>
<span class="line-number">22</span>
<span class="line-number">23</span>
<span class="line-number">24</span>
<span class="line-number">25</span>
<span class="line-number">26</span>
<span class="line-number">27</span>
<span class="line-number">28</span>
<span class="line-number">29</span>
<span class="line-number">30</span>
<span class="line-number">31</span>
<span class="line-number">32</span>
<span class="line-number">33</span>
<span class="line-number">34</span>
<span class="line-number">35</span>
<span class="line-number">36</span>
<span class="line-number">37</span>
<span class="line-number">38</span>
<span class="line-number">39</span>
<span class="line-number">40</span>
<span class="line-number">41</span>
<span class="line-number">42</span>
<span class="line-number">43</span>
</pre></td><td class="code"><pre><code class="perl"><span class="line"><span class="c1">#!/usr/bin/perl -w</span>
</span><span class="line">
</span><span class="line"><span class="k">use</span> <span class="n">strict</span><span class="p">;</span>
</span><span class="line"><span class="k">use</span> <span class="nn">Crypt::</span><span class="n">RC4</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$clearText</span><span class="p">,</span><span class="nv">$passwordFile</span><span class="p">,</span><span class="nv">$key</span><span class="p">);</span>
</span><span class="line">
</span><span class="line"><span class="k">foreach</span> <span class="k">my</span> <span class="nv">$item</span><span class="p">(</span><span class="nv">@ARGV</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">        <span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--password=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$clearText</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">11</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">11</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">        <span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--file=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$passwordFile</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">7</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">7</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">        <span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--key=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$key</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">6</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">6</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">if</span> <span class="p">(</span><span class="o">!</span><span class="nv">$passwordFile</span> <span class="o">||</span> <span class="o">!</span><span class="nv">$clearText</span> <span class="o">||</span> <span class="o">!</span><span class="nv">$key</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line"><span class="k">print</span> <span class="s">&quot;\n USAGE: perl createpasswordfile.pl --password=&lt;domain password&gt; --key=&lt;password file key&gt; --file=&lt;secure password file&gt;\n\n&quot;</span><span class="p">;</span>
</span><span class="line"><span class="nb">exit</span><span class="p">;</span>
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$encryptedPassword</span><span class="p">)</span> <span class="o">=</span> <span class="n">RC4</span><span class="p">(</span><span class="nv">$key</span><span class="p">,</span><span class="nv">$clearText</span><span class="p">);</span>
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$OUTPUTFILE</span><span class="p">);</span>
</span><span class="line"><span class="nb">open</span> <span class="p">(</span><span class="nv">$OUTPUTFILE</span><span class="p">,</span> <span class="s">&quot;&gt;$passwordFile&quot;</span><span class="p">)</span> <span class="ow">or</span> <span class="nb">die</span> <span class="s">&quot;Could not open $passwordFile\n&quot;</span><span class="p">;</span>
</span><span class="line"><span class="k">print</span> <span class="nv">$OUTPUTFILE</span> <span class="s">&quot;$encryptedPassword&quot;</span><span class="p">;</span>
</span><span class="line"><span class="nb">close</span> <span class="p">(</span><span class="nv">$OUTPUTFILE</span><span class="p">);</span>
</span><span class="line">
</span><span class="line"><span class="nb">system</span><span class="p">(</span><span class="s">&quot;chmod 400 $passwordFile&quot;</span><span class="p">);</span>
</span><span class="line">
</span><span class="line"><span class="k">print</span> <span class="s">&quot;\n\nPassword file $passwordFile written.\n&quot;</span><span class="p">;</span>
</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>The above script, and others to follow, are house in <code>/scripts</code>.  You will use it to create an encrypted version of your password that is stored in a new file in your Home directory.  To run the script, issue the following (suitably modified) command in R:</p>

<pre><code>system("perl /scripts/createpasswordfile.pl --password=&lt;YourPassword&gt; --key=&lt;YourChosenKey&gt; --file=&lt;/path/to/YourFavFileName.txt&gt;")
</code></pre>

<p>After you run the script, clear your R History:  you don’t want to leave your password hanging out in the open.</p>

<h3 id="create-subdirectories">Create Subdirectories</h3>

<p>Here is the Perl script that we currently use to create <code>submit</code> and <code>returned</code> directories in the Home directory of each student in the class.  Obviously your sysadmin will modify it to suit the file structure of your server.</p>

<div class="bogus-wrapper"><notextile><figure class="code"><figcaption><span></span></figcaption><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
<span class="line-number">10</span>
<span class="line-number">11</span>
<span class="line-number">12</span>
<span class="line-number">13</span>
<span class="line-number">14</span>
<span class="line-number">15</span>
<span class="line-number">16</span>
<span class="line-number">17</span>
<span class="line-number">18</span>
<span class="line-number">19</span>
<span class="line-number">20</span>
<span class="line-number">21</span>
<span class="line-number">22</span>
<span class="line-number">23</span>
<span class="line-number">24</span>
<span class="line-number">25</span>
<span class="line-number">26</span>
<span class="line-number">27</span>
<span class="line-number">28</span>
<span class="line-number">29</span>
<span class="line-number">30</span>
<span class="line-number">31</span>
<span class="line-number">32</span>
<span class="line-number">33</span>
<span class="line-number">34</span>
<span class="line-number">35</span>
<span class="line-number">36</span>
<span class="line-number">37</span>
<span class="line-number">38</span>
<span class="line-number">39</span>
<span class="line-number">40</span>
<span class="line-number">41</span>
<span class="line-number">42</span>
<span class="line-number">43</span>
<span class="line-number">44</span>
<span class="line-number">45</span>
<span class="line-number">46</span>
<span class="line-number">47</span>
<span class="line-number">48</span>
<span class="line-number">49</span>
<span class="line-number">50</span>
<span class="line-number">51</span>
<span class="line-number">52</span>
<span class="line-number">53</span>
<span class="line-number">54</span>
<span class="line-number">55</span>
<span class="line-number">56</span>
<span class="line-number">57</span>
<span class="line-number">58</span>
<span class="line-number">59</span>
<span class="line-number">60</span>
<span class="line-number">61</span>
<span class="line-number">62</span>
<span class="line-number">63</span>
<span class="line-number">64</span>
<span class="line-number">65</span>
<span class="line-number">66</span>
<span class="line-number">67</span>
<span class="line-number">68</span>
<span class="line-number">69</span>
<span class="line-number">70</span>
<span class="line-number">71</span>
<span class="line-number">72</span>
<span class="line-number">73</span>
<span class="line-number">74</span>
<span class="line-number">75</span>
<span class="line-number">76</span>
<span class="line-number">77</span>
<span class="line-number">78</span>
<span class="line-number">79</span>
<span class="line-number">80</span>
<span class="line-number">81</span>
<span class="line-number">82</span>
<span class="line-number">83</span>
<span class="line-number">84</span>
<span class="line-number">85</span>
<span class="line-number">86</span>
<span class="line-number">87</span>
<span class="line-number">88</span>
<span class="line-number">89</span>
<span class="line-number">90</span>
<span class="line-number">91</span>
<span class="line-number">92</span>
<span class="line-number">93</span>
<span class="line-number">94</span>
<span class="line-number">95</span>
<span class="line-number">96</span>
<span class="line-number">97</span>
<span class="line-number">98</span>
<span class="line-number">99</span>
<span class="line-number">100</span>
<span class="line-number">101</span>
<span class="line-number">102</span>
<span class="line-number">103</span>
<span class="line-number">104</span>
<span class="line-number">105</span>
<span class="line-number">106</span>
<span class="line-number">107</span>
<span class="line-number">108</span>
<span class="line-number">109</span>
<span class="line-number">110</span>
<span class="line-number">111</span>
<span class="line-number">112</span>
<span class="line-number">113</span>
<span class="line-number">114</span>
<span class="line-number">115</span>
<span class="line-number">116</span>
<span class="line-number">117</span>
<span class="line-number">118</span>
<span class="line-number">119</span>
<span class="line-number">120</span>
<span class="line-number">121</span>
<span class="line-number">122</span>
<span class="line-number">123</span>
<span class="line-number">124</span>
<span class="line-number">125</span>
<span class="line-number">126</span>
<span class="line-number">127</span>
<span class="line-number">128</span>
<span class="line-number">129</span>
<span class="line-number">130</span>
<span class="line-number">131</span>
<span class="line-number">132</span>
<span class="line-number">133</span>
<span class="line-number">134</span>
<span class="line-number">135</span>
<span class="line-number">136</span>
<span class="line-number">137</span>
<span class="line-number">138</span>
<span class="line-number">139</span>
<span class="line-number">140</span>
<span class="line-number">141</span>
<span class="line-number">142</span>
<span class="line-number">143</span>
<span class="line-number">144</span>
<span class="line-number">145</span>
<span class="line-number">146</span>
<span class="line-number">147</span>
<span class="line-number">148</span>
<span class="line-number">149</span>
<span class="line-number">150</span>
<span class="line-number">151</span>
<span class="line-number">152</span>
<span class="line-number">153</span>
<span class="line-number">154</span>
</pre></td><td class="code"><pre><code class="perl"><span class="line"><span class="c1">#!/usr/bin/perl -w</span>
</span><span class="line">
</span><span class="line"><span class="k">use</span> <span class="n">strict</span><span class="p">;</span>
</span><span class="line"><span class="k">use</span> <span class="n">constant</span> <span class="n">TRUE</span> <span class="o">=&gt;</span> <span class="o">-</span><span class="mi">1</span><span class="p">;</span>
</span><span class="line"><span class="k">use</span> <span class="n">constant</span> <span class="n">FALSE</span> <span class="o">=&gt;</span> <span class="mi">0</span><span class="p">;</span>
</span><span class="line"><span class="c1">#************************ PARAMETERS *********************************************************</span>
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$sourceRoot</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;/home/FAST&quot;</span><span class="p">;</span>
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$group</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;admins&quot;</span><span class="p">;</span>
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$userDirective</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;FAST\\\\&quot;</span><span class="p">;</span>
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$permissions</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;770&quot;</span><span class="p">;</span>
</span><span class="line"><span class="c1">#*********************************************************************************************</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="c1">#collect commandline arguments</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">sub </span><span class="nf">showUsage</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line"><span class="k">print</span> <span class="s">&quot;\nUSAGE: perl createdirectories.pl --studentfile=&lt;filename&gt; [--source=&lt;source path&gt; (Alternate source path) --email=&lt;email address&gt; (Email for submission report) --group=&lt;group name&gt; (Security Group) --permissions=&lt;nnn&gt; (Default Directory Permissions)]\n\n&quot;</span><span class="p">;</span>
</span><span class="line"><span class="nb">exit</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$studentfile</span><span class="p">,</span><span class="nv">$sendEmail</span><span class="p">,</span><span class="nv">$summaryLine</span><span class="p">,</span><span class="nv">$recipientAddress</span><span class="p">);</span>
</span><span class="line"><span class="nv">$sendEmail</span> <span class="o">=</span> <span class="n">FALSE</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">foreach</span> <span class="k">my</span> <span class="nv">$item</span><span class="p">(</span><span class="nv">@ARGV</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">        <span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--studentfile=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$studentfile</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">14</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">14</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">        <span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--source=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                 <span class="nv">$sourceRoot</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">9</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">9</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">        <span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--email=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$sendEmail</span> <span class="o">=</span> <span class="n">TRUE</span><span class="p">;</span>
</span><span class="line">                <span class="nv">$recipientAddress</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">8</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">8</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">  <span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--group=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$group</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">8</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">8</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line"> 	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--permissions=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$permissions</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">14</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">14</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">if</span> <span class="p">(</span><span class="o">!</span><span class="nv">$studentfile</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line"><span class="o">&amp;</span><span class="n">showUsage</span><span class="p">;</span>
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="nv">$summaryLine</span> <span class="o">=</span> <span class="s">&quot;\nDirectory Permission Updates:\n--------------------------\n\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">);</span>
</span><span class="line"><span class="nb">open</span> <span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">,</span> <span class="s">&quot;&lt;$studentfile&quot;</span><span class="p">)</span> <span class="ow">or</span> <span class="nb">die</span> <span class="s">&quot;Could not open $studentfile\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">while</span> <span class="p">(</span><span class="sr">&lt;$INPUTFILE&gt;</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">	<span class="nv">$_</span> <span class="o">=~</span> <span class="sr">s/\cM\cJ|\cM|\cJ/\n/g</span><span class="p">;</span>  <span class="c1"># Re-format Windows files</span>
</span><span class="line">	<span class="k">my</span><span class="p">(</span><span class="nv">$inputLine</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$_</span><span class="p">;</span>
</span><span class="line">        <span class="nb">chomp</span> <span class="p">(</span><span class="nv">$inputLine</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">	<span class="k">unless</span> <span class="p">(</span><span class="nv">$inputLine</span> <span class="o">=~</span><span class="sr"> /^\s*$/</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">		<span class="k">my</span><span class="p">(</span><span class="nv">$submitPath</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$sourceRoot</span> <span class="o">.</span> <span class="s">&quot;/&quot;</span> <span class="o">.</span> <span class="nv">$inputLine</span> <span class="o">.</span> <span class="s">&quot;/submit&quot;</span><span class="p">;</span>
</span><span class="line">		<span class="k">my</span><span class="p">(</span><span class="nv">$returnPath</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$sourceRoot</span> <span class="o">.</span> <span class="s">&quot;/&quot;</span> <span class="o">.</span> <span class="nv">$inputLine</span> <span class="o">.</span> <span class="s">&quot;/returned&quot;</span><span class="p">;</span>
</span><span class="line">		<span class="k">my</span><span class="p">(</span><span class="nv">$mynotesPath</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$sourceRoot</span> <span class="o">.</span> <span class="s">&quot;/&quot;</span> <span class="o">.</span> <span class="nv">$inputLine</span> <span class="o">.</span><span class="s">&quot;/mynotes&quot;</span><span class="p">;</span>
</span><span class="line">	
</span><span class="line">		<span class="k">unless</span> <span class="p">(</span><span class="o">-</span><span class="n">e</span> <span class="nv">$submitPath</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">			<span class="nb">system</span> <span class="p">(</span><span class="s">&quot;mkdir $submitPath&quot;</span><span class="p">);</span> <span class="c1">#or die &quot;\nCould not create directory $submitPath.\n&quot;; </span>
</span><span class="line">			<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nCreated submit path $submitPath for user $inputLine.\n&quot;</span><span class="p">;</span>
</span><span class="line">		<span class="p">}</span> <span class="k">else</span> <span class="p">{</span>
</span><span class="line">			<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nSubmit path $submitPath for user $inputLine already exists.\n&quot;</span><span class="p">;</span>
</span><span class="line">		<span class="p">}</span>
</span><span class="line">	
</span><span class="line">		<span class="k">unless</span> <span class="p">(</span><span class="o">-</span><span class="n">e</span> <span class="nv">$returnPath</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">			<span class="nb">system</span> <span class="p">(</span><span class="s">&quot;mkdir $returnPath&quot;</span><span class="p">);</span>  <span class="c1">#or die &quot;\nCould not create directory $returnPath.\n&quot;; </span>
</span><span class="line">			<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nCreated return path $returnPath for user $inputLine.\n&quot;</span><span class="p">;</span>
</span><span class="line">		<span class="p">}</span> <span class="k">else</span> <span class="p">{</span>
</span><span class="line">			<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nReturn path $returnPath for user $inputLine already exists.\n&quot;</span><span class="p">;</span>
</span><span class="line">		<span class="p">}</span>
</span><span class="line">			
</span><span class="line"> 		<span class="k">unless</span> <span class="p">(</span><span class="o">-</span><span class="n">e</span> <span class="nv">$mynotesPath</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                	<span class="nb">system</span> <span class="p">(</span><span class="s">&quot;mkdir $mynotesPath&quot;</span><span class="p">);</span>  <span class="c1">#or die &quot;\nCould not create directory $returnPath.\n&quot;;</span>
</span><span class="line">                	<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nCreated mynotes path $mynotesPath for user $inputLine.\n&quot;</span><span class="p">;</span>
</span><span class="line">        	<span class="p">}</span> <span class="k">else</span> <span class="p">{</span>
</span><span class="line">                	<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nmynotes path $mynotesPath for user $inputLine already exists.\n&quot;</span><span class="p">;</span>
</span><span class="line">        	<span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">		<span class="k">my</span><span class="p">(</span><span class="nv">$securityToken</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$userDirective</span> <span class="o">.</span> <span class="nv">$inputLine</span> <span class="o">.</span> <span class="s">&quot;:&quot;</span> <span class="o">.</span> <span class="nv">$group</span><span class="p">;</span>
</span><span class="line">	
</span><span class="line">		<span class="nb">system</span><span class="p">(</span><span class="s">&quot;chown $securityToken $submitPath&quot;</span><span class="p">);</span>
</span><span class="line">		<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nChanged ownership of submit path $submitPath to $securityToken.\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">		<span class="nb">system</span><span class="p">(</span><span class="s">&quot;chown $securityToken $returnPath&quot;</span><span class="p">);</span>
</span><span class="line">		<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nChanged ownership of return path $returnPath to $securityToken.\n&quot;</span><span class="p">;</span>
</span><span class="line"> 	
</span><span class="line">		<span class="nb">system</span><span class="p">(</span><span class="s">&quot;chown $securityToken $mynotesPath&quot;</span><span class="p">);</span>
</span><span class="line">        	<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nChanged ownership of mynotes path $mynotesPath to $securityToken.\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">		<span class="nb">system</span><span class="p">(</span><span class="s">&quot;chmod $permissions $submitPath&quot;</span><span class="p">);</span>
</span><span class="line">		<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nChanged permissions of submit path $submitPath to $permissions.\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">		<span class="nb">system</span><span class="p">(</span><span class="s">&quot;chmod $permissions $returnPath&quot;</span><span class="p">);</span>
</span><span class="line"> 		<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nChanged permissions of return path $returnPath to $permissions.\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">		<span class="nb">system</span><span class="p">(</span><span class="s">&quot;chmod $permissions $mynotesPath&quot;</span><span class="p">);</span>
</span><span class="line">        	<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\nChanged permissions of mynotes path $mynotesPath to $permissions.\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">	<span class="p">}</span>
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line"><span class="nb">close</span> <span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">);</span>
</span><span class="line">
</span><span class="line"><span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">print</span> <span class="nv">$summaryLine</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">if</span> <span class="p">(</span><span class="nv">$sendEmail</span> <span class="o">==</span> <span class="n">TRUE</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">        <span class="k">print</span> <span class="s">&quot;\nSending summary email to $recipientAddress.\n&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">my</span> <span class="p">(</span><span class="nv">$emailSubject</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;Subject: RStudio directories updated&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">my</span> <span class="p">(</span><span class="nv">$sendmailObject</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;/usr/sbin/sendmail -F RStudio_Grades\@georgetowncollege.edu -t&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">my</span> <span class="p">(</span><span class="nv">$replyAddress</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;Reply-to: RStudio_Grades\@georgetowncollege.edu&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">my</span> <span class="p">(</span><span class="nv">$recipient</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;To: $recipientAddress&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="nb">open</span> <span class="p">(</span><span class="n">SENDMAIL</span><span class="p">,</span> <span class="s">&quot;|$sendmailObject&quot;</span><span class="p">)</span> <span class="ow">or</span> <span class="nb">die</span> <span class="s">&quot;Cannot open $sendmailObject: $!&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$emailSubject</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$recipient</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$replyAddress</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;Content-type: text/plain\n\n&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$summaryLine</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;.&quot;</span><span class="p">;</span>
</span><span class="line">        <span class="nb">close</span> <span class="p">(</span><span class="n">SENDMAIL</span><span class="p">);</span>
</span><span class="line"><span class="p">}</span>
</span></code></pre></td></tr></table></div></figure></notextile></div>
<p>To run the script, issue the following R command, suitably modified:</p>

<pre><code>system("perl createdirectories.pl --studentfile=&lt;StudentFileName&gt;")
</code></pre>

<p>There are options to receive an email report confirming the creation of the directories, and to set permissions for them as well.  Currently we use the default settings.</p>

<h3 id="collect-assignments">Collect Assignments</h3>

<p>Students save an assignment into their <code>submit</code> directory, named according to some convention that you establish.  Specifics vary, but the name must end with an underscore followed by the student username.  For example:  <code>HW05_jdoe.Rmd</code> is the fifth homework assignment, submitted by the student with username <code>jdoe</code>.</p>

<p>The Perl script for collection of assignments is as follows:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><figcaption><span></span></figcaption><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
<span class="line-number">10</span>
<span class="line-number">11</span>
<span class="line-number">12</span>
<span class="line-number">13</span>
<span class="line-number">14</span>
<span class="line-number">15</span>
<span class="line-number">16</span>
<span class="line-number">17</span>
<span class="line-number">18</span>
<span class="line-number">19</span>
<span class="line-number">20</span>
<span class="line-number">21</span>
<span class="line-number">22</span>
<span class="line-number">23</span>
<span class="line-number">24</span>
<span class="line-number">25</span>
<span class="line-number">26</span>
<span class="line-number">27</span>
<span class="line-number">28</span>
<span class="line-number">29</span>
<span class="line-number">30</span>
<span class="line-number">31</span>
<span class="line-number">32</span>
<span class="line-number">33</span>
<span class="line-number">34</span>
<span class="line-number">35</span>
<span class="line-number">36</span>
<span class="line-number">37</span>
<span class="line-number">38</span>
<span class="line-number">39</span>
<span class="line-number">40</span>
<span class="line-number">41</span>
<span class="line-number">42</span>
<span class="line-number">43</span>
<span class="line-number">44</span>
<span class="line-number">45</span>
<span class="line-number">46</span>
<span class="line-number">47</span>
<span class="line-number">48</span>
<span class="line-number">49</span>
<span class="line-number">50</span>
<span class="line-number">51</span>
<span class="line-number">52</span>
<span class="line-number">53</span>
<span class="line-number">54</span>
<span class="line-number">55</span>
<span class="line-number">56</span>
<span class="line-number">57</span>
<span class="line-number">58</span>
<span class="line-number">59</span>
<span class="line-number">60</span>
<span class="line-number">61</span>
<span class="line-number">62</span>
<span class="line-number">63</span>
<span class="line-number">64</span>
<span class="line-number">65</span>
<span class="line-number">66</span>
<span class="line-number">67</span>
<span class="line-number">68</span>
<span class="line-number">69</span>
<span class="line-number">70</span>
<span class="line-number">71</span>
<span class="line-number">72</span>
<span class="line-number">73</span>
<span class="line-number">74</span>
<span class="line-number">75</span>
<span class="line-number">76</span>
<span class="line-number">77</span>
<span class="line-number">78</span>
<span class="line-number">79</span>
<span class="line-number">80</span>
<span class="line-number">81</span>
<span class="line-number">82</span>
<span class="line-number">83</span>
<span class="line-number">84</span>
<span class="line-number">85</span>
<span class="line-number">86</span>
<span class="line-number">87</span>
<span class="line-number">88</span>
<span class="line-number">89</span>
<span class="line-number">90</span>
<span class="line-number">91</span>
<span class="line-number">92</span>
<span class="line-number">93</span>
<span class="line-number">94</span>
<span class="line-number">95</span>
<span class="line-number">96</span>
<span class="line-number">97</span>
<span class="line-number">98</span>
<span class="line-number">99</span>
<span class="line-number">100</span>
<span class="line-number">101</span>
<span class="line-number">102</span>
<span class="line-number">103</span>
<span class="line-number">104</span>
<span class="line-number">105</span>
<span class="line-number">106</span>
<span class="line-number">107</span>
<span class="line-number">108</span>
<span class="line-number">109</span>
<span class="line-number">110</span>
<span class="line-number">111</span>
<span class="line-number">112</span>
<span class="line-number">113</span>
<span class="line-number">114</span>
<span class="line-number">115</span>
<span class="line-number">116</span>
<span class="line-number">117</span>
<span class="line-number">118</span>
<span class="line-number">119</span>
<span class="line-number">120</span>
<span class="line-number">121</span>
<span class="line-number">122</span>
<span class="line-number">123</span>
<span class="line-number">124</span>
<span class="line-number">125</span>
<span class="line-number">126</span>
<span class="line-number">127</span>
<span class="line-number">128</span>
<span class="line-number">129</span>
<span class="line-number">130</span>
<span class="line-number">131</span>
<span class="line-number">132</span>
<span class="line-number">133</span>
<span class="line-number">134</span>
<span class="line-number">135</span>
<span class="line-number">136</span>
<span class="line-number">137</span>
<span class="line-number">138</span>
<span class="line-number">139</span>
<span class="line-number">140</span>
<span class="line-number">141</span>
<span class="line-number">142</span>
<span class="line-number">143</span>
<span class="line-number">144</span>
<span class="line-number">145</span>
<span class="line-number">146</span>
<span class="line-number">147</span>
<span class="line-number">148</span>
<span class="line-number">149</span>
<span class="line-number">150</span>
<span class="line-number">151</span>
<span class="line-number">152</span>
<span class="line-number">153</span>
</pre></td><td class="code"><pre><code class="perl"><span class="line"><span class="c1">#!/usr/bin/perl -w</span>
</span><span class="line">
</span><span class="line"><span class="k">use</span> <span class="n">strict</span><span class="p">;</span>
</span><span class="line"><span class="k">use</span> <span class="nn">File::</span><span class="n">Find</span><span class="p">;</span>
</span><span class="line"><span class="k">use</span> <span class="n">constant</span> <span class="n">TRUE</span> <span class="o">=&gt;</span> <span class="o">-</span><span class="mi">1</span><span class="p">;</span>
</span><span class="line"><span class="k">use</span> <span class="n">constant</span> <span class="n">FALSE</span> <span class="o">=&gt;</span> <span class="mi">0</span><span class="p">;</span>
</span><span class="line"><span class="c1">#************************ PARAMETERS *********************************************************</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$sourceRoot</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;/home/FAST&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="c1">#*********************************************************************************************</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="c1">#collect commandline arguments</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">sub </span><span class="nf">showUsage</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line"><span class="k">print</span> <span class="s">&quot;\nUSAGE: perl collecthomework.pl --instructor=&lt;name&gt; --assignment=&lt;name&gt; --studentfile=&lt;filename&gt; \n Optional Parameters:\n\n[--source=&lt;source path&gt; (Alternate source path)\n--destination=&lt;destination path&gt; (Alternate destination path)\n --remove (Remove homework files after copying them)\n --email=&lt;email address&gt; (Email for submission report)]\n\n&quot;</span><span class="p">;</span>
</span><span class="line"><span class="nb">exit</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$instructor</span><span class="p">,</span><span class="nv">$assignment</span><span class="p">,</span><span class="nv">$studentfile</span><span class="p">,</span><span class="nv">$destinationRoot</span><span class="p">,</span><span class="nv">$sendEmail</span><span class="p">,</span><span class="nv">$recipientAddress</span><span class="p">);</span>
</span><span class="line">
</span><span class="line"><span class="nv">$sendEmail</span> <span class="o">=</span> <span class="n">FALSE</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">foreach</span> <span class="k">my</span> <span class="nv">$item</span><span class="p">(</span><span class="nv">@ARGV</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">  <span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--instructor=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">		<span class="nv">$instructor</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">13</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">13</span><span class="p">);</span>
</span><span class="line">	<span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"> 	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--assignment=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$assignment</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">13</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">13</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--studentfile=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$studentfile</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">14</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">14</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line"> 	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--source=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">		 <span class="nv">$sourceRoot</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">9</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">9</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--destination=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                 <span class="nv">$destinationRoot</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">14</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">14</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--email=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$sendEmail</span> <span class="o">=</span> <span class="n">TRUE</span><span class="p">;</span>
</span><span class="line">		<span class="nv">$recipientAddress</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">8</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">8</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">if</span> <span class="p">(</span><span class="o">!</span><span class="nv">$instructor</span> <span class="o">||</span> <span class="o">!</span><span class="nv">$assignment</span> <span class="o">||</span> <span class="o">!</span><span class="nv">$studentfile</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line"><span class="o">&amp;</span><span class="n">showUsage</span><span class="p">;</span>
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">if</span> <span class="p">(</span><span class="o">!</span><span class="nv">$destinationRoot</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">	<span class="nv">$destinationRoot</span> <span class="o">=</span> <span class="s">&quot;/home/FAST/&quot;</span> <span class="o">.</span> <span class="nv">$instructor</span> <span class="o">.</span> <span class="s">&quot;/homework&quot;</span><span class="p">;</span>
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$noSubmissionYet</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;\nThe following students have not submitted homework yet:\n------------------------------------------------------------&quot;</span><span class="p">;</span>
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$summaryLine</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;\nHomework assignments retrieved for assignment $assignment:\n-------------------------------------&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">);</span>
</span><span class="line"><span class="nb">open</span> <span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">,</span> <span class="s">&quot;&lt;$studentfile&quot;</span><span class="p">)</span> <span class="ow">or</span> <span class="nb">die</span> <span class="s">&quot;Could not open $studentfile\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">while</span> <span class="p">(</span><span class="sr">&lt;$INPUTFILE&gt;</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line"> 	<span class="nv">$_</span> <span class="o">=~</span> <span class="sr">s/\cM\cJ|\cM|\cJ/\n/g</span><span class="p">;</span>  <span class="c1"># Re-format Windows files</span>
</span><span class="line">        <span class="k">my</span><span class="p">(</span><span class="nv">$inputLine</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$_</span><span class="p">;</span>
</span><span class="line">        <span class="nb">chomp</span> <span class="p">(</span><span class="nv">$inputLine</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">        <span class="k">unless</span> <span class="p">(</span><span class="nv">$inputLine</span> <span class="o">=~</span><span class="sr"> /^\s*$/</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line">        <span class="k">my</span><span class="p">(</span><span class="nv">@searchFolders</span><span class="p">)</span> <span class="o">=</span> <span class="p">(</span><span class="nv">$sourceRoot</span> <span class="o">.</span> <span class="s">&quot;/&quot;</span> <span class="o">.</span> <span class="nv">$inputLine</span> <span class="o">.</span> <span class="s">&quot;/submit&quot;</span><span class="p">);</span>
</span><span class="line">	<span class="k">my</span><span class="p">(</span><span class="nv">@foundProjects</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">        <span class="n">find</span><span class="p">(</span> <span class="k">sub </span><span class="p">{</span> <span class="nb">push</span> <span class="nv">@foundProjects</span><span class="p">,</span> <span class="nv">$</span><span class="nn">File::Find::</span><span class="nv">name</span> <span class="k">if</span> <span class="sr">/$assignment/i</span> <span class="p">},</span> <span class="nv">@searchFolders</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">	
</span><span class="line">        <span class="k">my</span><span class="p">(</span><span class="nv">$projectFile</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">        <span class="k">foreach</span> <span class="nv">$projectFile</span><span class="p">(</span><span class="nv">@foundProjects</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">		<span class="k">print</span> <span class="s">&quot;\nFound $projectFile.&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">                <span class="k">my</span> <span class="p">(</span><span class="nv">$destinationFolder</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$destinationRoot</span> <span class="o">.</span> <span class="s">&quot;/&quot;</span> <span class="o">.</span> <span class="nv">$assignment</span> <span class="o">.</span> <span class="s">&quot;/&quot;</span> <span class="o">.</span> <span class="nv">$inputLine</span><span class="p">;</span>
</span><span class="line">                <span class="k">unless</span> <span class="p">(</span><span class="o">-</span><span class="n">e</span> <span class="nv">$destinationFolder</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                        <span class="nb">system</span> <span class="p">(</span><span class="s">&quot;mkdir -p $destinationFolder&quot;</span><span class="p">);</span>
</span><span class="line">                <span class="p">}</span>
</span><span class="line">
</span><span class="line">                <span class="nv">$destinationFolder</span> <span class="o">=</span> <span class="nv">$destinationFolder</span> <span class="o">.</span> <span class="s">&quot;/&quot;</span><span class="p">;</span>
</span><span class="line">                <span class="nb">system</span> <span class="p">(</span><span class="s">&quot;cp -f $projectFile $destinationFolder&quot;</span><span class="p">);</span>
</span><span class="line">		<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\n $inputLine submitted file: $projectFile&quot;</span><span class="p">;</span>		
</span><span class="line">
</span><span class="line">	<span class="p">}</span>
</span><span class="line">
</span><span class="line">	<span class="k">if</span> <span class="p">(</span><span class="o">!</span><span class="nv">@foundProjects</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">		<span class="nv">$noSubmissionYet</span> <span class="o">=</span> <span class="nv">$noSubmissionYet</span> <span class="o">.</span> <span class="s">&quot;\n$inputLine&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">	<span class="p">}</span>
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line"><span class="nb">close</span> <span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">);</span>
</span><span class="line">
</span><span class="line"><span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\n\n&quot;</span> <span class="o">.</span> <span class="nv">$noSubmissionYet</span> <span class="o">.</span> <span class="s">&quot;\n\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">print</span> <span class="nv">$summaryLine</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">if</span> <span class="p">(</span><span class="nv">$sendEmail</span> <span class="o">==</span> <span class="n">TRUE</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">	<span class="k">print</span> <span class="s">&quot;\nSending summary email to $recipientAddress.\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">my</span> <span class="p">(</span><span class="nv">$emailSubject</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;Subject: RStudio projects submitted for assignment $assignment&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">my</span> <span class="p">(</span><span class="nv">$sendmailObject</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;/usr/sbin/sendmail -F RStudio_Grades\@georgetowncollege.edu -t&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">my</span> <span class="p">(</span><span class="nv">$replyAddress</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;Reply-to: RStudio_Grades\@georgetowncollege.edu&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">my</span> <span class="p">(</span><span class="nv">$recipient</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;To: $recipientAddress&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="nb">open</span> <span class="p">(</span><span class="n">SENDMAIL</span><span class="p">,</span> <span class="s">&quot;|$sendmailObject&quot;</span><span class="p">)</span> <span class="ow">or</span> <span class="nb">die</span> <span class="s">&quot;Cannot open $sendmailObject: $!&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$emailSubject</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$recipient</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$replyAddress</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;Content-type: text/plain\n\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$summaryLine</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;.&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="nb">close</span> <span class="p">(</span><span class="n">SENDMAIL</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span></code></pre></td></tr></table></div></figure></notextile></div>
<p>To run the script issue a command like the following:</p>

<pre><code>system("perl /scripts/collecthomework.pl --instructor=&lt;yourUsername&gt; --assignment=&lt;assignCode&gt; --studentfile=students.txt")
</code></pre>

<p>If you would like to receive an email with a list of all students from whom you got an assignment, run this instead:</p>

<pre><code>system("perl /scripts/collecthomework.pl --instructor=&lt;yourUsername&gt; --assignment=&lt;assignCode&gt; --studentfile=students.txt --email=&lt;yourEmailAddress&gt;")
</code></pre>

<p>You can run the collection script as often as you like:  it will pick up newly-submitted assignments but will not overwrite assignments collected from other students in a previous run.</p>

<h3 id="return-assignments">Return Assignments</h3>

<p>All of the assignments you collect appear in a <code>homework</code> folder in your Home directory, in sub-directories by assignment name and sub-sub-directories by student username.  Navigate to the assignments one by one.  For each assignment, open the R Markdown file and save it with an additional tag in the file name that will mark it out as the graded/commented copy to be returned to the student.  We use <code>_com</code> as our tag, creating files like this:  <code>HW05_jdoe_com.Rmd</code>.</p>

<p>For returning assignments, we have the following Perl script:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><figcaption><span></span></figcaption><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
<span class="line-number">10</span>
<span class="line-number">11</span>
<span class="line-number">12</span>
<span class="line-number">13</span>
<span class="line-number">14</span>
<span class="line-number">15</span>
<span class="line-number">16</span>
<span class="line-number">17</span>
<span class="line-number">18</span>
<span class="line-number">19</span>
<span class="line-number">20</span>
<span class="line-number">21</span>
<span class="line-number">22</span>
<span class="line-number">23</span>
<span class="line-number">24</span>
<span class="line-number">25</span>
<span class="line-number">26</span>
<span class="line-number">27</span>
<span class="line-number">28</span>
<span class="line-number">29</span>
<span class="line-number">30</span>
<span class="line-number">31</span>
<span class="line-number">32</span>
<span class="line-number">33</span>
<span class="line-number">34</span>
<span class="line-number">35</span>
<span class="line-number">36</span>
<span class="line-number">37</span>
<span class="line-number">38</span>
<span class="line-number">39</span>
<span class="line-number">40</span>
<span class="line-number">41</span>
<span class="line-number">42</span>
<span class="line-number">43</span>
<span class="line-number">44</span>
<span class="line-number">45</span>
<span class="line-number">46</span>
<span class="line-number">47</span>
<span class="line-number">48</span>
<span class="line-number">49</span>
<span class="line-number">50</span>
<span class="line-number">51</span>
<span class="line-number">52</span>
<span class="line-number">53</span>
<span class="line-number">54</span>
<span class="line-number">55</span>
<span class="line-number">56</span>
<span class="line-number">57</span>
<span class="line-number">58</span>
<span class="line-number">59</span>
<span class="line-number">60</span>
<span class="line-number">61</span>
<span class="line-number">62</span>
<span class="line-number">63</span>
<span class="line-number">64</span>
<span class="line-number">65</span>
<span class="line-number">66</span>
<span class="line-number">67</span>
<span class="line-number">68</span>
<span class="line-number">69</span>
<span class="line-number">70</span>
<span class="line-number">71</span>
<span class="line-number">72</span>
<span class="line-number">73</span>
<span class="line-number">74</span>
<span class="line-number">75</span>
<span class="line-number">76</span>
<span class="line-number">77</span>
<span class="line-number">78</span>
<span class="line-number">79</span>
<span class="line-number">80</span>
<span class="line-number">81</span>
<span class="line-number">82</span>
<span class="line-number">83</span>
<span class="line-number">84</span>
<span class="line-number">85</span>
<span class="line-number">86</span>
<span class="line-number">87</span>
<span class="line-number">88</span>
<span class="line-number">89</span>
<span class="line-number">90</span>
<span class="line-number">91</span>
<span class="line-number">92</span>
<span class="line-number">93</span>
<span class="line-number">94</span>
<span class="line-number">95</span>
<span class="line-number">96</span>
<span class="line-number">97</span>
<span class="line-number">98</span>
<span class="line-number">99</span>
<span class="line-number">100</span>
<span class="line-number">101</span>
<span class="line-number">102</span>
<span class="line-number">103</span>
<span class="line-number">104</span>
<span class="line-number">105</span>
<span class="line-number">106</span>
<span class="line-number">107</span>
<span class="line-number">108</span>
<span class="line-number">109</span>
<span class="line-number">110</span>
<span class="line-number">111</span>
<span class="line-number">112</span>
<span class="line-number">113</span>
<span class="line-number">114</span>
<span class="line-number">115</span>
<span class="line-number">116</span>
<span class="line-number">117</span>
<span class="line-number">118</span>
<span class="line-number">119</span>
<span class="line-number">120</span>
<span class="line-number">121</span>
<span class="line-number">122</span>
<span class="line-number">123</span>
<span class="line-number">124</span>
<span class="line-number">125</span>
<span class="line-number">126</span>
<span class="line-number">127</span>
<span class="line-number">128</span>
<span class="line-number">129</span>
<span class="line-number">130</span>
<span class="line-number">131</span>
<span class="line-number">132</span>
<span class="line-number">133</span>
<span class="line-number">134</span>
<span class="line-number">135</span>
<span class="line-number">136</span>
<span class="line-number">137</span>
<span class="line-number">138</span>
<span class="line-number">139</span>
<span class="line-number">140</span>
<span class="line-number">141</span>
<span class="line-number">142</span>
<span class="line-number">143</span>
<span class="line-number">144</span>
<span class="line-number">145</span>
<span class="line-number">146</span>
<span class="line-number">147</span>
<span class="line-number">148</span>
<span class="line-number">149</span>
<span class="line-number">150</span>
<span class="line-number">151</span>
<span class="line-number">152</span>
<span class="line-number">153</span>
<span class="line-number">154</span>
<span class="line-number">155</span>
<span class="line-number">156</span>
<span class="line-number">157</span>
<span class="line-number">158</span>
<span class="line-number">159</span>
<span class="line-number">160</span>
<span class="line-number">161</span>
<span class="line-number">162</span>
<span class="line-number">163</span>
<span class="line-number">164</span>
<span class="line-number">165</span>
<span class="line-number">166</span>
<span class="line-number">167</span>
<span class="line-number">168</span>
<span class="line-number">169</span>
<span class="line-number">170</span>
<span class="line-number">171</span>
<span class="line-number">172</span>
<span class="line-number">173</span>
<span class="line-number">174</span>
<span class="line-number">175</span>
<span class="line-number">176</span>
<span class="line-number">177</span>
<span class="line-number">178</span>
<span class="line-number">179</span>
<span class="line-number">180</span>
<span class="line-number">181</span>
<span class="line-number">182</span>
<span class="line-number">183</span>
<span class="line-number">184</span>
<span class="line-number">185</span>
<span class="line-number">186</span>
<span class="line-number">187</span>
<span class="line-number">188</span>
<span class="line-number">189</span>
<span class="line-number">190</span>
<span class="line-number">191</span>
<span class="line-number">192</span>
<span class="line-number">193</span>
<span class="line-number">194</span>
<span class="line-number">195</span>
</pre></td><td class="code"><pre><code class="perl"><span class="line"><span class="c1">#!/usr/bin/perl -w</span>
</span><span class="line">
</span><span class="line"><span class="k">use</span> <span class="n">strict</span><span class="p">;</span>
</span><span class="line"><span class="k">use</span> <span class="nn">File::</span><span class="n">Find</span><span class="p">;</span>
</span><span class="line"><span class="k">use</span> <span class="nn">Crypt::</span><span class="n">RC4</span><span class="p">;</span>
</span><span class="line"><span class="k">use</span> <span class="n">constant</span> <span class="n">TRUE</span> <span class="o">=&gt;</span> <span class="o">-</span><span class="mi">1</span><span class="p">;</span>
</span><span class="line"><span class="k">use</span> <span class="n">constant</span> <span class="n">FALSE</span> <span class="o">=&gt;</span> <span class="mi">0</span><span class="p">;</span>
</span><span class="line"><span class="c1">#************************ PARAMETERS *********************************************************</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$sourceRoot</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;/home/FAST/&quot;</span><span class="p">;</span>
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$group</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;admins&quot;</span><span class="p">;</span>
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$userDirective</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;FAST\\\\&quot;</span><span class="p">;</span>
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$permissions</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;770&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="c1">#*********************************************************************************************</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="c1">#collect commandline arguments</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">sub </span><span class="nf">showUsage</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line"><span class="k">print</span> <span class="s">&quot;\nUSAGE: perl returnhomework.pl --path=&lt;name&gt; --flag=&lt;name&gt; --studentfile=&lt;filename&gt; \n Optional Parameters:\n\n[--email=&lt;email address&gt; (Email for submission report) --key=&lt;password file key&gt; --passwordfile=&lt;password file&gt;]\n\n&quot;</span><span class="p">;</span>
</span><span class="line"><span class="nb">exit</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$path</span><span class="p">,</span><span class="nv">$flag</span><span class="p">,</span><span class="nv">$studentfile</span><span class="p">,</span><span class="nv">$destinationRoot</span><span class="p">,</span><span class="nv">$sendEmail</span><span class="p">,</span><span class="nv">$recipientAddress</span><span class="p">,</span><span class="nv">$key</span><span class="p">,</span><span class="nv">$passwordFile</span><span class="p">,</span><span class="nv">$decryptedPassword</span><span class="p">);</span>
</span><span class="line">
</span><span class="line"><span class="nv">$sendEmail</span> <span class="o">=</span> <span class="n">FALSE</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">foreach</span> <span class="k">my</span> <span class="nv">$item</span><span class="p">(</span><span class="nv">@ARGV</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line">   <span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--flag=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$flag</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">7</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">7</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--studentfile=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$studentfile</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">14</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">14</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line"> 	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--path=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">		 <span class="nv">$path</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">7</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">7</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--destination=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                 <span class="nv">$destinationRoot</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">14</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">14</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--email=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$sendEmail</span> <span class="o">=</span> <span class="n">TRUE</span><span class="p">;</span>
</span><span class="line">		<span class="nv">$recipientAddress</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">8</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">8</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--key=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$key</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">6</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">6</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">	<span class="k">if</span> <span class="p">(</span><span class="nv">$item</span> <span class="o">=~</span> <span class="sr">m/--passwordfile=/i</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                <span class="nv">$passwordFile</span> <span class="o">=</span> <span class="nb">substr</span><span class="p">(</span><span class="nv">$item</span><span class="p">,</span><span class="mi">15</span><span class="p">,</span><span class="nb">length</span><span class="p">(</span><span class="nv">$item</span><span class="p">)</span><span class="o">-</span><span class="mi">15</span><span class="p">);</span>
</span><span class="line">        <span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">if</span> <span class="p">(</span><span class="nv">$passwordFile</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">	<span class="k">my</span><span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">);</span>
</span><span class="line">	<span class="nb">open</span> <span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">,</span> <span class="s">&quot;&lt;$passwordFile&quot;</span><span class="p">)</span> <span class="ow">or</span> <span class="nb">die</span> <span class="s">&quot;Could not open $passwordFile\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">	<span class="k">while</span> <span class="p">(</span><span class="sr">&lt;$INPUTFILE&gt;</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">        	<span class="k">my</span><span class="p">(</span><span class="nv">$inputLine</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$_</span><span class="p">;</span>
</span><span class="line">        	<span class="nb">chomp</span> <span class="p">(</span><span class="nv">$inputLine</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">		<span class="nv">$decryptedPassword</span> <span class="o">=</span> <span class="n">RC4</span><span class="p">(</span><span class="nv">$key</span><span class="p">,</span><span class="nv">$inputLine</span><span class="p">);</span>
</span><span class="line">	<span class="p">}</span>
</span><span class="line">	
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">if</span> <span class="p">(</span><span class="o">!</span><span class="nv">$path</span> <span class="o">||</span> <span class="o">!</span><span class="nv">$flag</span> <span class="o">||</span> <span class="o">!</span><span class="nv">$studentfile</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line"><span class="o">&amp;</span><span class="n">showUsage</span><span class="p">;</span>
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">unless</span> <span class="p">(</span> <span class="nv">$path</span> <span class="o">=~</span> <span class="n">s</span><span class="o">|</span><span class="sr">/\s*$|/</span><span class="o">|</span> <span class="p">)</span>
</span><span class="line"><span class="p">{</span>
</span><span class="line">    <span class="nv">$path</span> <span class="o">=</span> <span class="nv">$path</span> <span class="o">.</span> <span class="s">&quot;/&quot;</span><span class="p">;</span>
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">if</span> <span class="p">(</span><span class="o">!</span><span class="nv">$destinationRoot</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">	<span class="nv">$destinationRoot</span> <span class="o">=</span> <span class="s">&quot;/home/FAST/&quot;</span><span class="p">;</span>
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$summaryLine</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;\nHomework graded in folder $path:\n-------------------------------------&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="k">my</span><span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">);</span>
</span><span class="line"><span class="nb">open</span> <span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">,</span> <span class="s">&quot;&lt;$studentfile&quot;</span><span class="p">)</span> <span class="ow">or</span> <span class="nb">die</span> <span class="s">&quot;Could not open $studentfile\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">while</span> <span class="p">(</span><span class="sr">&lt;$INPUTFILE&gt;</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line"> 	<span class="nv">$_</span> <span class="o">=~</span> <span class="sr">s/\cM\cJ|\cM|\cJ/\n/g</span><span class="p">;</span>  <span class="c1"># Re-format Windows files</span>
</span><span class="line">        <span class="k">my</span><span class="p">(</span><span class="nv">$inputLine</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$_</span><span class="p">;</span>
</span><span class="line">        <span class="nb">chomp</span> <span class="p">(</span><span class="nv">$inputLine</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">        <span class="k">unless</span> <span class="p">(</span><span class="nv">$inputLine</span> <span class="o">=~</span><span class="sr"> /^\s*$/</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">
</span><span class="line">        <span class="k">my</span><span class="p">(</span><span class="nv">@searchFolders</span><span class="p">)</span> <span class="o">=</span> <span class="p">(</span><span class="nv">$path</span> <span class="o">.</span>  <span class="nv">$inputLine</span><span class="p">);</span>
</span><span class="line">	<span class="k">my</span><span class="p">(</span><span class="nv">@foundProjects</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">        <span class="n">find</span><span class="p">(</span> <span class="k">sub </span><span class="p">{</span> <span class="nb">push</span> <span class="nv">@foundProjects</span><span class="p">,</span> <span class="nv">$</span><span class="nn">File::Find::</span><span class="nv">name</span> <span class="k">if</span> <span class="sr">/$flag/i</span> <span class="p">},</span> <span class="nv">@searchFolders</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">	
</span><span class="line">        <span class="k">my</span><span class="p">(</span><span class="nv">$projectFile</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">        <span class="k">foreach</span> <span class="nv">$projectFile</span><span class="p">(</span><span class="nv">@foundProjects</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">
</span><span class="line">		<span class="k">print</span> <span class="s">&quot;\nFound $projectFile.&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line">                <span class="k">my</span> <span class="p">(</span><span class="nv">$destinationFolder</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$destinationRoot</span> <span class="o">.</span> <span class="nv">$inputLine</span> <span class="o">.</span> <span class="s">&quot;/returned&quot;</span><span class="p">;</span>
</span><span class="line">                <span class="k">unless</span> <span class="p">(</span><span class="o">-</span><span class="n">e</span> <span class="nv">$destinationFolder</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                        <span class="nb">system</span> <span class="p">(</span><span class="s">&quot;mkdir -p $destinationFolder&quot;</span><span class="p">);</span>
</span><span class="line">                <span class="p">}</span>
</span><span class="line">
</span><span class="line">                <span class="nv">$destinationFolder</span> <span class="o">=</span> <span class="nv">$destinationFolder</span> <span class="o">.</span> <span class="s">&quot;/&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"> 		<span class="k">my</span><span class="p">(</span><span class="nv">$securityToken</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$userDirective</span> <span class="o">.</span> <span class="nv">$inputLine</span> <span class="o">.</span> <span class="s">&quot;:&quot;</span> <span class="o">.</span> <span class="nv">$group</span><span class="p">;</span>
</span><span class="line">        	
</span><span class="line">                <span class="nb">system</span> <span class="p">(</span><span class="s">&quot;cp -f $projectFile $destinationFolder&quot;</span><span class="p">);</span>
</span><span class="line">		
</span><span class="line">		<span class="k">my</span><span class="p">(</span><span class="nv">$folderWildcard</span><span class="p">)</span> <span class="o">=</span> <span class="nv">$destinationFolder</span> <span class="o">.</span> <span class="s">&quot;*&quot;</span><span class="p">;</span>
</span><span class="line">	
</span><span class="line">
</span><span class="line">		<span class="k">if</span> <span class="p">(</span><span class="nv">$passwordFile</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">                	<span class="nb">system</span><span class="p">(</span><span class="s">&quot;echo $decryptedPassword | sudo chown $securityToken $folderWildcard&quot;</span><span class="p">);</span>
</span><span class="line">                	<span class="nb">system</span> <span class="p">(</span><span class="s">&quot;echo $decryptedPassword | sudo chmod 770 $folderWildcard&quot;</span><span class="p">);</span>
</span><span class="line">		<span class="p">}</span> <span class="k">else</span> <span class="p">{</span>
</span><span class="line">			<span class="nb">system</span><span class="p">(</span><span class="s">&quot;chown $securityToken $folderWildcard&quot;</span><span class="p">);</span>
</span><span class="line">                	<span class="nb">system</span><span class="p">(</span><span class="s">&quot;chmod 770 $folderWildcard&quot;</span><span class="p">);</span>
</span><span class="line">		<span class="p">}</span>
</span><span class="line">
</span><span class="line">		
</span><span class="line">		<span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\n $inputLine returned $projectFile to $destinationFolder\n&quot;</span><span class="p">;</span>		
</span><span class="line">
</span><span class="line">
</span><span class="line">	<span class="p">}</span>
</span><span class="line">
</span><span class="line">
</span><span class="line">	<span class="p">}</span>
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span><span class="line">
</span><span class="line"><span class="nb">close</span> <span class="p">(</span><span class="nv">$INPUTFILE</span><span class="p">);</span>
</span><span class="line">
</span><span class="line"><span class="nv">$summaryLine</span> <span class="o">=</span> <span class="nv">$summaryLine</span> <span class="o">.</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">print</span> <span class="nv">$summaryLine</span><span class="p">;</span>
</span><span class="line">
</span><span class="line"><span class="k">if</span> <span class="p">(</span><span class="nv">$sendEmail</span> <span class="o">==</span> <span class="n">TRUE</span><span class="p">)</span> <span class="p">{</span>
</span><span class="line">	<span class="k">print</span> <span class="s">&quot;\nSending summary email to $recipientAddress.\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">my</span> <span class="p">(</span><span class="nv">$emailSubject</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;Subject: RStudio projects graded and returned.&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">my</span> <span class="p">(</span><span class="nv">$sendmailObject</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;/usr/sbin/sendmail -F RStudio_Grades\@georgetowncollege.edu -t&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">my</span> <span class="p">(</span><span class="nv">$replyAddress</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;Reply-to: RStudio_Grades\@georgetowncollege.edu&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">my</span> <span class="p">(</span><span class="nv">$recipient</span><span class="p">)</span> <span class="o">=</span> <span class="s">&quot;To: $recipientAddress&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="nb">open</span> <span class="p">(</span><span class="n">SENDMAIL</span><span class="p">,</span> <span class="s">&quot;|$sendmailObject&quot;</span><span class="p">)</span> <span class="ow">or</span> <span class="nb">die</span> <span class="s">&quot;Cannot open $sendmailObject: $!&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$emailSubject</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$recipient</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$replyAddress</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;Content-type: text/plain\n\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="nv">$summaryLine</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;\n&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="k">print</span> <span class="n">SENDMAIL</span> <span class="s">&quot;.&quot;</span><span class="p">;</span>
</span><span class="line">	<span class="nb">close</span> <span class="p">(</span><span class="n">SENDMAIL</span><span class="p">);</span>
</span><span class="line">
</span><span class="line">
</span><span class="line"><span class="p">}</span>
</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>To run the script, you need the key for your encrypted password.  Run a command like the following:</p>

<pre><code>system("perl /scripts/returnhomework.pl --path=/path/to/yourUsername/homework/HW05/ --flag=_com --studentfile=/usr/local/sbin/YourUsername-YourCourse.txt --key=YourChosenKey --passwordfile=password_file_YourUsername.txt")
</code></pre>

<p>Note that the sysadmin has established, for each instructor, a file in <code>/usr/local/sbin</code> of student usernames for the instructor’s course.  As students drop your course and you edit your local student file accordingly, the two files may fall out of sync, but the return script will still work correctly for students still enrolled in the course.</p>

<h2 id="bumps-on-the-road">Bumps on the Road</h2>

<p>All in all, the server environment has proven to be quite useful for our courses.  Nevertheless, there are a few complications and potential problems to keep in mind.</p>

<ul>
  <li>Students can read from the Common Source, directory, but cannot write to it.  If a student wishes to perform an “knitting” type of action to a file in the Common Source directory—e.g., knitting an R Markdown to HTML or previewing an R Presentation document—then she must save a copy into her Home directory and perform the knitting operations upon it.  The same often goes for other instructors (default file permissions are still a bit unclear to us).</li>
  <li><a href="https://www.rstudio.com/shiny/">Shiny apps</a> are wonderful.  We put them into the <a href="https://github.com/homerhanumat/tigerstats">ancillary package</a> that we use for our own elementary course, so that R users can run them locally once the package is installed, or run them locally after downloading them from the package’s Git Hub repository.  However, at many institutions the firewalls don’t permit execution of the Shiny scripts.  If this is the case at your own institution and you want your students to work with Shiny apps, then you must either install and configure the Shiny server or deploy the apps yourself on a site hosted by RStudio, e.g., <a href="http://shinyapps.io/">http://shinyapps.io/</a>.  We have experimented with both venues and are pleased with the results.</li>
  <li>A small percentage of users eventually experience mysterious problems—e.g., loss of ability to knit an R markdown document more than once in a single server session—that we have not been able to diagnose and resolve completely.  If the problem becomes sufficiently severe, a student could always use the desktop version, but this in itself creates a course management problem.  Larger institutions than ours may wish to consider paying for the Enterprise version of the RStudio server, and the support that accompanies it.</li>
</ul>

<h2 id="props-to-the-sysadmin">Props to the Sysadmin</h2>

<p>We are grateful for the work of Scott Switzer, who serves as Server System Manager in the Office of Information Technology Services at Georgetown College.  Scott manages the RStudio server and the College’s Shiny server, created the Perl scripts in this post, helped establish other website support for our elementary statistics course, and at an early stage played the role of informal command-line guru to the the author of this post.  If you have the good fortune to work with a such a sysadmin your own institution, make sure that she gets lots of love and special ice cream!</p>

</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/04/28/qnormtutorial/">Qnorm() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-04-28T22:00:00-04:00" pubdate data-updated="true">Apr 28<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/04/28/qnormtutorial/#disqus_thread"
             data-disqus-identifier="http://statistics.rainandrhino.org/blog/2014/04/28/qnormtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#comparison-of-qnorm-with-pnorm">Comparison of <code>qnorm()</code> with <code>pnorm()</code></a></li>
  <li><a href="#a-few-more-examples">A Few More Examples</a>    <ul>
      <li><a href="#making-the-top-ten-percent-an-area-above">Making the Top Ten Percent (An Area Above)</a></li>
      <li><a href="#an-area-between">An Area Between</a></li>
    </ul>
  </li>
</ul>

<h2 id="comparison-of-qnorm-with-pnorm">Comparison of <code>qnorm()</code> with <code>pnorm()</code></h2>

<p>Thew function <code>prnorm()</code> in regular <code>R</code>, as well as the function <code>pnormGC() in the </code>tigerstats` package, compute probabilities from known bounding values.  For example, suppose that $X$ is a normally distributed random variable with mean 70 and standard deviation 3, and that you want to know:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 72). %]]></script>

<p>Then you <em>know</em> the boundary value 72, but you don’t know the probability:  the area under the normal density curve before 72.  Functions like <code>pnormGC()</code> aim to give you that area–that probability:</p>

<pre><code>require(tigerstats)

 

pnormGC(72, region="below", mean=70,
        sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/qnormtut72.png" alt="plot of chunk qnormtut72" /> </p>

<pre><code>## [1] 0.7475
</code></pre>

<p>The function <code>qnorm()</code>, which comes standard with R, aims to do the opposite:  given an area, find the boundary value that determines this area.</p>

<p>For example, suppose you want to find that 85th percentile of a normal distribution whose mean is 70 and whose standard deviation is 3.  Then you ask for:</p>

<pre><code>qnorm(0.85,mean=70,sd=3)

## [1] 73.11
</code></pre>

<p>The value 73.1093 is indeed the 85th percentile, in the sense that 85% of the values in a population that is normally distributed with mean 70 and standard deviation 3 will lie below 73.1093.  In other words, if you were to pick a random member $X$ from such a population, then</p>

<p><script type="math/tex">% <![CDATA[
P(X < 73.1093) = 0.85 %]]></script>.</p>

<p>You can check that this is correct by plugging 73.1093 into <code>pnormGC()</code>:</p>

<pre><code>pnormGC(73.1093,region="below",mean=70,
        sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/qnormtut73.png" alt="plot of chunk qnormtut73" /> </p>

<pre><code>## [1] 0.85
</code></pre>

<p>Sure enough, the area under the curve before 73.1093 is 0.85.</p>

<h2 id="a-few-more-examples">A Few More Examples</h2>

<h3 id="making-the-top-ten-percent-an-area-above">Making the Top Ten Percent (An Area Above)</h3>

<blockquote>
  <p>Suppose that SAT scores are normally distributed, and that the mean SAT score is 1000, and the standard deviation of all SAT scores is 100.  <em>How high must you score so that only 10% of the population scores higher than you?</em></p>
</blockquote>

<p>Here’s the solution.  If 10% score higher than you, then 90% score lower.  So just call <code>qnorm()</code> with 0.90 as the boundary value:</p>

<pre><code>qnorm(0.90,mean=1000,sd=100)

## [1] 1128
</code></pre>

<p>In other words, the 90th percentile of SAT scores is around 1128.</p>

<p><strong>Note</strong>:  <code>qnorm()</code> deals by default with areas <em>below</em> the given boundary value.  If we had asked for:</p>

<pre><code>qnorm(0.10,mean=1000,sd=100)
</code></pre>

<p>then we would have got only the 10th percentile of the SAT scores, not the desired 90th percentile.  If you would like to input 0.10 directly, then you can do so provided that you fiddle with the <code>lower.tail</code> argument:</p>

<pre><code>qnorm(0.10,mean=1000,sd=100,
      lower.tail=FALSE)

## [1] 1128
</code></pre>

<p>But really it seems easier just to do the math:</p>

<p>$1 - 0.10 = 0.90.$</p>

<h3 id="an-area-between">An Area Between</h3>

<blockquote>
  <p>Find a positive number $z$ so that the area under the standard normal curve between $-z$ and $z$ is 0.95.</p>
</blockquote>

<p>Here’s the solution.  If 95% of the area lies between $-z$ and $z$, then 5% of the area must lie outside of this range.  since normal curves are symmetric, half of this amount–2.5%–must lie before $-z$.  Then the area under the curve before $z$ must be:</p>

<script type="math/tex; mode=display">0.025+0.95=0.975.</script>

<p>Hence the number $z$ is actually the 97.5th percentile of the standard normal distribution, and we can find it as follows:</p>

<pre><code>qnorm(0.975,mean=0,sd=1)

## [1] 1.96
</code></pre>

<p>So $z$ is about 1.96.  We can check this result graphically as follows:</p>

<pre><code>pnormGC(c(-1.96,1.96),region="between",mean=0,
        sd=1,graph=TRUE)
</code></pre>

<p><img src="/images/figure/qnormtutbetween.png" alt="plot of chunk qnormtutbetween" /> </p>

<pre><code>## [1] 0.95
</code></pre>

</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/04/13/roctopress/">Roctopress: Configure Your Octopress Blog for R</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-04-13T16:00:00-04:00" pubdate data-updated="true">Apr 13<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/04/13/roctopress/#disqus_thread"
             data-disqus-identifier="http://statistics.rainandrhino.org/blog/2014/04/13/roctopress/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#introduction">Introduction</a></li>
  <li><a href="#directory-house-keeping">Directory House-Keeping</a></li>
  <li><a href="#from-r-markdown-to-markdown">From R Markdown to Markdown</a></li>
  <li><a href="#from-r-markdown-to-html">From R Markdown to HTML</a></li>
  <li><a href="#considerations-of-style">Considerations of Style</a></li>
  <li><a href="#producing-a-post">Producing a Post</a></li>
  <li><a href="#creating-a-topics-feed">Creating a Topics Feed</a></li>
  <li><a href="#archive-old-r-markdowns">Archive Old R Markdowns</a></li>
  <li><a href="#lingering-problems">Lingering Problems</a></li>
</ul>

<h2 id="introduction">Introduction</h2>

<p>This post records how I configured <a href="http://octopress.org/">Octopress</a> for blogging about <a href="http://www.r-project.org/">R</a>, my favorite statistical programming environment.  It is intended for colleagues and students who would like to begin blogging in a similar vein.  I will assume that you have got Octopress up and running, and that you have chosen to have it hosted by <a href="https://pages.github.com/">GitHub Pages</a>.</p>

<p>I claim little in the way of originality:  most of this post consists of tips I picked up from knowledgeable people on the web.</p>

<h2 id="directory-house-keeping">Directory House-Keeping</h2>

<p>Create the following directories in the Octopress directory:</p>

<ul>
  <li><code>Rmd_sources</code> (your posts will start here)</li>
  <li><code>Rmd_sources_old</code> (to archive old posts source files)</li>
  <li><code>source/images/figure</code> (your R graphs will be placed here)</li>
  <li><code>source/images/cache</code> (if you cache the results of an expensive computation, the results go here)</li>
</ul>

<h2 id="from-r-markdown-to-markdown">From R Markdown to Markdown</h2>

<p>We will adopt the approach of <a href="http://jason.bryer.org/posts/2012-12-10/Markdown_Jekyll_R_for_Blogging.html">Jason Breyer</a>.</p>

<p>In your Octopress directory, place the Jason’s R Script (perhaps call it <code>rmarkdown.r</code>):</p>

<pre><code>#' This R script will process all R mardown files (those with in_ext file extention,
#' .rmd by default) in the current working directory. Files with a status of
#' 'processed' will be converted to markdown (with out_ext file extention, '.markdown'
#' by default). It will change the published parameter to 'true' and change the
#' status parameter to 'publish'.
#'
#' @param dir the directory to process R Markdown files.
#' @param images.dir the base directory where images will be generated.
#' @param images.url
#' @param out_ext the file extention to use for processed files.
#' @param in_ext the file extention of input files to process.
#' @param recursive should rmd files in subdirectories be processed.
#' @return nothing.
#' @author Jason Bryer &lt;jason@bryer.org&gt;
convertRMarkdown &lt;- function(dir=getwd(), images.dir=dir, 
                             images.url='/images/',
                             out_ext='.markdown', in_ext='.rmd', recursive=FALSE) {
        require(knitr, quietly=TRUE, warn.conflicts=FALSE)
        files &lt;- list.files(path=dir, pattern=in_ext, ignore.case=TRUE, recursive=recursive)
        for(f in files) {
                message(paste("Processing ", f, sep=''))
                content &lt;- readLines(f)
                frontMatter &lt;- which(substr(content, 1, 3) == '---')
                if(length(frontMatter) &gt;= 2 &amp; 1 %in% frontMatter) {
                        statusLine &lt;- which(substr(content, 1, 7) == 'status:')
                        publishedLine &lt;- which(substr(content, 1, 10) == 'published:')
                        if(statusLine &gt; frontMatter[1] &amp; statusLine &lt; frontMatter[2]) {
                                status &lt;- unlist(strsplit(content[statusLine], ':'))[2]
                                status &lt;- sub('[[:space:]]+$', '', status)
                                status &lt;- sub('^[[:space:]]+', '', status)
                                if(tolower(status) == 'process') {
                                        #This is a bit of a hack but if a line has zero length (i.e. a
                                        #black line), it will be removed in the resulting markdown file.
                                        #This will ensure that all line returns are retained.
                                        content[nchar(content) == 0] &lt;- ' '
                                        message(paste('Processing ', f, sep=''))
                                        content[statusLine] &lt;- 'status: publish'
                                        content[publishedLine] &lt;- 'published: true'
                                        outFile &lt;- paste(substr(f, 1, (nchar(f)-(nchar(in_ext)))), out_ext, sep='')
                                        render_markdown(strict=TRUE)
                                        opts_knit$set(out.format='markdown')
                                        opts_knit$set(fig.path="images/")
                                        opts_knit$set(base.dir=images.dir)
                                        opts_knit$set(base.url=images.url)
                                        opts_knit$set(fig.width=3.5,fig.height=3,tidy=FALSE)
                                        try(knit(text=content, output=outFile), silent=FALSE)
                                } else {
                                        warning(paste("Not processing ", f, ", status is '", status,
                                                                 "'. Set status to 'process' to convert.", sep=''))
                                }
                        } else {
                                warning("Status not found in front matter.")
                        }
                } else {
                        warning("No front matter found. Will not process this file.")
                }
        }
        invisible()
}
</code></pre>

<h2 id="from-r-markdown-to-html">From R Markdown to HTML</h2>

<p>Octopress ships with  <code>rdiscount</code> as the converter from markdown to HTML, but to handle math you want another converter.  I played around with <code>pandoc</code> for a while, but eventually decided on <code>kramdown</code>.</p>

<p>Octopress may be “locked” to a specific older version of <code>kramdown</code>, so install that version:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
</pre></td><td class="code"><pre><code class=""><span class="line">gem install kramdown -v 0.13.8</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>Now modify your Gemfile to include <code>kramdown</code>.  For example, my Gemfile now looks like:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
<span class="line-number">10</span>
<span class="line-number">11</span>
<span class="line-number">12</span>
<span class="line-number">13</span>
<span class="line-number">14</span>
<span class="line-number">15</span>
<span class="line-number">16</span>
<span class="line-number">17</span>
<span class="line-number">18</span>
<span class="line-number">19</span>
<span class="line-number">20</span>
<span class="line-number">21</span>
</pre></td><td class="code"><pre><code class=""><span class="line">source "https://rubygems.org"
</span><span class="line"> 
</span><span class="line">group :development do
</span><span class="line">  gem 'rake', '~&gt; 0.9'
</span><span class="line">  gem 'jekyll', '~&gt; 0.12'
</span><span class="line">  gem 'kramdown', '~&gt; 0.13.8'
</span><span class="line">  gem 'rdiscount', '~&gt; 2.0.7'
</span><span class="line">  gem 'pygments.rb', '~&gt; 0.3.4'
</span><span class="line">  gem 'RedCloth', '~&gt; 4.2.9'
</span><span class="line">  gem 'haml', '~&gt; 3.1.7'
</span><span class="line">  gem 'compass', '~&gt; 0.12.2'
</span><span class="line">  gem 'sass', '~&gt; 3.2'
</span><span class="line">  gem 'sass-globbing', '~&gt; 1.0.0'
</span><span class="line">  gem 'rubypants', '~&gt; 0.2.0'
</span><span class="line">  gem 'rb-fsevent', '~&gt; 0.9'
</span><span class="line">  gem 'stringex', '~&gt; 1.4.0'
</span><span class="line">  gem 'liquid', '~&gt; 2.3.0'
</span><span class="line">  gem 'directory_watcher', '1.4.1'
</span><span class="line">end
</span><span class="line"> 
</span><span class="line">gem 'sinatra', '~&gt; 1.4.2'</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>Also, edit your <code>_config.yml</code> file:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
</pre></td><td class="code"><pre><code class=""><span class="line">gems: [ 'kramdown' ]
</span><span class="line">markdown: kramdown</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>To get MathJax to work, my source is <a href="http://blog.zhengdong.me/2012/12/19/latex-math-in-octopress">Zheng Dong</a>,</p>

<p>Open <code>source/_includes/custom/head.html</code> and add the following:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
<span class="line-number">10</span>
<span class="line-number">11</span>
<span class="line-number">12</span>
<span class="line-number">13</span>
<span class="line-number">14</span>
<span class="line-number">15</span>
<span class="line-number">16</span>
<span class="line-number">17</span>
<span class="line-number">18</span>
<span class="line-number">19</span>
<span class="line-number">20</span>
<span class="line-number">21</span>
<span class="line-number">22</span>
<span class="line-number">23</span>
<span class="line-number">24</span>
<span class="line-number">25</span>
<span class="line-number">26</span>
<span class="line-number">27</span>
<span class="line-number">28</span>
<span class="line-number">29</span>
<span class="line-number">30</span>
<span class="line-number">31</span>
</pre></td><td class="code"><pre><code class=""><span class="line">&lt;!-- MathJax --&gt;
</span><span class="line">&lt;script type="text/x-mathjax-config"&gt;
</span><span class="line">  MathJax.Hub.Config({
</span><span class="line">    tex2jax: {
</span><span class="line">      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
</span><span class="line">      processEscapes: true
</span><span class="line">    }
</span><span class="line">  });
</span><span class="line">&lt;/script&gt;
</span><span class="line"> 
</span><span class="line">&lt;script type="text/x-mathjax-config"&gt;
</span><span class="line">    MathJax.Hub.Config({
</span><span class="line">      tex2jax: {
</span><span class="line">        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
</span><span class="line">      }
</span><span class="line">    });
</span><span class="line">&lt;/script&gt;
</span><span class="line"> 
</span><span class="line">&lt;script type="text/x-mathjax-config"&gt;
</span><span class="line">    MathJax.Hub.Queue(function() {
</span><span class="line">        var all = MathJax.Hub.getAllJax(), i;
</span><span class="line">        for(i=0; i &lt; all.length; i += 1) {
</span><span class="line">            all[i].SourceElement().parentNode.className += ' has-jax';
</span><span class="line">        }
</span><span class="line">    });
</span><span class="line">&lt;/script&gt;
</span><span class="line"> 
</span><span class="line">&lt;script type="text/javascript"
</span><span class="line">   src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"&gt;
</span><span class="line">&lt;/script&gt;
</span><span class="line"> </span></code></pre></td></tr></table></div></figure></notextile></div>

<h2 id="considerations-of-style">Considerations of Style</h2>

<p>Open <code>octopress/sass/custom/_styles.css</code> and add:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
<span class="line-number">10</span>
<span class="line-number">11</span>
<span class="line-number">12</span>
<span class="line-number">13</span>
<span class="line-number">14</span>
<span class="line-number">15</span>
<span class="line-number">16</span>
<span class="line-number">17</span>
<span class="line-number">18</span>
<span class="line-number">19</span>
<span class="line-number">20</span>
<span class="line-number">21</span>
<span class="line-number">22</span>
<span class="line-number">23</span>
<span class="line-number">24</span>
<span class="line-number">25</span>
<span class="line-number">26</span>
<span class="line-number">27</span>
<span class="line-number">28</span>
<span class="line-number">29</span>
<span class="line-number">30</span>
<span class="line-number">31</span>
<span class="line-number">32</span>
<span class="line-number">33</span>
<span class="line-number">34</span>
<span class="line-number">35</span>
<span class="line-number">36</span>
<span class="line-number">37</span>
<span class="line-number">38</span>
<span class="line-number">39</span>
<span class="line-number">40</span>
<span class="line-number">41</span>
<span class="line-number">42</span>
<span class="line-number">43</span>
<span class="line-number">44</span>
<span class="line-number">45</span>
<span class="line-number">46</span>
<span class="line-number">47</span>
<span class="line-number">48</span>
<span class="line-number">49</span>
<span class="line-number">50</span>
<span class="line-number">51</span>
<span class="line-number">52</span>
<span class="line-number">53</span>
<span class="line-number">54</span>
<span class="line-number">55</span>
<span class="line-number">56</span>
<span class="line-number">57</span>
<span class="line-number">58</span>
<span class="line-number">59</span>
<span class="line-number">60</span>
<span class="line-number">61</span>
<span class="line-number">62</span>
<span class="line-number">63</span>
<span class="line-number">64</span>
<span class="line-number">65</span>
<span class="line-number">66</span>
<span class="line-number">67</span>
<span class="line-number">68</span>
<span class="line-number">69</span>
<span class="line-number">70</span>
<span class="line-number">71</span>
<span class="line-number">72</span>
<span class="line-number">73</span>
<span class="line-number">74</span>
<span class="line-number">75</span>
<span class="line-number">76</span>
<span class="line-number">77</span>
<span class="line-number">78</span>
<span class="line-number">79</span>
<span class="line-number">80</span>
<span class="line-number">81</span>
<span class="line-number">82</span>
</pre></td><td class="code"><pre><code class=""><span class="line">#markdown-toc:before {
</span><span class="line">  content: "In this Post";
</span><span class="line">  font-weight: bold;
</span><span class="line">}
</span><span class="line">ul#markdown-toc {
</span><span class="line">  list-style: none;
</span><span class="line">  float: right;
</span><span class="line">  @include shadow-box;
</span><span class="line">  background-color: white;
</span><span class="line">}
</span><span class="line"> 
</span><span class="line"> 
</span><span class="line"> 
</span><span class="line">caption {
</span><span class="line">  font-weight:  bolder;
</span><span class="line">  text-align:  center;
</span><span class="line">  margin-bottom:  20px; 
</span><span class="line">}
</span><span class="line"> 
</span><span class="line">figcaption {
</span><span class="line">  font-weight:  bolder;
</span><span class="line">  text-align:  center;
</span><span class="line">  margin-bottom:  30px; 
</span><span class="line">}
</span><span class="line"> 
</span><span class="line">p img {
</span><span class="line">  display: block;
</span><span class="line">  margin-left: auto;
</span><span class="line">  margin-right: auto;
</span><span class="line">  margin-bottom: 10px;
</span><span class="line">  border-style:  ridge;
</span><span class="line">  border-color:  teal;
</span><span class="line">  border-width:  thick;
</span><span class="line">  padding:  5px 5px 5px 5px;
</span><span class="line">}
</span><span class="line"> 
</span><span class="line">table, th, td
</span><span class="line">{
</span><span class="line">border: 1px solid black;
</span><span class="line">}
</span><span class="line"> 
</span><span class="line">td
</span><span class="line">{
</span><span class="line">padding:15px;
</span><span class="line">}
</span><span class="line"> 
</span><span class="line">table, td, th
</span><span class="line">{
</span><span class="line">border:1px solid green;
</span><span class="line">}
</span><span class="line">th
</span><span class="line">{
</span><span class="line">background-color: rgb(147,161,161);
</span><span class="line">color:white;
</span><span class="line">}
</span><span class="line"> 
</span><span class="line">table {
</span><span class="line">    margin-left:auto; 
</span><span class="line">    margin-right:auto;
</span><span class="line">    margin-bottom:  30px;
</span><span class="line">  }
</span><span class="line">  
</span><span class="line"> 
</span><span class="line">dt {
</span><span class="line">  display:  block;
</span><span class="line">  font-weight:  bolder;
</span><span class="line">  margin-bottom:  15px;
</span><span class="line">  
</span><span class="line">}
</span><span class="line"> 
</span><span class="line">dd {
</span><span class="line">  display:  block;
</span><span class="line">  border-style:  double;
</span><span class="line">  border-color:  blue;
</span><span class="line">  border-width:  medium;
</span><span class="line">  padding:  5px 5px 5px 5px;
</span><span class="line">  margin-bottom:  15px;
</span><span class="line">}
</span><span class="line"> 
</span><span class="line">dl {
</span><span class="line">  margin-bottom:  30px;
</span><span class="line">}</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>Drawback:  your blog will look exactly like my blog.</p>

<p>Notes:</p>

<ul>
  <li>the table of contents styling was from <a href="http://blog.riemann.cc/2013/04/10/table-of-contents-in-octopress/">Robert Riemann</a>.</li>
  <li>CSS for <code>caption</code> and <code>figcaption</code> are left over from earlier experiments with <code>pandoc</code>, but I’m retaining them in case they come in handy later.</li>
</ul>

<h2 id="producing-a-post">Producing a Post</h2>

<p>Create a new .Rmd document, and put it in <code>Rmd_sources</code>.  At the top, make sure you have stuff like this:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
</pre></td><td class="code"><pre><code class=""><span class="line">---
</span><span class="line">layout: post
</span><span class="line">title: "Your Title Here in Quotes"
</span><span class="line">date: 2014-04-17 01:00:00
</span><span class="line">comments: true
</span><span class="line">categories: [YourCategoryName]
</span><span class="line">published: true
</span><span class="line">status: publish
</span><span class="line">---</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>If you want the table of contents that <code>kramdown</code> provides, then add the following a couple of lines on down:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
</pre></td><td class="code"><pre><code class=""><span class="line">* will be replaced by TOC
</span><span class="line">{:toc}</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>It’s a good idea to set some chunk options (use <code>include-FALSE</code>):</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
</pre></td><td class="code"><pre><code class=""><span class="line">opts_chunk$set(tidy=FALSE,fig.width=4.5,fig.height=3.5)</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>All images from all posts end up in the same directory, so when a code chunk results in a graphic give that chunk a unique name (different from all other graph chunks that you will ever produce with this blog).</p>

<p>When you are ready to process run:</p>

<pre><code>source("~/octopress/rmarkdown.r")
</code></pre>

<p>(This assumes your working directory is your home directory, and that <code>octopress</code> is directly under your home.  Modify the path name if this is not the case.)</p>

<p>Then change working directory to <code>Rmd_sources</code> and run:</p>

<pre><code>convertRMarkdown()
system("cp figure/* ../source/images/figure")
</code></pre>

<p>If you created any cache make sure you named the chunks uniquely.  Also you need to run:</p>

<pre><code>system("cp cache/* ../source/images/cache")
</code></pre>

<p>Finally, get the markdown file into the <code>source/_posts</code> directory:</p>

<pre><code>system("cp 2014-04-01-HowToSurviveZombieArmageddonUsingR.markdown ../source/_posts")
</code></pre>

<p>Then the usual:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
</pre></td><td class="code"><pre><code class=""><span class="line">rake generate
</span><span class="line">rake preview</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>until it looks good, then</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
</pre></td><td class="code"><pre><code class=""><span class="line">rake deploy</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>Then commit your changes and push to Git Hub repository:</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
</pre></td><td class="code"><pre><code class=""><span class="line">git add --all
</span><span class="line">git commit -m "add Zombie Armageddon Survival Guide"
</span><span class="line">git push origin source</span></code></pre></td></tr></table></div></figure></notextile></div>

<h2 id="creating-a-topics-feed">Creating a Topics Feed</h2>

<p>Say you produce something you think merits wider distribution, and want to pass it on to a great site like <a href="http://www.r-bloggers.com/">R-bloggers</a>:  then you need to create a category feed.  Here’s some help I got from <a href="http://hairysun.com/blog/2011/11/09/creating-category-feeds-in-octopress/">Matt Harrison</a>.</p>

<p>Create the file the <code>source/YourCategoryName.xml</code> (make sure to modify occurrences of “YourCategoryName” in what follows to whatever you please):</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
<span class="line-number">10</span>
<span class="line-number">11</span>
<span class="line-number">12</span>
<span class="line-number">13</span>
<span class="line-number">14</span>
<span class="line-number">15</span>
<span class="line-number">16</span>
<span class="line-number">17</span>
<span class="line-number">18</span>
<span class="line-number">19</span>
<span class="line-number">20</span>
<span class="line-number">21</span>
<span class="line-number">22</span>
<span class="line-number">23</span>
<span class="line-number">24</span>
<span class="line-number">25</span>
<span class="line-number">26</span>
<span class="line-number">27</span>
<span class="line-number">28</span>
<span class="line-number">29</span>
</pre></td><td class="code"><pre><code class=""><span class="line">---
</span><span class="line">layout: nil
</span><span class="line">---
</span><span class="line">&lt;?xml version="1.0" encoding="utf-8"?&gt;
</span><span class="line">&lt;feed xmlns="http://www.w3.org/2005/Atom"&gt;
</span><span class="line"> 
</span><span class="line">  &lt;title&gt;A Statistics Blog - YourCategoryName&lt;/title&gt;
</span><span class="line">  &lt;link href="http://statistics.rainandrhino.org/atom.xml" rel="self"/&gt;
</span><span class="line">  &lt;link href="http://statistics.rainandrhino.org/"/&gt;
</span><span class="line">  &lt;updated&gt;2015-07-02T18:05:37-04:00&lt;/updated&gt;
</span><span class="line">  &lt;id&gt;http://statistics.rainandrhino.org/&lt;/id&gt;
</span><span class="line">  &lt;author&gt;
</span><span class="line">    &lt;name&gt;Homer White&lt;/name&gt;
</span><span class="line">    
</span><span class="line">  &lt;/author&gt;
</span><span class="line">  &lt;generator uri="http://octopress.org/"&gt;Octopress&lt;/generator&gt;
</span><span class="line"> 
</span><span class="line">  
</span><span class="line">&lt;/feed&gt;</span></code></pre></td></tr></table></div></figure></notextile></div>

<h2 id="archive-old-r-markdowns">Archive Old R Markdowns</h2>

<p>Once you are done publishing a post, move the R Markdown source into the <code>Rmd_sources_old</code> directory, so the <code>ConvertRMarkdown()</code> function won’t keep processing them needlessly.</p>

<h2 id="lingering-problems">Lingering Problems</h2>

<ul>
  <li><code>kramdown</code> differs from <code>knitr</code> in how it recognizes math.  If you see odd results, consult the <code>kramdown</code> documentation on the web to learn how to really really do it right.  If you want to keep on the R Markdown way, then from time to time you may have to escape certain special characters.</li>
  <li>R-bloggers takes your stuff from a blog feed.  It does not recognize MathJax, so your math won’t render.</li>
</ul>

</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/04/08/reasons-to-teach-with-R-2/">Five Reasons to Teach Elementary Statistics With R: #2</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-04-08T19:59:59-04:00" pubdate data-updated="true">Apr 8<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/04/08/reasons-to-teach-with-R-2/#disqus_thread"
             data-disqus-identifier="http://statistics.rainandrhino.org/blog/2014/04/08/reasons-to-teach-with-R-2/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#introduction">Introduction</a></li>
  <li><a href="#reason-2--rstudios-manipulate">Reason #2:  RStudio’s <code>manipulate</code></a>    <ul>
      <li><a href="#do-it-yourself">Do It Yourself</a></li>
      <li><a href="#next-time">Next Time</a></li>
    </ul>
  </li>
</ul>

<h2 id="introduction">Introduction</h2>

<p>This is is second in a projected five-part series of posts aimed at colleagues who teach elementary statistics.  If you teach with R but hesitate to spring such a powerful and complex tool on unsuspecting introductory students—many of whom whom will have had no prior experience with the command line, much less with coding—then I hope these posts will give you some encouragement.</p>

<p>The <a href="http://statistics.rainandrhino.org/blog/2014/04/05/tigerstatsintro/">first post</a> in this series introduced package <code>mosaic</code>, and promised to review a supplementary package that I and a colleague put together for our own students, but I’ve decided put that off a bit and focus instead on another powerful new tool for statistics instruction:  the well-known <a href="https://www.rstudio.com/">RStudio</a> Integrated Development Environment for R, and its <code>manipulate</code> package in particular.</p>

<h2 id="reason-2--rstudios-manipulate">Reason #2:  RStudio’s <code>manipulate</code></h2>

<p>You might think that an IDE is strictly for programmers.  The authors of <code>mosaic</code>, though, looked at RStudio and saw an environment ripe for customization to fit the elementary classroom.  RStudio offers many benefits in this regard, but for this post I’ll concentrate on just one:  its pre-installed package <code>manipulate</code>.</p>

<p>The RStudio developers may have written <code>manipulate</code> simply as a prototype for <a href="http://shiny.rstudio.com/">Shiny</a>, but it happens to be a fabulous tool for authoring instructional applets.  To be sure, there are many great instructional apps out on the web—visual stunners put together by authentic web developers—but the everyday statistics instructor may find that <code>manipulate</code> empowers her to quickly work up small instructional apps that address needs specific to her own students.</p>

<p>At my College, for example, we believe that simulation is important to understanding probability concepts, but we also find that our students don’t easily grasp the import of a simulation when the computers simply generates, say, 3000 re-samples and summarizes the results, <em>all in flash</em>.  We feel the need for plenty of “one at a time” simulation experiences that serve as transitions to the analysis of large-scale simulation results, and we don’t always find apps on the web that cater to our needs in just the way we would like.</p>

<p>Suppose you want students to understand coverage properties of confidence intervals—i.e., what we really mean when we say that we are “95%-confident” that the interval covers the population parameter–in a ground-up way.  Then you might do as my colleague Rebekah Robinson did, and write a manipulate app like <code>CIMean()</code>.</p>

<p>To get the app, install package <code>tigerstats</code> from CRAN, or for the very latest version try:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<p>Next, get into RStudio (if you are not there already), and run:</p>

<pre><code>require(tigerstats)
require(manipulate)
CIMean(~height,data=imagpop)
</code></pre>

<p>The app loads in the (roughly normally distributed) heights of an imaginary population of 10,000 people.  Sliders allow the user to select a sample size and a desired confidence level.  Click on one of the sliders and you’ll get just one sample from the population, with a histogram of the sample overlaying the density curve for the population, and a confidence interval displayed clearly along the horizontal axis.  The user can easily see whether the interval contains the population mean (marked by the red vertical line).  Output to the console also keeps the user apprised of what has just happened.  When the user has clicked enough to get the idea, he/she can ask for a lot of samples at once, verifying that when assumptions are met 95%-confidence intervals do indeed cover their target parameter about 95% of the time.</p>

<p>One advantage of <code>manipulate</code> apps over the visually spectacular ones you find on the web is that you can easily write them to accept arbitrary input.  <code>CIMean()</code>, for example, will deal with any numerical variable from any data frame on R’s search path,including the quite right-skewed variable <strong>income</strong> from<code>imagpop</code>:</p>

<pre><code>CIMean(~income,data=imagpop)
</code></pre>

<p>The user realizes quickly that the standard t-intervals applied to small samples from skewed populations do not possess the advertised coverage properties.</p>

<p>Once you get into the spirit of <code>manipulate</code> you may find yourself writing apps that work in a similar vein without requiring the elements of the package itself.  For example <code>ChisqSimSlow()</code>, which does not require <code>manipulate</code> (and in fact runs outside of RStudio) takes arbitrary data and applies a one-at-a-time re-sampling routine to slowly build up the Null Distribution of the chi-square statistic, in a situation where one is testing whether two factor variables are associated.</p>

<p>For example, suppose we are looking at survey in which a random sample of students were asked for their sex and for their seating preference in a classroom:</p>

<pre><code>SexSeat &lt;- xtabs(~sex+seat,data=m111survey)
SexSeat

##         seat
## sex      1_front 2_middle 3_back
##   female      19       16      5
##   male         8       16      7
</code></pre>

<p>Let’s check this out with some row percentages:</p>

<pre><code>rowPerc(SexSeat)

##        1_front 2_middle 3_back Total
## female   47.50    40.00  12.50   100
## male     25.81    51.61  22.58   100
</code></pre>

<p>Hmm, the women in the sample seem much more likely than the guys to prefer the Front!  Does this data provide convincing evidence for a relationship between <strong>sex</strong> and <strong>seat</strong> in the College population at large?  To investigate this, a student might try:</p>

<pre><code>ChisqSimSlow(~sex+seat,data=m111survey)
</code></pre>

<p>Keep asking for a re-sample, and after a while you get the sense that the observed value of the chi-square statistic is not an unusually large value, if <strong>sex</strong> and <strong>seat</strong> are, all along, unrelated in the population.</p>

<p>Once students understand the import of simulation they can employ it to advantage on a large scale.  In the <code>tigerstats</code> version of the <code>chisq.test()</code>, the student might ask for:</p>

<pre><code>set.seed(2014)
chisqtestGC(~sex+seat,data=m111survey,
      simulate.p.value="random",
      B=3000,
      graph=TRUE)

## Pearson's chi-squared test with simulated p-value, random effects
## 	 (based on 3000 resamples)
## 
## Observed Counts:
##         seat
## sex      1_front 2_middle 3_back
##   female      19       16      5
##   male         8       16      7
## 
## Counts Expected by Null:
##         seat
## sex      1_front 2_middle 3_back
##   female   15.21    18.03   6.76
##   male     11.79    13.97   5.24
## 
## Contributions to the chi-square statistic:
##         seat
## sex      1_front 2_middle 3_back
##   female    0.94     0.23   0.46
##   male      1.22     0.29   0.59
## 
## 
## Chi-Square Statistic = 3.734 
## Degrees of Freedom of the table = 2 
## P-Value = 0.1727
</code></pre>

<p><img src="/images/figure/reasonsteachr2.png" alt="plot of chunk reasonsteachr2" /> </p>

<h3 id="do-it-yourself">Do It Yourself</h3>

<p>I do not discuss the above apps with the expectation that colleagues at other institution will adopt them.  On the contrary, my point is merely that the folks at RStudio have provided R-users with a tool that enables ordinary instructors like us to write our own apps.  If you like a particular app, them check out the source code (<code>tigerstats</code>, for example is <a href="http:github.com/homerhanumat/tigerstats">on GitHub</a>), clean it up a bit maybe, and use it as a basis for an app tailored to your particular tastes and the needs of your particular students.</p>

<p>Better yet, persuade an upper-level student to write the app for you as a programming project:  <code>manipulate</code>’s greatest use may prove to be as a gateway-drug to coding!</p>

<h3 id="next-time">Next Time</h3>

<p>In the next post, maybe we’ll have a look at what R Studio’s <code>shiny</code> can do for an elementary class.</p>
</div>
  
  


    </article>
  
  <div class="pagination">
    
      <a class="prev" href="/blog/page/3/">&larr; Older</a>
    
    <a href="/blog/archives">Blog Archives</a>
    
    <a class="next" href="/">Newer &rarr;</a>
    
  </div>
</div>
<aside class="sidebar">
  
    <section>
  <h1>Recent Posts</h1>
  <ul id="recent_posts">
    
      <li class="post">
        <a href="/blog/2015/07/03/shiny-simulation-tutorial/">A Tutorial on Writing Simulation Apps in Shiny</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/09/03/google-charts/">Google Charts in R Markdown</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/08/27/r-studio-server-centos-pandoc-latex/">New Wine in an Old Bottle: R Markdown V2 and R Studio on the Cent OS Server</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/05/04/reasons-to-teach-with-R-3/">Five Reasons to Teach Elementary Statistics With R: #3</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/05/02/perl-scripts-r-studio/">Course Management With the RStudio Server</a>
      </li>
    
  </ul>
</section>

<section>
  <h1>GitHub Repos</h1>
  <ul id="gh_repos">
    <li class="loading">Status updating&#8230;</li>
  </ul>
  
  <a href="https://github.com/homerhanumat">@homerhanumat</a> on GitHub
  
  <script type="text/javascript">
    $(document).ready(function(){
        if (!window.jXHR){
            var jxhr = document.createElement('script');
            jxhr.type = 'text/javascript';
            jxhr.src = '/javascripts/libs/jXHR.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(jxhr, s);
        }

        github.showRepos({
            user: 'homerhanumat',
            count: 5,
            skip_forks: true,
            skip_repos: [ "homerhanumat.github.io" ],
            target: '#gh_repos'
        });
    });
  </script>
  <script src="/javascripts/github.js" type="text/javascript"> </script>
</section>



<section class="googleplus">
  <h1>
    <a href="https://plus.google.com/101037539642604924807?rel=author">
      <img src="http://www.google.com/images/icons/ui/gprofile_button-32.png" width="32" height="32">
      Google+
    </a>
  </h1>
</section>


<section>
  <h1>Categories</h1>
  <ul id="categories">
    <li class='category'><a href='/blog/categories/r/'>R (7)</a></li>
<li class='category'><a href='/blog/categories/student-focused-tutorials/'>Student-Focused Tutorials (15)</a></li>
<li class='category'><a href='/blog/categories/tech-note/'>Tech Note (4)</a></li>

  </ul>
</section>
<section>
  <h1>Useful Links</h1>
  <ul id="links">
      <li class="post"><a href="http://www.r-bloggers.com" target="_blank">R-Bloggers</a></li>
      <li class="post"><a href="http://mosaic-web.org/" target="_blank">Project Mosaic</a></li>
      <li class="post"><a href="http://statistics.georgetowncollege.edu", target="_blank">My Elementary Course</a></li> 
  </ul>
</section>

  
</aside>

    </div>
  </div>
  <footer role="contentinfo"><p float>
  2015 - Homer White -
  <span class="credit">Powered by <a href="http://octopress.org">Octopress</a>
</p>
<p>      
  <span> <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /></span><span style="color:black">This work is licensed under a </span><a style="color:black" rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/deed.en_US">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
  </span>
</p>

</footer>
  

<script type="text/javascript">
      var disqus_shortname = 'homerhanumatgithubio';
      
        
        var disqus_script = 'count.js';
      
    (function () {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/' + disqus_script;
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    }());
</script>



<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id; js.async = true;
  js.src = "//connect.facebook.net/en_US/all.js#appId=212934732101925&xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>









</body>
</html>
