
<!DOCTYPE html>
<!--[if IEMobile 7 ]><html class="no-js iem7"><![endif]-->
<!--[if lt IE 9]><html class="no-js lte-ie8"><![endif]-->
<!--[if (gt IE 8)|(gt IEMobile 7)|!(IEMobile)|!(IE)]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <title>A Statistics Blog</title>
  <meta name="author" content="Homer White">

  
  <meta name="description" content="Preliminaries Finding P(X &lt; x) Find P(X &gt; x) Finding P(a &lt; X &lt; b) “Outside” Probabilities Non-Strict Inequalities Preliminaries pnormGC &hellip;">
  

  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  
  <link rel="canonical" href="http://homerhanumat.github.io/blog/page/4">
  <link href="/favicon.png" rel="icon">
  <link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">
  <link href="/atom.xml" rel="alternate" title="A Statistics Blog" type="application/atom+xml">
  <script src="/javascripts/modernizr-2.0.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script>!window.jQuery && document.write(unescape('%3Cscript src="./javascripts/libs/jquery.min.js"%3E%3C/script%3E'))</script>
  <script src="/javascripts/octopress.js" type="text/javascript"></script>
  <!--Fonts from Google"s Web font directory at http://google.com/webfonts -->
<link href="http://fonts.googleapis.com/css?family=PT+Serif:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
<!-- MathJax -->
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true
    }
  });
</script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
      }
    });
</script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Queue(function() {
        var all = MathJax.Hub.getAllJax(), i;
        for(i=0; i < all.length; i += 1) {
            all[i].SourceElement().parentNode.className += ' has-jax';
        }
    });
</script>

<script type="text/javascript"
   src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>


  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-47254229-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>


</head>

<body   >
  <header role="banner"><hgroup>
  <h1><a href="/">A Statistics Blog</a></h1>
  <img src="/favicon.png" style="float:  right; align:  right; width: 20%;">
  
    <h2>R for Statistics Education, and information for the courses I teach.</h2>
  
 
</hgroup>

</header>
  <nav role="navigation"><ul class="subscription" data-subscription="rss">
  <li><a href="/atom.xml" rel="subscribe-rss" title="subscribe via RSS">RSS</a></li>
  
</ul>
  
<form action="http://google.com/search" method="get">
  <fieldset role="search">
    <input type="hidden" name="q" value="site:homerhanumat.github.io" />
    <input class="search" type="text" name="q" results="0" placeholder="Search"/>
  </fieldset>
</form>
  
<ul class="main-navigation">
  <li><a href="/">Blog</a></li>
  <li><a href="/blog/archives">Archives</a></li>
  <li><a href="/about/index.html">About</a></li>
</ul>

</nav>
  <div id="main">
    <div id="content">
      <div class="blog-index">
  
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/26/pnormGCtutorial/">pnormGC() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-26T16:00:00-05:00" pubdate data-updated="true">Feb 26<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/02/26/pnormGCtutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/26/pnormGCtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#finding-px--x">Finding P(X &lt; x)</a></li>
  <li><a href="#find-px--x">Find P(X &gt; x)</a></li>
  <li><a href="#finding-pa--x--b">Finding P(a &lt; X &lt; b)</a></li>
  <li><a href="#outside-probabilities">“Outside” Probabilities</a></li>
  <li><a href="#non-strict-inequalities">Non-Strict Inequalities</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p><code>pnormGC()</code> provides a direct way to compute probabilities for normal random variables, along with graphs for the probabilities, if you want them.  The function comes from the <code>tigerstats</code> package, so make sure that <code>tigerstats</code> is loaded:</p>

<pre><code>require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need to install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<h2 id="finding-px--x">Finding P(X &lt; x)</h2>

<p>Suppose that you have a normal random variable $X$ with mean $\mu=70$ and standard deviation $\sigma=3$, and you would like to find the chance that $X$ will turn out to be less than 66.  In other words, you are looking for:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 66). %]]></script>

<p>Then run this command:</p>

<pre><code>pnormGC(bound=66,region="below",mean=70,sd=3)

## [1] 0.09121
</code></pre>

<p>Note carefully what the arguments mean, here:</p>

<ul>
  <li><code>bound=66</code> tells <code>pnormGC()</code> where to stop</li>
  <li><code>region="below"</code> takes care of the “less than” part of the requested probability</li>
  <li><code>mean=70</code> specifies the mean $\mu$ of $X$</li>
  <li><code>sd=3</code> specifies the standard deviation $\sigma$ of $X$</li>
</ul>

<p>If you would like to see a graph of the probability distribution of $X$ along with a shaded area that represents the requested probability, then you can set the argument <code>graph</code> to <code>TRUE</code>:</p>

<pre><code>pnormGC(bound=66,region="below",
        mean=70,sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/normtutless66.png" alt="plot of chunk normtutless66" /> </p>

<pre><code>## [1] 0.09121
</code></pre>

<p>You should ask for a graph until you are confident of being able to use <code>pnormGC()</code> to get exactly the probability that you want.</p>

<h2 id="find-px--x">Find P(X &gt; x)</h2>

<p>For the same random variable $X \sim norm(70,3)$, suppose we want the probability that $X$ is greater than 69, i.e.:</p>

<script type="math/tex; mode=display">P(X > 69).</script>

<p>Ask for:</p>

<pre><code>pnormGC(bound=69,region="above",
        mean=70,sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/normtutgreater69.png" alt="plot of chunk normtutgreater69" /> </p>

<pre><code>## [1] 0.6306
</code></pre>

<h2 id="finding-pa--x--b">Finding P(a &lt; X &lt; b)</h2>

<p>For the same random variable $X \sim norm(70,3)$, suppose we want the probability that $X$ is between 68 and 72, i.e.:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(68 < X < 72). %]]></script>

<p>Ask for:</p>

<pre><code>pnormGC(bound=c(68,72),region="between",
        mean=70,sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/normtutbetween.png" alt="plot of chunk normtutbetween" /> </p>

<pre><code>## [1] 0.495
</code></pre>

<p>Observe that since there are two numbers—68 and 72—that are boundaries, we have to specify both of them for <code>pnormGC()</code> in the form of a list <code>c(68,72)</code>.</p>

<h2 id="outside-probabilities">“Outside” Probabilities</h2>

<p>For the same random variable $X \sim norm(70,3)$, suppose we want the probability that either $X$ is less than 66 OR that $X$ is more than 73.  Then we are looking for:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 66 \textbf{ or } X > 73). %]]></script>

<p>We can find this with the command:</p>

<pre><code>pnormGC(bound=c(66,73),region="outside",
         mean=70,sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/mormtutout.png" alt="plot of chunk mormtutout" /> </p>

<pre><code>## [1] 0.2499
</code></pre>

<p>Again observe that there are two numbers—66 and 73—that make the boundaries, so supply both of them to the <code>bound</code> argument as a list:  <code>c(66,72)</code>.</p>

<h2 id="non-strict-inequalities">Non-Strict Inequalities</h2>

<p>Suppose that for the same random variable $X \sim norm(70,3)$, you want the probability that $X$ will turn out to be <em>no more than</em> 66, i.e., you want:</p>

<script type="math/tex; mode=display">P(X \leq 66).</script>

<p>You get this with exactly the same function call that gives you $P(X &lt; 66)$, namely:</p>

<pre><code>pnormGC(bound=66,region="below",
        mean=70,sd=3)
</code></pre>

<p>Remember why?  Normal random variables are <em>continuous</em> random variables, and for any continuous random variable the chance that it is <em>exactly</em> equal to any particular value is zero.  For example, the probability that $X$ is exactly equal to 66 is given by:</p>

<pre><code>pnormGC(bound=c(66,66),region="between",
        mean=70,sd=3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/normtutequal.png" alt="plot of chunk normtutequal" /> </p>

<pre><code>## [1] 0
</code></pre>

<p>The probability of getting exactly 66 is given by the area of the line segment under the curve over 66.  But the area of a line segment—if you think of it as a “rectangle”” with zero width—is zero!</p>

<p>When you ask for</p>

<script type="math/tex; mode=display">P(X \leq 66)</script>

<p>as opposed to</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 66), %]]></script>

<p>you are adding on just the chance of $X$ being exactly 66.  Since this extra chance is zero, you get the same probability as you did with the strict inequality.</p>

</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/26/pbinomGCtutorial/">pbinomGC() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-26T15:00:00-05:00" pubdate data-updated="true">Feb 26<span>th</span>, 2014</time>
        
           | <a href="/blog/2014/02/26/pbinomGCtutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/26/pbinomGCtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#finding-px--x">Finding P(X &lt;= x)</a></li>
  <li><a href="#find-px--x">Find P(X &gt;= x)</a></li>
  <li><a href="#strict-inequalities--finding-px--x">Strict Inequalities:  Finding P(X &lt; x)</a></li>
  <li><a href="#strict-inequalities--finding-px--x-1">Strict Inequalities:  Finding P(X &gt; x)</a></li>
  <li><a href="#finding-pa--x--b">Finding P(a &lt;= X &lt;= b)</a></li>
  <li><a href="#finding-px--x-1">Finding P(X = x)</a></li>
  <li><a href="#outside-probabilities">“Outside” Probabilities</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p><code>pbinomGC()</code> provides a direct way to compute probabilities for binomial random variables, along with graphs for the probabilities, if you want them.  The function comes from the <code>tigerstats</code> package, so make sure that <code>tigerstats</code> is loaded:</p>

<pre><code>require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<h2 id="finding-px--x">Finding P(X &lt;= x)</h2>

<p>Suppose that you have a binomial random variable with $n=20$ trials, and chance of success $p=0.3$ on each trial, and you would like to find the chance of getting 8 or fewer successes in your 20 trials.  In other words (letting $X$ stand for the binomial random variable), you are looking for:</p>

<script type="math/tex; mode=display">P(X \leq 8).</script>

<p>Then run this command:</p>

<pre><code>pbinomGC(bound=8,region="below",size=20,prob=0.3)

## [1] 0.8867
</code></pre>

<p>Note carefully what the arguments mean, here:</p>

<ul>
  <li><code>bound=8</code> tells where to stop</li>
  <li><code>region="below"</code> takes care of the “less than” part of the requested probability</li>
  <li><code>size=20</code> tells <code>pbinomGC()</code> the number of trials for $X$</li>
  <li><code>prob=0.3</code> tells <code>pbinomGC()</code> the chance of success on each trial</li>
</ul>

<p>If you would like to see a graph of the probability distribution of $X$ along with a shaded area that represents the requested probability, then you can set the argument <code>graph</code> to <code>TRUE</code>:</p>

<pre><code>pbinomGC(bound=8,region="below",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutleq8.png" alt="plot of chunk binomtutleq8" /> </p>

<pre><code>## [1] 0.8867
</code></pre>

<h2 id="find-px--x">Find P(X &gt;= x)</h2>

<p>For the same random variable $X \sim binom(20,0.3)$, suppose we want the probability of at least 10 successes, i.e.:</p>

<script type="math/tex; mode=display">P(X \geq 10).</script>

<p>When we want to go “above” a given number, <code>pbinomGC()</code> will <em>not</em> include that number in its computation of probabilities, so asking for</p>

<pre><code>pbinomGC(bound=10,region="above",
         size=20,prob=0.3)
</code></pre>

<p>would give us the chance of $X$ being at least 11, which is not what we want.</p>

<p>However, since $X$ can only take on whole number values, $X \geq 10$ means exactly the same thing as $X &gt; 9$, what we really should ask for is:</p>

<pre><code>pbinomGC(bound=9,region="above",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutgeq10.png" alt="plot of chunk binomtutgeq10" /> </p>

<pre><code>## [1] 0.04796
</code></pre>

<p>The shaded area starts at 10, as desired.</p>

<p>It’s a good idea to keep asking for a graph along with your output, so you can check that R is giving you exactly the probability that you need.</p>

<h2 id="strict-inequalities--finding-px--x">Strict Inequalities:  Finding P(X &lt; x)</h2>

<p>For this case we also have to be careful.</p>

<p>For the same random variable $X \sim binom(20,0.3)$, suppose we want the probability of less than 6 successes, i.e.:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 6). %]]></script>

<p>Since $X$ is a discrete random variable with whole number values, $X &lt; 6$ means exactly the same thing thing as $X \leq 5$.  <code>pbinomGC()</code> includes the bound in the probability that it computes, so we have stop at 5, rather than at 6.  We use the command:</p>

<pre><code>pbinomGC(bound=5,region="below",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutless6.png" alt="plot of chunk binomtutless6" /> </p>

<pre><code>## [1] 0.4164
</code></pre>

<h2 id="strict-inequalities--finding-px--x-1">Strict Inequalities:  Finding P(X &gt; x)</h2>

<p>For the same random variable $X \sim binom(20,0.3)$, suppose we want the probability that the number of successes will be more than 7.  Then we are looking for:</p>

<script type="math/tex; mode=display">P(X > 7).</script>

<p>This is easy again.  Since <code>pbinomGC()</code> does not include the bound when <code>region</code> is “above”, we only need to ask for:</p>

<pre><code>pbinomGC(bound=7,region="above",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutgreater7.png" alt="plot of chunk binomtutgreater7" /> </p>

<pre><code>## [1] 0.2277
</code></pre>

<h2 id="finding-pa--x--b">Finding P(a &lt;= X &lt;= b)</h2>

<p>For the same random variable $X \sim binom(20,0.3)$, suppose we want the probability that the number of successes will be at least 6 but no more than 10.  Then we are looking for:</p>

<script type="math/tex; mode=display">P(6 \leq X \leq 10).</script>

<p>We can find this with the command:</p>

<pre><code>pbinomGC(bound=c(6,10),region="between",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutbetwee.png" alt="plot of chunk binomtutbetwee" /> </p>

<pre><code>## [1] 0.5665
</code></pre>

<p>Notice that there are no two numbers—6 and 10—that make the boundaries, so we must supply both of them to the <code>bound</code> argument as a list:  <code>c(6,10)</code>.  Also note that when <code>region="between"</code>, <code>pbinomGC()</code> includes <em>both</em> of the bounds in its computation of probabilities.</p>

<h2 id="finding-px--x-1">Finding P(X = x)</h2>

<p>To find the chance of $X$ being <em>exactly</em> a particular value, you can employ a little trick.</p>

<p>For example, for the same random variable $X \sim binom(20,0.3)$, suppose we want the chance of exactly 6 successes.  This is very same thing as</p>

<script type="math/tex; mode=display">P(6 \leq X \leq 6),</script>

<p>so you can ask for:</p>

<pre><code>pbinomGC(bound=c(6,6),region="between",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutequal.png" alt="plot of chunk binomtutequal" /> </p>

<pre><code>## [1] 0.1916
</code></pre>

<h2 id="outside-probabilities">“Outside” Probabilities</h2>

<p>This case does not occur very often.</p>

<p>For the same random variable $X \sim binom(20,0.3)$, suppose we want the probability that you either get less than 7 successes OR you get more than 9 successes.  Then we are looking for:</p>

<script type="math/tex; mode=display">% <![CDATA[
P(X < 7 \textbf{ or } X > 9). %]]></script>

<p>You can find this with the command:</p>

<pre><code>pbinomGC(bound=c(7,9),region="outside",
         size=20,prob=0.3,graph=TRUE)
</code></pre>

<p><img src="/images/figure/binomtutout.png" alt="plot of chunk binomtutout" /> </p>

<pre><code>## [1] 0.656
</code></pre>

<p>Notice that there are two numbers—7 and 9—that make the boundaries, so we must supply both of them to the <code>bound</code> argument as a list:  <code>c(6,10)</code>.  Notice also that when <code>region</code> is set to “outside”, <code>pbinomGC()</code> excludes both bounds.</p>
</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/21/barchartGCtutorial/">barchartGC() Tutorial</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-21T16:00:00-05:00" pubdate data-updated="true">Feb 21<span>st</span>, 2014</time>
        
           | <a href="/blog/2014/02/21/barchartGCtutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/21/barchartGCtutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#one-factor-variable">One Factor Variable</a></li>
  <li><a href="#two-factor-variables">Two Factor Variables</a></li>
  <li><a href="#warning">Warning</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p><code>barchartGC()</code> provides quick-and-easy bar charts for the graphical exploration of factor variables.  The function comes from the <code>tigerstats</code> package and we will use some data from the <code>tigerstats</code> as well, so make sure that <code>tigerstats</code> is loaded:</p>

<pre><code>require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo="homerhanumat/tigerstats")
</code></pre>

<p>In this tutorial we will work with the <code>m111survey</code> data frame from <code>tigerstats</code> package.  If you are not yet familiar with this data, then run:</p>

<pre><code>data(m111survey)
View(m111survey)
help(m111survey)
</code></pre>

<p>Remember that you can also learn about the types of each variable in the data frame with the <code>str()</code> function:</p>

<pre><code>str(m111survey)

## 'data.frame':	71 obs. of  12 variables:
##  $ height         : num  76 74 64 62 72 70.8 70 79 59 67 ...
##  $ ideal_ht       : num  78 76 NA 65 72 NA 72 76 61 67 ...
##  $ sleep          : num  9.5 7 9 7 8 10 4 6 7 7 ...
##  $ fastest        : int  119 110 85 100 95 100 85 160 90 90 ...
##  $ weight_feel    : Factor w/ 3 levels "1_underweight",..: 1 2 2 1 1 3 2 2 2 3 ...
##  $ love_first     : Factor w/ 2 levels "no","yes": 1 1 1 1 1 1 1 1 1 1 ...
##  $ extra_life     : Factor w/ 2 levels "no","yes": 2 2 1 1 2 1 2 2 2 1 ...
##  $ seat           : Factor w/ 3 levels "1_front","2_middle",..: 1 2 2 1 3 1 1 3 3 2 ...
##  $ GPA            : num  3.56 2.5 3.8 3.5 3.2 3.1 3.68 2.7 2.8 NA ...
##  $ enough_Sleep   : Factor w/ 2 levels "no","yes": 1 1 1 1 1 2 1 2 1 2 ...
##  $ sex            : Factor w/ 2 levels "female","male": 2 2 1 1 2 2 2 2 1 1 ...
##  $ diff.ideal.act.: num  2 2 NA 3 0 NA 2 -3 2 0 ...
</code></pre>

<h2 id="one-factor-variable">One Factor Variable</h2>

<p>To look see a bar chart for the tallies of the factor variable <strong>seat</strong>:</p>

<pre><code>barchartGC(~seat,data=m111survey,type="frequency",
           main="Barchart of Seating Preference")
</code></pre>

<p><img src="/images/figure/barchartseatfreq.png" alt="plot of chunk barchartseatfreq" /> </p>

<p>In order to get the actual distribution of <strong>seat</strong>, you want percents rather than counts:</p>

<pre><code>barchartGC(~seat,data=m111survey,type="percent",
           main="Barchart of Seating Preference")
</code></pre>

<p><img src="/images/figure/barchartseatperc.png" alt="plot of chunk barchartseatperc" /> </p>

<p>If you have a table of the counts for a variable, then you can enter it directly.  For example, suppose you have already made:</p>

<pre><code>Seat &lt;- xtabs(~seat,data=m111survey)
Seat

## seat
##  1_front 2_middle   3_back 
##       27       32       12
</code></pre>

<p>Then you can just enter the table:</p>

<pre><code>barchartGC(Seat,type="percent",
           main="Barchart of Seating Preference")
</code></pre>

<p><img src="/images/figure/barchartseattab.png" alt="plot of chunk barchartseattab" /> </p>

<h2 id="two-factor-variables">Two Factor Variables</h2>

<p>You can also use <code>barchartGC()</code> to study the relationship between two factor variables.  For example, if you want to see whether males and females differ in their seating preferences, then you might try formula-data input as follows:</p>

<pre><code>barchartGC(~sex+seat,data=m111survey,
           type="percent",
           main="Sex and Seating Preference\nat Georgetown")
</code></pre>

<p><img src="/images/figure/barchartsexseat.png" alt="plot of chunk barchartsexseat" /> </p>

<p>Again, if you happen to have already made a two-way table, then you can just enter it:</p>

<pre><code>SexSeat &lt;- xtabs(~sex+seat,data=m111survey)
SexSeat

##         seat
## sex      1_front 2_middle 3_back
##   female      19       16      5
##   male         8       16      7
</code></pre>

<p>Here is the bar chart from the two-way table:</p>

<pre><code>barchartGC(SexSeat,type="percent",
           main="Sex and Seating Preference\nat Georgetown")
</code></pre>

<p><img src="/images/figure/barchartsexseattab.png" alt="plot of chunk barchartsexseattab" /> </p>

<h2 id="warning">Warning</h2>

<p>Bar charts are for factor variables, not for numerical variables.  Look what happens when you ask for a bar chart of <strong>fastest</strong>:</p>

<pre><code>barchartGC(~fastest,data=m111survey,
           main="Fastest Speed Ever Driven")
</code></pre>

<p><img src="/images/figure/barchartfastest.png" alt="plot of chunk barchartfastest" /> </p>

<p>R tries to accommodate your request, but it ends up making something that resembles a very amateurish histogram.  R draws a separate bar for each speed that appears in the data, making for a very “busy” graph.  Worse yet, consecutive speeds are equally spaced from each other, even though the differences between consecutive speeds vary.  For example, the spacing between the 90 ans 91 mph bars is the same as the spacing between the 160 and 190 mph bars.  This is very misleading!</p>
</div>
  
  


    </article>
  
  
    <article>
      
  <header>
    
      <h1 class="entry-title"><a href="/blog/2014/02/21/favstatstutorial/">Tutorial on Mosaic&#8217;s Favstats()</a></h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-02-21T15:00:00-05:00" pubdate data-updated="true">Feb 21<span>st</span>, 2014</time>
        
           | <a href="/blog/2014/02/21/favstatstutorial/#disqus_thread"
             data-disqus-identifier="http://homerhanumat.github.io/blog/2014/02/21/favstatstutorial/">Comments</a>
        
      </p>
    
  </header>


  <div class="entry-content"><ul id="markdown-toc">
  <li><a href="#preliminaries">Preliminaries</a></li>
  <li><a href="#studying-one-numerical-variable">Studying One Numerical Variable</a></li>
  <li><a href="#studying-the-relationship-between-a-numerical-variable-and-a-factor-variable">Studying the Relationship Between a Numerical Variable and a Factor Variable</a></li>
  <li><a href="#limiting-the-output">Limiting the Output</a></li>
  <li><a href="#warning">Warning</a></li>
</ul>

<h2 id="preliminaries">Preliminaries</h2>

<p><code>favstats()</code> comes from the <code>mosaic</code> package and we will use some data from the <code>tigerstats</code> package, so make sure that both are loaded:</p>

<pre><code>require(mosaic)
require(tigerstats)
</code></pre>

<p><strong>Note:</strong>  If you are not working with the R Studio server hosted by Georgetown College, then you will need install <code>tigerstats</code> on your own machine.  You can get the current version from <a href="http://github.com">Github</a> by first installing the <code>devtools</code> package from the CRAN repository, and then running the following commands in a fresh R session:</p>

<pre><code>require(devtools)
install_github(repo = "homerhanumat/tigerstats")
</code></pre>

<p>In this tutorial we will work with the <code>m111survey</code> data frame from <code>tigerstats</code> package.  If you are not yet familiar with this data, then run:</p>

<pre><code>data(m111survey)
View(m111survey)
help(m111survey)
</code></pre>

<p>Remember that you can also learn about the types of each variable in the data frame with the <code>str()</code> function:</p>

<pre><code>str(m111survey)

## 'data.frame':	71 obs. of  12 variables:
##  $ height         : num  76 74 64 62 72 70.8 70 79 59 67 ...
##  $ ideal_ht       : num  78 76 NA 65 72 NA 72 76 61 67 ...
##  $ sleep          : num  9.5 7 9 7 8 10 4 6 7 7 ...
##  $ fastest        : int  119 110 85 100 95 100 85 160 90 90 ...
##  $ weight_feel    : Factor w/ 3 levels "1_underweight",..: 1 2 2 1 1 3 2 2 2 3 ...
##  $ love_first     : Factor w/ 2 levels "no","yes": 1 1 1 1 1 1 1 1 1 1 ...
##  $ extra_life     : Factor w/ 2 levels "no","yes": 2 2 1 1 2 1 2 2 2 1 ...
##  $ seat           : Factor w/ 3 levels "1_front","2_middle",..: 1 2 2 1 3 1 1 3 3 2 ...
##  $ GPA            : num  3.56 2.5 3.8 3.5 3.2 3.1 3.68 2.7 2.8 NA ...
##  $ enough_Sleep   : Factor w/ 2 levels "no","yes": 1 1 1 1 1 2 1 2 1 2 ...
##  $ sex            : Factor w/ 2 levels "female","male": 2 2 1 1 2 2 2 2 1 1 ...
##  $ diff.ideal.act.: num  2 2 NA 3 0 NA 2 -3 2 0 ...
</code></pre>

<h2 id="studying-one-numerical-variable">Studying One Numerical Variable</h2>

<p>“favstats” is short for “favorite statistics”:  it will give you the some of the most popular summary statistics for numerical variables.</p>

<p>Suppose, for example, that you want to know how fast people in the <code>m111survey</code> sample tend to drive, when they drive their fastest. The you want to study the numerical variable <strong>fastest</strong>:  the fastest speed each person claims to have ever driven, measured in miles per hour.  Just try <code>favstats()</code> with the usual formula-data input:</p>

<pre><code>favstats(~fastest, data = m111survey)

##  min   Q1 median    Q3 max  mean    sd  n missing
##   60 90.5    102 119.5 190 105.9 20.88 71       0
</code></pre>

<p>Remember what each of the statistics tells you:</p>

<ul>
  <li>The minimum fastest speed drive by anyone in the survery was 60 mph.</li>
  <li>The maximum fastest speed was 190 mph.</li>
  <li>About 25% of the survey participants drove less than 90.5 mph (the First Quartile)</li>
  <li>About 75% percent of the survey participants drove less than 119.5 mph (the Third Quartile)</li>
  <li>About 50% of the participants drove less than 102 mph (the median)</li>
  <li>The mean speed for this sample of students was about 105.9 mph …</li>
  <li>… give or take about 20.9 mph or so (the standard deviation).</li>
</ul>

<p>We also see that</p>

<ul>
  <li>71 people answered the question about fastest speed;</li>
  <li>Nobody did not answer (missing = 0).</li>
</ul>

<h2 id="studying-the-relationship-between-a-numerical-variable-and-a-factor-variable">Studying the Relationship Between a Numerical Variable and a Factor Variable</h2>

<p>Studying the relationship between a numerical variable and factor variable involves what is popularly known as “breaking the data into groups” based on the values of the factor variable.  More formally, we obtain the conditional distributions of the numerical variable given the various possible values of the factor variable, and look for difference between these distributions.  If we see large differences. then we know that the factor variable “makes a difference” in the likely values of the numerical variable, i.e., the two variable are related.</p>

<p>For example we might want to know if the fastest speed one drives might be related to one’s sex.  The relevant variables in <code>m111survey</code> are then the numerical <strong>fastest</strong> and the factor variable <strong>sex</strong>.</p>

<p>In formula-data input for <code>favstats()</code> the formula always follows the format:</p>

<script type="math/tex; mode=display">numerical \sim factor.</script>

<p>So we run the following command:</p>

<pre><code>favstats(fastest ~ sex, data = m111survey)

##   .group min Q1 median    Q3 max  mean    sd  n missing
## 1 female  60 90     95 110.0 145 100.0 17.61 40       0
## 2   male  85 99    110 122.5 190 113.5 22.57 31       0
</code></pre>

<p>The first row of the output gives a summary of the conditional distribution of <strong>fastest</strong>, given that <strong>sex</strong> is female.</p>

<p>The second row summarizes the conditional distribution of <strong>fastest</strong>, given that <strong>sex</strong> is male.</p>

<p>The two conditional distribution are not the same.  For example, we see that on average females drove about 100 mph, whereas the guys drove about 113.4 mph.  The guys appear to drive faster than the gals:  for this sample of students, fastest speed drive does indeed appear to be related to sex.</p>

<h2 id="limiting-the-output">Limiting the Output</h2>

<p>Sometimes you want just a few of the numbers from <code>favstats()</code>.  If you would like to display only those numbers you can do so using brackets “[” and “]”, along with a list of the names of the columns you want to see.  For example, to display only the means and the standard deviations for <strong>fastest</strong>, ask for:</p>

<pre><code>favstats(fastest, data = m111survey)[c("mean", "sd")]

##   mean    sd
##  105.9 20.88
</code></pre>

<p>The brackets are R’s way of locating particular parts of an object.  If you want to display more than one column, make sure to combine their names (in quotes) in a list with the <code>c()</code> function, as shown above.</p>

<p>When you are breaking a numerical variable into groups, you will probably also want to see the group names:  this requires the addition of the column named <code>.group</code>.  Therefore, to see just the mean and the standard deviation for <strong>fastest</strong> broken down by <strong>sex</strong>, ask for:</p>

<pre><code>favstats(fastest ~ sex, data = m111survey)[c(".group", "mean", "sd")]

##   .group  mean    sd
## 1 female 100.0 17.61
## 2   male 113.5 22.57
</code></pre>

<h2 id="warning">Warning</h2>

<p><code>favstats()</code> specializes in numerical variables:  it won’t help you to study a factor variable by itself.  Look what happens when you try to use it to study the factor variable <strong>sex</strong>:</p>

<pre><code>favstats(~sex, data = m111survey)

## Error: non-numeric argument to binary operator
</code></pre>

</div>
  
  


    </article>
  
  <div class="pagination">
    
      <a class="prev" href="/blog/page/5/">&larr; Older</a>
    
    <a href="/blog/archives">Blog Archives</a>
    
    <a class="next" href="/blog/page/3/">Newer &rarr;</a>
    
  </div>
</div>
<aside class="sidebar">
  
    <section>
  <h1>Recent Posts</h1>
  <ul id="recent_posts">
    
      <li class="post">
        <a href="/blog/2014/04/28/qnormtutorial/">Qnorm() Tutorial</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/04/13/roctopress/">Roctopress: Configure Your Octopress Blog for R</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/04/08/reasons-to-teach-with-R-2/">Five Reasons to Teach Elementary Statistics With R: #2</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/04/05/tigerstatsintro/">Five Reasons to Teach Elementary Statistics With R: #1</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/02/28/xtabstutorial/">Xtabs() Tutorial</a>
      </li>
    
  </ul>
</section>

<section>
  <h1>GitHub Repos</h1>
  <ul id="gh_repos">
    <li class="loading">Status updating&#8230;</li>
  </ul>
  
  <a href="https://github.com/homerhanumat">@homerhanumat</a> on GitHub
  
  <script type="text/javascript">
    $(document).ready(function(){
        if (!window.jXHR){
            var jxhr = document.createElement('script');
            jxhr.type = 'text/javascript';
            jxhr.src = '/javascripts/libs/jXHR.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(jxhr, s);
        }

        github.showRepos({
            user: 'homerhanumat',
            count: 5,
            skip_forks: true,
            target: '#gh_repos'
        });
    });
  </script>
  <script src="/javascripts/github.js" type="text/javascript"> </script>
</section>



<section class="googleplus">
  <h1>
    <a href="https://plus.google.com/101037539642604924807?rel=author">
      <img src="http://www.google.com/images/icons/ui/gprofile_button-32.png" width="32" height="32">
      Google+
    </a>
  </h1>
</section>


<section>
  <h1>Categories</h1>
  <ul id="categories">
    <li class='category'><a href='/blog/categories/r/'>R (3)</a></li>
<li class='category'><a href='/blog/categories/student-focused-tutorials/'>Student-Focused Tutorials (15)</a></li>
<li class='category'><a href='/blog/categories/tech-note/'>Tech Note (2)</a></li>

  </ul>
</section>
<section>
  <h1>Useful Links</h1>
  <ul id="links">
      <li class="post"><a href="http://www.r-bloggers.com" target="_blank">R-Bloggers</a></li>
      <li class="post"><a href="http://mosaic-web.org/" target="_blank">Project Mosaic</a></li>
      <li class="post"><a href="http://statistics.georgetowncollege.edu", target="_blank">My Elementary Course</a></li> 
  </ul>
</section>

  
</aside>

    </div>
  </div>
  <footer role="contentinfo"><p float>
  2014 - Homer White -
  <span class="credit">Powered by <a href="http://octopress.org">Octopress</a>
</p>
<p>      
  <span> <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /></span><span style="color:black">This work is licensed under a </span><a style="color:black" rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/deed.en_US">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
  </span>
</p>

</footer>
  

<script type="text/javascript">
      var disqus_shortname = 'homerhanumatgithubio';
      
        
        var disqus_script = 'count.js';
      
    (function () {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/' + disqus_script;
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    }());
</script>



<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id; js.async = true;
  js.src = "//connect.facebook.net/en_US/all.js#appId=212934732101925&xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>









</body>
</html>
